export default {
  en: {
    //labels
    officeNameOrElectoralWard: "Office Name/Electoral ward",
    departmentName: "Department Name",
    committeeName: "Committee Name",
    financialYear: "Financial Year",
    docketType: "Docket Type",
    subjectSerialNumber: "Subject Serial Number",
    subjectDate: "Subject Date",
    approvedDate: "Approved Date",
    subject: "Subject",
    description: "Description",
    attachment: "Attachment",
    subjectStatus: "Subject Status",
    subjectSummary: "Subject Summary",
    amount: "Amount",
    remark: "Remark",
    outwardNumber: "Outward Number",
    outwardDate: "Outward Date",
    inwardNumber: "Inward Number",
    inwardDate: "Inward Date",
    fromDate: "From Date",
    toDate: "To Date",
    agendaNo: "Agenda No.",
    agendaDate: "Agenda Date",
    committeeMemberName: "Name of Committee Member",
    attendanceMethod: "Attendance captured from",
    proceedingDate: "Proceeding Date",
    onHoldSubjects: "On Hold Subjects",
    nameOfSuchak: "Name of Pointer",
    nameOfAnumodak: "Name of Approver",
    month: "Month",
    year: "Year",
    ward: "Ward",
    corporatorName: "Name of Corporator",
    captureAttendance: "Capture Attendance",
    fixedAmountPerMonth: "Fixed Amount (Per Month)",
    amountForMeetingAttendedInTheMonth: "Amount for Meeting Attended in the Month",
    deductedOtherAmount: "Deducted Other Amount",
    healthInsuranceCharges: "Health Insurance Charges",
    grandTotal: "Grand Total",
    dateOfHonorariumProcess: "Date of Honorarium Process",
    firstNameEn: "First Name (in English)",
    middleNameEn: "Middle Name (in English)",
    lastNameEn: "Last Name (in English)",
    firstNameMr: "First Name (in Marathi)",
    middleNameMr: "Middle Name (in Marathi)",
    lastNameMr: "Last Name (in Marathi)",
    gender: "Gender",
    religion: "Religion",
    caste: "Caste",
    electedWard: "Elected Ward",
    dateOfBirth: "Date of Birth",
    casteCertificateNo: "Caste Certificate No.",
    partyName: "Party Name",
    idProofCategory: "ID Proof Category",
    panNo: "Pan No",
    idProofNo: "ID Proof No.",
    mobileNo: "Mobile No",
    emailAddress: "Email Address",
    address: "Address",
    electedDate: "Elected Date",
    monthlyHonorariumAmount: "Monthly Honorarium Amount",
    resignDate: "Resign Date",
    reason: "Reason",
    bankName: "Bank Name",
    branchName: "Branch Name",
    savingAccountNo: "Saving's Account No.",
    bankIFSCcode: "Bank IFSC Code",
    bankMICRcode: "Bank MICR Code",
    fullName: "Fullname",
    nominatedCorporator: "Nominated Corporator",

    search: "Search",
    preview: "Preview",
    addFile: "Add File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    print: "Print",

    /////////////////////////////////////////////
    docketId: "Docket Id",
    /////////////////////////////////////////////
    departmentId: "Department Id",
    subjectId: "Subject Id",
    inwardOutWardDate: "Inward Out Ward Date:",
    prepareAgenda: "Prepare Agenda",
    selectCommitteeName: "Select Committee Name",
    agendaSubject: "Agenda Subject",
    agendaOutwardDate: "Agenda Outward Date",
    coveringLetterSubject: "Covering Letter Subject",
    coveringLetterNote: "Covering Letter Note",
    agendaDescription: "Agenda Description",
    tip: "Tip",
    sabhavruttant: "Sabhavruttant",
    btnSaveText: "SAVE",
    selectDockets: "Select Dockets",
  },
  mr: {
    //labels
    officeNameOrElectoralWard: "कार्यालयाचे नाव / निवडणूक प्रभाग",
    departmentName: "विभागाचे नाव",
    committeeName: "समितीचे नाव",
    financialYear: "आर्थिक वर्ष",
    docketType: "डॉकेट प्रकार",
    subjectSerialNumber: "विषय अनुक्रमांक",
    subjectDate: "विषयाची तारीख",
    approvedDate: "मंजूर तारीख",
    subject: "विषय",
    description: "वर्णन",
    attachment: "संलग्नक",
    subjectStatus: "विषय स्थिती",
    subjectSummary: "विषय सारांश",
    amount: "रक्कम",
    remark: "टिप्पणी",
    outwardNumber: "बाह्य क्र.",
    outwardDate: "बाह्य तारीख",
    inwardNumber: "आवक क्र.",
    inwardDate: "आवक तारीख",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    agendaNo: "कार्यसूची क्रमांक",
    agendaDate: "कार्यसूची तारीख",
    committeeMemberName: "समिती सदस्याचे नाव",
    attendanceMethod: "उपस्थितीची पद्धत",
    proceedingDate: "प्रक्रिया तारीख",
    onHoldSubjects: "होल्डवरचे विषय",
    nameOfSuchak: "सुचकाचे नाव",
    nameOfAnumodak: "अनुमोदकाचे नाव",
    month: "महिना",
    year: "वर्ष",
    ward: "वार्ड",
    corporatorName: "नगरसेवकाचे नाव",
    captureAttendance: "उपस्थिती मिळवा",
    fixedAmountPerMonth: "निश्चित रक्कम (प्रति महिना)",
    amountForMeetingAttendedInTheMonth: "महिन्यात उपस्थित मीटिंगची रक्कम",
    deductedOtherAmount: "इतर रक्कम वजा केली",
    healthInsuranceCharges: "आरोग्य विमा शुल्क",
    grandTotal: "पूर्ण रक्कम",
    dateOfHonorariumProcess: "मानधन प्रक्रियेची तारीख",
    firstNameEn: "पहिले नाव (इंग्रजीत)",
    middleNameEn: "मधले नाव (इंग्रजीत)",
    lastNameEn: "शेवटचं नाव (इंग्रजीत)",
    firstNameMr: "पहिले नाव (मराठीत)",
    middleNameMr: "मधले नाव (मराठीत)",
    lastNameMr: "शेवटचं नाव (मराठीत)",
    gender: "लिंग",
    religion: "धर्म",
    caste: "जात",
    electedWard: "निवडून आलेला प्रभाग",
    dateOfBirth: "जन्मतारीख",
    casteCertificateNo: "जात प्रमाणपत्र क्र.",
    partyName: "पार्टीचे नाव",
    idProofCategory: "आयडी प्रूफ श्रेणी",
    panNo: "पॅन क्रं",
    idProofNo: "आयडी प्रूफ क्र.",
    mobileNo: "मोबाईल नं",
    emailAddress: "इमेल पत्ता",
    address: "पत्ता",
    electedDate: "निवडलेली तारीख",
    monthlyHonorariumAmount: "मासिक मानधन रक्कम",
    resignDate: "राजीनाम्याची तारीख",
    reason: "कारण",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    savingAccountNo: "बचत खाते क्र.",
    bankIFSCcode: "बँक आयएफएससी कोड",
    bankMICRcode: "बँक एमआयसीआर कोड",
    nominatedCorporator: "नामनिर्देशित नगरसेवक",

    search: "शोधा",
    preview: "पूर्वावलोकन",
    addFile: "फाइल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    fullName: "पूर्ण नाव",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    print: "छापणे",

    ///////////////////////////////////////////
    docketId: "डॉकेट आयडी",
    /////////////////////////////////////////////
    departmentId: "विभाग आयडी",
    subjectId: "विषय आयडी",
    inwardOutWardDate: "आवक आउट वॉर्ड दिनांक",
    prepareAgenda: "अजेंडा तयार करा",
    selectCommitteeName: "समितीचे नाव निवडा",
    agendaSubject: "अजेंडा विषय",
    agendaOutwardDate: "अजेंडा जावक तारीख",
    coveringLetterSubject: "कव्हरिंग लेटर विषय",
    coveringLetterNote: "कव्हरिंग लेटर नोट",
    agendaDescription: "अजेंडा वर्णन",
    tip: "टीप",
    sabhavruttant: "सर्वज्ञ",
    btnSaveTextMr: "जतन करा",
    selectDockets: "डॉकेट निवडा",
  },
};
