export default {
    en: {
        mediumPrefix: "Medium Prefix",
        nameOfMedium: "Name of Medium",
        infoTransferMediumMaster: "Medium Master",
        add: 'Add',
        srNo: "Sr.No",
        actions: "Actions",
        address: "Address",
        save: 'Save',
        update: 'Update',
        clear: 'Clear',
        exit: 'Exit',
        back: 'Back',
        rtiApplication: "RTI Application",
        applicantFirstName: "Applicant First Name",
        applicantMiddleName: "Applicant Middle Name",
        applicantLastName: "Applicant Last Name",
        gender: "Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        pinCode: "Pincode",
        contactDetails: "Contact Details",
        emailId: "Email Id",
        education: "Education",
        educated: "Educated",
        unEducated: "Uneducated",
        wardkey: "Ward Name",
        zoneKey: "Zone Name",
        departmentKey: "Department Name",
        subDepartmentKey: "Sub department Name",
        isApplicantBelowToPovertyLine: "Is applicant below to poverty line?",
        bplCardNo: "BPL Card Number",
        yearOfIssues: "Year of Issues",
        issuingAuthority: "Issuing Authority",
        informationSubject: "Information Subject",
        fromDate: "From Date(Related Information)",
        toDate: "To Date(Related Information)",
        description: "Descrition of required Information",
        yes: "Yes",
        no: "No",
        requiredInfoDeliveryDetails: "Required Information Delivery Details",
        byPost: "By Post",
        personally: "Personally",
        softCopy: "Soft Copy",
        departmentKey: "Department Name",
        subDepartmentKey: "Sub Department Name",
        wardKey: "Ward Name",

        rtiAppeal: "RTI Appeal",
        applicationNo: "Application No",
        search: "Search",
        descInfoOfOfficer: "Description of Information officer",
        dateOfOfficialorderAgainstAppeal: "Date of Official order against the appeal",
        descriptionOfInfo: "Description of Information",
        reqInfoSubjectAndDesc: "Required Information subject and description",
        concernOfficerDeptnmWhoseInfoRequired: "Concern office or department name whose information required",
        rtiFileDate: "RTI File Date",

        requiredInfoPurpose: "Required Information Purpose",
        reasonForAppeal: "Reason for Appeal",
        paymentModeKey: "Payment Mode",
        paymentAmount: "Application Charges",
        status: "Status",
        rtiApplicationList: "RTI Application List",
        ViewrtiApplication: "View RTI Application",

        appealApplicationNo: "Appeal Application No",
        rtiAppealList: "RTI Appeal List",
        appealFileDate: "Appeal File Date",
        viewrtiAppeal: "View RTI Appeal",
        currentStatus: "Current Status",
        isLOIGenerated: "Is LOI Generated",
        payment: "Payment Done",
        saveAndPay: "Save and Pay",
        completeApplication: "Complete status of Application",
        loiGenerate: "Letter Of Intent",
        closeModal: "Close",
        loiGenerateBtn: "LOI Generate",
        serviceName: "Service Name",
        noOfPages: "No of Pages",
        chargeType: "Charge Type",
        amount: "Amount",
        totalAmount: "Total Amount",
        remark: "Remark",
        viewLoi: "View Letter of Intent",
        print: "Print",
        makePayment: "Make a Payment",
        applicationReceivedBy: "Application Received By",
        cfcuser: "CFC User",
        citizenuser: "Citizen User",
        pcmcportal: "PCMC Portal",
        aaplesarkar: "Aaple Sarkar",
        ratePerPage: "Rate Per Page",
        fileSize: " File size must be less than 2MB",
        fileExtension: "Allow Only .JPG, .PNG, .JPEG  and .PDF files",
        cancel: "Cancel",
        fileUpload: "File Upload",
        addDoc: " ADD DOCUMENTS",
        uploadDoc: "UPLOAD DOCUMENT/IMAGE",
        informationRemark: "Information Ready Remark",
        infoReady: "Information Ready",
        infoPages: "Information Pages",
        selectedReturnMedia: "Selected Return Media",
        infoReadyDate: "Information Ready Date",
        completeDate: "Complete Date",
        completeRemark: "Complete Remark",
        informationReturnMedia: "Information Return Media",
        hearingSchedule: "Hearing Schedule",
        decisionEntry: "Decision Entry",

        applicantName: "Applicant Name",
        appealNo: "Appeal No",
        scheduleDate: "Schedule Date",
        scheduleTime: "Schedule Time",
        venueForHearing: "Venue for Hearing",
        subject: "Subject",
        rtiApplicationNO: "RTI Application No",

        decisiontakenInHearing:"Decision taken in hearing",
      
        decisionStatus:"Decision Status by department",
        decisionOrderAttach:"Decision order upload",
        updloadScanInfoDelivered:"Upload Scan Copy of Information Delivered",
        hearingReschedule:"Hearing Reschedule",
        completeAppeal:"Complete Status of Appeal",
        decisionDetails:"Decision Details",
        documents:"Documents",
        completeDoc:"Complete Documents"


    },
    mr: {
        mediumPrefix: "माध्यम उपसर्ग",
        nameOfMedium: "माध्यमाचे नाव",
        infoTransferMediumMaster: "माध्यम मास्टर",
        srNo: "अनु क्रमांक",
        actions: "क्रिया",
        add: 'जोडा',
        save: 'जतन करा',
        update: 'अद्यायावत करा',
        clear: 'रिक्त',
        exit: 'बाहेर पडा',
        rtiApplication: "आरटीआय अर्ज",
        applicantFirstName: "अर्जदार प्रथम नाव",
        applicantMiddleName: "अर्जदाराचे मधले नाव",
        applicantLastName: "अर्जदार आडनाव",
        gender: "लिंग",
        male: "पुरुष",
        female: "स्त्री",
        other: "इतर",
        pinCode: "पिन कोड",
        contactDetails: "संपर्काची माहिती",
        emailId: "ई-मेल आयडी",
        education: "शिक्षण",
        educated: "शिक्षित",
        unEducated: "अशिक्षित",
        wardKey: "प्रभागाचे नाव",
        zoneKey: "झोनचे नाव",
        departmentKey: "विभागाचे नाव",
        subDepartmentKey: "उपविभागाचे नाव",
        isApplicantBelowToPovertyLine: "अर्जदार दारिद्र्य रेषेखालील आहे का?",
        bplCardNo: "बीपीएल कार्ड क्र",
        yearOfIssues: "कार्ड वितरीत वर्ष",
        issuingAuthority: "कार्ड मान्यता अधिकारी यांचे नाव",
        informationSubject: "माहितीचा विषय",
        fromDate: "तारखेपासून (संबंधित माहिती)",
        toDate: "तारखेपर्यंत (संबंधित माहिती)",
        description: "आवश्यक असलेल्या माहितीचे वर्णन",
        yes: "होय",
        no: "नाही",
        requiredInfoDeliveryDetails: "आवश्यक माहिती वितरण तपशील",
        byPost: "पोस्टाने",
        personally: "वैयक्तिकरित्या",
        softCopy: "सॉफ्टकॉपी",
        address: "पत्ता",
        departmentKey: "विभागाचे नाव",
        subDepartmentKey: "उपविभागाचे नाव",
        wardKey: "प्रभागाचे नाव",


        rtiAppeal: "आरटीआय आवाहन",
        applicationNo: "अर्ज क्र",
        search: "शोधा",
        descInfoOfOfficer: "माहिती अधिकाऱ्याचा तपशील",
        dateOfOfficialorderAgainstAppeal: "ज्या आदेशाविरुद्ध अपिल केले तो आदेश मिळाल्याची दिनांक",

        descriptionOfInfo: "माहितीचा तपशील",
        reqInfoSubjectAndDesc: "आवश्यक असलेल्या माहितीचे स्वरूप आणि विषय",
        concernOfficerDeptnmWhoseInfoRequired: "माहिती ज्या कार्यालयाशी किंवा विभागाशी संबंधित विभागाशी आहे त्याचे नाव",
        requiredInfoPurpose: "ज्यासाठी माहिती आवश्यक आहे ते प्रयोजन",
        reasonForAppeal: "अपिलाचे कारण",
        paymentModeKey: "पेमेंट मोड",
        paymentAmount: "अर्ज शुल्क",
        rtiFileDate: "आरटीआय फाइलची तारीख",
        status: "स्थिती",
        rtiApplicationList: "आरटीआय अर्ज यादी",
        ViewrtiApplication: "आरटीआय अर्ज पहा",

        appealApplicationNo: "अपील अर्ज क्र",
        rtiAppealList: "आरटीआय अपील यादी",
        appealFileDate: "अपील फाइलची तारीख",
        viewrtiAppeal: "आरटीआय अपील पहा",
        currentStatus: "वर्तमान स्थिती",
        loiGenerate: "उद्देशीय पत्र",
        isLOIGenerated: "LOI व्युत्पन्न करणे आवश्यक आहे",
        payment: "पैसे भरा",
        saveAndPay: "जतन करा आणि पैसे द्या",
        completeApplication: "अर्जाची संपूर्ण स्थिती",
        closeModal: "बंद करा",
        loiGenerateBtn: "loi व्युत्पन्न करा",
        serviceName: "सेवेचे नाव",
        noOfPages: "पृष्ठांची संख्या",
        chargeType: "चार्ज प्रकार",
        amount: "रक्कम",
        totalAmount: "एकूण रक्कम",
        remark: "शेरा",
        completeRemark: "पूर्ण शेरा",

        viewLoi: "हेतू पत्र पहा",
        print: "छापणे",
        makePayment: 'पैसे भरा',
        applicationReceivedBy: "द्वारे अर्ज प्राप्त झाला",
        cfcuser: "cfc वापरकर्ता",
        citizenuser: "नागरिक वापरकर्ता",
        pcmcportal: "PCMC पोर्टल",
        aaplesarkar: "आपल सरकार",
        ratePerPage: "प्रति पृष्ठ दर",
        fileSize: " फाइल आकार 2MB पेक्षा कमी असणे आवश्यक आहे",
        fileExtension: "फक्त .JPG, .PNG, .JPEG आणि .PDF फाइल्सना अनुमती द्या",
        cancel: "रद्द करा",
        fileUpload: "फाइल अपलोड",
        addDoc: " दस्तऐवज जोडा",
        uploadDoc: "दस्तऐवज/इमेज अपलोड करा",
        informationRemark: "माहिती तयार टिप्पणी",
        inforReady: "माहिती तयार",
        infoPages: "माहिती पृष्ठे",
        selectedReturnMedia: "माहिती रिटर्न मीडिया",


        infoReadyDate: "माहिती तयार तारीख",
        completeDate: "पूर्ण तारीख",
        informationReturnMedia: "माहिती रिटर्न मीडिया",
        hearingSchedule: "सुनावणीचे वेळापत्रक",
        decisionEntry: "निर्णय प्रवेश",


        applicantName: "अर्जदाराचे नाव",
        appealNo: "अपील क्र",
        scheduleDate: "शेड्यूल तारीख",
        scheduleTime: "वेळ शेड्यूल करा",
        venueForHearing: "सुनावणीचे ठिकाण",

        subject: "विषय",
        rtiApplicationNO: "आरटीआय अर्ज क्र",
        decisiontakenInHearing:"सुनावणीत घेतलेला निर्णय",
      
        decisionStatus:"विभागानुसार निर्णयाची स्थिती",
        decisionOrderAttach:"निर्णय ऑर्डर अपलोड",
        updloadScanInfoDelivered:"वितरित केलेल्या माहितीची स्कॅन प्रत अपलोड करा",
        hearingReschedule:"सुनावणीचे पुन्हा वेळापत्रक",
        completeAppeal:"अपीलची संपूर्ण स्थिती",
        decisionDetails:"निर्णय तपशील",
        documents:"दस्तऐवज",
        completeDoc:"पूर्ण कागदपत्रे"





    }
}