const schoolLabels = {
  en: {
    type: "commonLabels",
    module: "School",

    studentDailyAttendance: "Student Daily Attendance",
    classTimetable: "Class Timetable",

    studentList: "Student List",
    selectSchool: "Select School",
    schoolRequired: "School is required",
    selectAcademicYear: "Select Academic Year",
    academicYearRequired: "Academic Year is required",
    selectClass: "Select Class",
    classRequired: "Class is required",
    selectDivision: "Select Division",
    divisionRequired: "Division is required",
    date: "Date",
    dateRequired: "Date is required",
    studentName: "Student Name",
    presentAbsent: "Present/Absent",
    examName: "Exam Name",
    examNameRequired: "Exam Name is required",
    examDate: "Exam Date",
    examDateRequired: "Exam Date is required",
    examFromTime: "Exam From Time",
    examFromTimeRequired: "Exam From Time is required",
    examToTime: "Exam To Time",
    examToTimeRequired: "Exam To Time is required",
    srNo: "Sr.No",

    schoolName: "School Name",
    studentGeneralRegisterNumber: "Student General Register Number",
    admissionDate: "Admission Date",
    rollNumber: "Roll Number",
    divisionName: "Division Name",
    firstName: " First Name",
    middleName: "Middle Name",
    surnameName: "Surname Name",
    address: "Address",
    mobileNumber: "Mobile Number",
    emailID: "Email ID",
    className: "Class Name",
    division: "Division",
    dateOfbirth: "Date of Birth",
    birthAddress: "Birth Address",
    remark: "Remark",
    selectStudent: "Select Student",
    studentRequired: "Student is required",

    addNewTimetable: "Add New Timetable",
    updateTimetable: "Update Timetable",
    periodList: "Period List",
    day: "Day",
    from: "From",
    to: "To",
    subject: "Subject",
    teacher: "Teacher",
    recess: "Recess",

    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    7: "Saturday",

    search: "Search",
    clear: "Clear",
    teacherParentCommunication: "Teacher Parent Communication",
    add: "Add",
    save: "Save",
    edit: "Edit",
    toggle: "Toggle",
    updateAttendance: "Update Attendance",
    update: "Update",
    exit: "Exit",

    success: "Success!",
    attendanceUpdated: "Attendance Updated Successfully",
    examSaved: "Exam Saved Successfully",
    examUpdated: "Exam Updated Successfully",
    error: "Error!",
    admissionRegitrationNo: "Admission Reg. No.",

    aadharNumber: "Aadhar Number",
    schoolTeacher: "School Teacher",
    gender: "Gender",
    male: "Male",
    female: "Female",
    motherTongue: "Mother Tongue",
    permanentAddress: "Permanent Address",
    pincode: "Pincode",
    message: "Message",
    teacherName: "Teacher Name",
    actions: "Actions",

    studentAdmissionForm: "Student Admission Form",
    zoneName: "Zone Name",
    wardName: "Ward Name",
    studentFirstName: "Student First Name",
    studentMiddleName: "Student Middle Name",
    studentLastName: "Student Last Name",
    fatherFirstName: "Father First Name",
    fatherMiddleName: "Father Middle Name",
    fatherLastName: "Father Last Name",
    motherName: "Mother First Name",
    motherMiddleName: "Mother Middle Name",
    motherLastName: "Mother Last Name",
    religion: "Religion",
    casteName: "Caste Category",
    citizenship: "Citizenship",
    birthPlace: "Birth Place",
    studentState: "Student State",
    studentDist: "Student District",
    parentAddress: "Parent Address",
    parentOccupation: "Parent Occupation",
    fatherMobileNumber: " Father Mobile Number",
    motherMobileNumber: " Mother Mobile Number",
    permanentAddress: "Permanent Address",
    parentFullName: "Parent Full Name",
    colony: "Colony",
    district: "District",
    state: "State",
    lastSchoolName: "Last School Name -if applicable",
    lastSchoolAdmissionDate: "Last School Admission Date -if applicable",
    lastSchoolAndFromWhenStudying: "Last School and from when Studying",
    lastSchoolLeavingDate: "Last School Leaving Date",
    studentBehaviour: "Student Behaviour",
    reasonForLeavingSchool: "Reason for Leaving School",

    selectExam: "Select Examination",
    exam: "Examination",
    examMarks: "Exam Marks",
    examRequired: "Examination is required",
    selectTerm: "Select Term",
    term: "Term",
    termRequired: "Term is required",
    marksObtained: "Marks Obtained",
    outOfMarks: "Out of Marks",
    outOfMarksRequired: "Out of Marks is required",
    passingMarks: "Passing Marks",
    passingMarksRequired: "Passing Marks is required",
    marksError: "Marks should be less than or equal to out of marks",
    updateMarks: "Update Marks",
    marksUpdated: "Marks Updated Successfully",

    deactivate: "Deactivate",
    activate: "Activate",
    areYouSureToDeactivate: "Are you sure to deactivate this record?",
    areYouSureToActivate: "Are you sure to activate this record?",
    deactivateSuccess: "Record Deactivated Successfully",
    activateSuccess: "Record Activated Successfully",
    printReport: "Print Report",
    classTimetableReport: "Class Timetable Report",
    generateReport: "Generate Report",
    fromDate: "From Date",
    toDate: "To Date",
    studentsAttendanceReport: "Students Attendance Report",
    schoolLeavingCert: "School Leaving Certificate",
    studentBonafideCert: "Student Bonafide Certificate",
  },

  mr: {
    type: "commonLabels",
    module: "शाळा",

    studentDailyAttendance: "विद्यार्थी दैनिक उपस्थिती",
    classTimetable: "वर्ग वेळापत्रक",

    studentList: "विद्यार्थी सूची",
    selectSchool: "शाळा निवडा",
    schoolRequired: "शाळा आवश्यक आहे",
    selectAcademicYear: "शैक्षणिक वर्ष निवडा",
    academicYearRequired: "शैक्षणिक वर्ष आवश्यक आहे",
    selectClass: "वर्ग निवडा",
    classRequired: "वर्ग आवश्यक आहे",
    selectDivision: "तुकडी निवडा",
    divisionRequired: "तुकडी आवश्यक आहे",
    date: "तारीख",
    dateRequired: "तारीख आवश्यक आहे",
    studentName: "विद्यार्थ्याचे नाव",
    presentAbsent: "उपस्थित/अनुपस्थित",
    examName: "परीक्षेचे नाव",
    examNameRequired: "परीक्षेचे नाव आवश्यक आहे",
    examDate: "परीक्षेची तारीख",
    examDateRequired: "परीक्षेची तारीख आवश्यक आहे",
    examFromTime: "सुरवातीची वेळ",
    examFromTimeRequired: "सुरवातीची वेळ आवश्यक आहे",
    examToTime: "समाप्तीची वेळ",
    examToTimeRequired: "समाप्तीची वेळ आवश्यक आहे",
    srNo: "अनु क्रमांक",

    schoolName: "शाळेचे नाव",
    studentGeneralRegisterNumber: "अर्ज क्रमाांक",
    admissionDate: "प्रवेशाची तारीख",
    rollNumber: "हजेरी क्रमांक",
    divisionName: "विभागणीचे नाव",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    surnameName: "आडनाव",
    address: "पत्ता",
    mobileNumber: "मोबाईल नंबर",
    emailID: "ई - मेल आयडी",
    className: "वर्गाचे नाव",
    division: "विभागणी",
    dateOfbirth: "जन्मतारीख",
    birthAddress: "जन्माचा पत्ता",
    remark: "शेरा",
    selectStudent: "विद्यार्थी निवडा",
    studentRequired: "विद्यार्थी आवश्यक आहे",

    addNewTimetable: "नवीन वेळापत्रक जोडा",
    updateTimetable: "वेळापत्रक अद्यायावत करा",
    periodList: "वेळापत्रक सूची",
    day: "वार  ",
    from: "सुरू",
    to: "समाप्त",
    subject: "विषय",
    teacher: "शिक्षक",
    recess: "सुट्टी",

    2: "सोमवार",
    3: "मंगळवार",
    4: "बुधवार",
    5: "गुरुवार",
    6: "शुक्रवार",
    7: "शनिवार",

    search: "शोधा",
    clear: "हटवा",
    teacherParentCommunication: "शिक्षक पालक संपर्क",
    add: "जोडा",
    save: "जतन करा",
    edit: "संपादित करा",
    toggle: "टॉगल करा",
    updateAttendance: "उपस्थिती अद्यायावत करा",
    update: "अद्यायावत करा",
    exit: "बाहेर पडा",

    success: "सफलता!",
    attendanceUpdated: "उपस्थिती यशस्वीरित्या अद्यायावत केली गेली आहे",
    examSaved: "परीक्षा यशस्वीरित्या जतन केली गेली आहे",
    examUpdated: "परीक्षा यशस्वीरित्या अद्यायावत केली गेली आहे",
    error: "त्रुटी!",
    admissionRegitrationNo: "प्रवेश नोंदणी क्रमांक",

    aadharNumber: "आधार क्रमांक",
    schoolTeacher: "शाळेतील शिक्षक",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    motherTongue: "मातृभाषा",
    permanentAddress: "कायमचा पत्ता",
    pincode: "पिन कोड",
    message: "संदेश",
    teacherName: "शिक्षकाचे नाव",
    actions: "क्रिया",

    studentAdmissionForm: "विद्यार्थी प्रवेश अर्ज",
    zoneName: "झोनचे नाव",
    wardName: "प्रभागाचे नाव",
    studentFirstName: "विद्यार्थ्याचे पहिले नाव",
    studentMiddleName: "विद्यार्थ्याचे मधले नाव",
    studentLastName: "विद्यार्थ्याचे आडनाव",
    fatherFirstName: "वडिलांचे पहिले नाव",
    fatherMiddleName: "वडिलांचे मधले नाव",
    fatherLastName: "वडिलांचे आडनाव",
    motherName: "आईचे पहिले नाव",
    motherMiddleName: "आईचे मधले नाव",
    motherLastName: "आईचे आडनाव",
    religion: "धर्म",
    casteName: "जातीचे नाव",
    citizenship: "नागरिकत्व",
    birthPlace: "जन्म ठिकाण",
    studentState: "विद्यार्थी राज्य",
    studentDist: "विद्यार्थी जिल्हा",
    parentAddress: "पालकांचा पत्ता",
    parentOccupation: "पालकांचा व्यवसाय ",
    fatherMobileNumber: "वडिलांचा मोबाईल नंबर ",
    motherMobileNumber: "आईचा मोबाईल नंबर ",
    permanentAddress: "कायमचा पत्ता",
    parentFullName: "पालकांचे पूर्ण नाव",
    colony: "वसाहत",
    district: "जिल्हा",
    state: "राज्य",
    lastSchoolName: "शेवटच्या शाळेचे नाव -जर लागू असेल तर",
    lastSchoolAdmissionDate: "शाळा प्रवेशाची शेवटची तारीख - लागू असल्यास",
    lastSchoolAndFromWhenStudying: "शेवटचा वर्ग आणि कधीपासून अभ्यास",
    lastSchoolLeavingDate: "शाळा सोडण्याची शेवटची तारीख",
    studentBehaviour: "विद्यार्थ्यांचे वर्तन",
    reasonForLeavingSchool: "शाळा सोडण्याचे कारण",

    selectExam: "परीक्षा निवडा",
    exam: "परीक्षा",
    examMarks: "परीक्षा गुण",
    examRequired: "परीक्षा आवश्यक आहे",
    selectTerm: "अवधी निवडा",
    term: "अवधी",
    termRequired: "अवधी आवश्यक आहे",
    marksObtained: "प्राप्त गुण",
    outOfMarks: "एकूण गुण",
    outOfMarksRequired: "एकूण गुण आवश्यक आहे",
    passingMarks: "उत्तीर्ण गुण",
    passingMarksRequired: "उत्तीर्ण गुण आवश्यक आहे",
    marksError: "मिळवलेले गुण हे एकूण गुणांच्या आत असणे आवश्यक आहे",
    updateMarks: "गुण अद्यायावत करा",
    marksUpdated: "गुण यशस्वीरित्या अद्यायावत केले गेले आहेत",

    deactivate: "निष्क्रिय करा",
    activate: "सक्रिय करा",
    areYouSureToDeactivate: "तुम्हाला निष्क्रिय करण्याची खात्री आहे?",
    areYouSureToActivate: "तुम्हाला सक्रिय करण्याची खात्री आहे?",
    deactivateSuccess: "निष्क्रिय करण्यात यशस्वी झाले",
    activateSuccess: "सक्रिय करण्यात यशस्वी झाले",
    printReport: "अहवाल छापा",
    classTimetableReport: "वर्ग वेळापत्रकाचा अहवाल",
    generateReport: "अहवाल तयार करा",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    studentsAttendanceReport: "विद्यार्थ्यांचा उपस्थिती अहवाल",
    schoolLeavingCert: "शाळा सोडल्याचा दाखला",
    studentBonafideCert: "विद्यार्थी बोनाफाईड प्रमाणपत्र",
  },
};

export default schoolLabels;
