export default {
  en: {
    type: 'commonLabels',

    module: 'Sports Portal',
    // dashboard: 'PCMC Dashboard',
    dashboard: 'Pimpri-Chinchwad Municipal Corporation Dashboard',
    master: 'Masters',
    transaction: 'Transactions',
    report: 'Reports',
    masterPath: 'Sports Portal / Master',
    transactionPath: 'Sports Portal / Transaction ',
    reportPath: 'Sports Portal / Reports ',

    type: 'master',
    // master: "Masters",
    masterPath: 'Sports Portal/ Master',
    master: 'Masters',

    //breadcrum

    facilityNamePath: 'Sports Portal/ Master/ Facility Name Master',
    venuePath: 'Sports Portal/ Master / Venue Master',
    bookingTimePath: 'Sports Portal/ Master / Booking Time Master',
    facilityTypePath: 'Sports Portal/ Master / Facility Type Master',

    //label title
    facilityNameMaster: 'Facility Sub-Type Master',
    venueMaster: 'Facility Venue Master',
    bookingTimeMaster: 'Booking Time Slot Master',
    facilityTypeMaster: 'Facility Type Master',

    //Facility Name Master
    facilityNameId: 'Facility Name ID',
    facilityTypeId: 'Facility Type ID',
    zone: 'Zone',
    ward: 'Ward',
    venueId: 'Venue ID',
    department: 'Department',
    subDepartment: 'Sub Department',
    facilityType: 'Facility Type',
    facilityName: 'Facility Sub-Type Name',
    gisCode: 'GIS Code',
    remark: 'Remark',
    venue: 'Facility Venue',
    date: 'Date',
    fromBookingTime: 'From Booking Time',
    toBookingTime: 'To Booking Time',
    capacity: 'Capacity/TotalMember',

    //other labels

    //Remarks

    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'Exit',
    back: 'Back',
    saveAndNext: 'Save & Next',
    finish: 'Finish',

    type: 'transaction',

    transaction: 'Transaction',

    transactionPath: 'Sports Portal / Transactions ',

    //titles
    sportBooking: 'Sport Booking',
    check: 'Check Availability Status ',
    swimmingPool: 'Swimming Pool',

    //breadcrum

    //titles
    bookingDetails: 'Booking Details',
    personalGroupDetails: 'Personal Group Details',
    personalDetails: 'Personal Details',
    aadharAuthenticationDetails: 'Aadhar Authentication Details',
    eCSDetails: 'ECS Details',
    documentsUpload: 'Documents Upload',

    //other labels
    documentUpload: 'Document Upload',
    bookingDetails: 'Booking Details',
    eCSDetails: 'ECS Details',
    aadharAuthentication: 'Aadhar Authentication',

    fromDate: 'Date(From)',
    formDateTime: 'Form Date Time',
    toDateTime: 'To Date Time',
    toDate: 'Date(To)',
    ward: 'Ward',
    subDepartment: 'Sub Department',
    bookingRegistrationId: 'Booking Registration Id',
    applicationDate: 'Application Date',
    bookingType: 'Booking Type',
    zone: 'Zone',
    department: 'Department',
    facilityType: 'Facility Type',
    facilityName: 'Facility Sub-Type Name',
    venue: 'Venue',
    totalGroupMember: 'Total Group Member',
    groupDetails: 'Group Details',
    title: 'Title',
    firstName: 'First Name',
    middleName: 'Middle Name',
    lastName: 'Last Name',
    gender: 'Gender',
    dateOfBirth: 'Date Of Birth',
    age: 'Age',
    mobileNo: 'Mobile No',
    aadharNo: 'Aadhar No',
    emailAddress: 'Email Address',
    currentAddress: 'Current Address',
    permanentAddress: 'Permanent Address',
    cityName: 'City Name',
    state: 'State',
    pinCode: 'Pin Code',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    bankAccountHolderName: 'Bank Account Holder Name',
    bankAccountNo: 'Bank Account No',
    ifscCode: 'IFSC Code',
    bankAddress: 'Bank Address',
    aadharCard: 'Aadhar Card',
    panCard: 'Pan Card',
    otherDocumentPhoto: 'Other Document Photo',
    checkBox: 'Permanent Address as the Correspondence Address',
    purposeOfBooking: 'Purpose Of Booking',
    bookingPersonDetails: 'Booking Person Details',
    slots: 'Slots',
    timePeriod: 'Time Period',
    sendOtp: 'SEND OTP',
    attachFile: 'Attach File',
    viewImage: 'VIEW IMAGE',
    srNo: 'Sr. No',
    actions: 'Actions',
    Lattitude: 'Lattitude',
    Longitute: 'Longitude',
    Addfile: 'Add File',
    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'Exit',
    back: 'Back',
    saveAndNext: 'Save & Next',
    finish: 'Finish',

    type: 'report',

    reports: 'Reports',

    reportsPath: 'Sports Portal / Reports ',

    //validation
    selectWard: 'Please select a ward',
    selectDate: 'Please select a date',
    selectTitle: 'Please select a title',

    enterFName: 'Please enter first name (In English)',
    enterMName: 'Please enter middle name (In English)',
    enterLName: 'Please enter last name (In English)',

    enterFNameMr: 'Please enter first name (In Marathi) ',
    enterMNameMr: 'Please enter middle name (In Marathi)',
    enterLNameMr: 'Please enter last name (In Marathi)',

    enterFlat: 'Please enter Flat/Building No (In English) ',
    enterApartment: 'Please enter Apartment Name (In English)',
    enterRoadName: 'Please enter Road Name (In English)',
    enterLandmark: 'Please enter Landmark (In English)',
    enterCity: 'Please enter a City Name / Village Name (In English) ',
    state: 'Please enter State (In English)',

    enterFlatMr: 'Please enter Flat/Building No (In Marathi)',
    enterApartmentMr: 'Please enter Apartment Name (In Marathi)',
    enterRoadNameMr: 'Please enter Road Name (In Marathi)',
    enterLandmarkMr: 'Please enter Landmark (In Marathi)',
    enterCityMr: 'Please enter a City Name / Village Name (In Marathi)',
    stateMr: 'Please enter State (In Marathi)',

    enterPinCode: 'Please enter a pincode ',
    enterPhoneNo: 'Please enter a phone no. ',
    enterMobileNo: 'Please enter a mobile no. ',
    enterEmailAddress: 'Please enter an e-mail. ',
    enteraadhaarNo: 'Please enter an aadhaar no. ',
    enterpanNo: 'Please enter an pan no. ',
    enterRemarks: 'Please enter a remark. ',
    enterAge: 'Please enter a Age. ',
    selectGender: 'Please select a Gender ',
    selectReligionby: 'Please select a Religion by Birth',
    selectAdoptionby: 'Please select a Religion by Adoption',
    selectStatusAt: 'Please select a Status at time of marriage',

    //mr
    selectZone: 'Please select a zone',
    selectWard: 'Please select a ward',
    selectZone: 'Please select a Zone',
    selectTitle: 'Please select a Title',
    placeMarriage: 'Please enter Place of Marriage (in English)',
    placeMarriageMr: 'Please enter Place of Marriage (in Marathi)',
    birthProf: 'Please select a Date of Birth Proof',
    ResideProof: 'Please select a Residence Proof',
    IdentyProof: 'Please select a ID Proof',
    witnessAddressC: 'Please enter an Address ',
    witnessRelation: 'Please enter an Relation. ',

    EnterDocName: 'Please enter an Document Name ',

    noOfCopies: 'No of Copies',
    charges: 'Total Charges',
    chargeName: 'Charge Name',
    amount: 'Amount',
    totalInWords: 'Total Charges in Words',
    totalCharges: 'Total Charges',
    applicantDetails: 'Applicant Details',
    chargesDetails: 'Charges Details',
    paymentMode: 'Payment Mode',
    paymentDetails: 'Payment Details',
    paymentType: 'Payment Type',
    receiptDate: 'Receipt Date',
    receiptNumber: 'Receipt Number',
    receiptAmount: 'Receipt Amount',
    ddNo: 'Demand Draft Number',
    ddDate: 'Demand Draft Date',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    bankAccountNo: 'Bank Account No',

    //Modification in Marriage Certificate

    onlyMIMC: 'Modification of Marriage Certificate',
    oldLabel: 'Old Information',
    newLabel: 'New Information',
    gDoc: 'Groom Documents',
    bDoc: 'Bride Documents',
    OwnerDetails: ' Owner Details :',
    Owneraddress: ' Owner Address :',
    document: 'Document Tab :',
    boardheadphoto: 'Board Head Person Photo',
    boardorgphotocpy: 'Board / Organization PhotoCopy',
    panCard: 'Pan Card',
    adharcard: 'Aadhaar card',
    rationcard: 'Ration card',
    electrbill: 'Electric Bill',
    OtherDocument: 'Other Document',
    UploadFile: ' Upload File',
    remarkModel: 'Enter Remark on application',
    APPROVE: 'APPROVE',

    REASSIGN: 'Revert Back',
    onlyeng: 'Must be only characters',
    onlymarathi: 'Must be only  marathi',

    Vvenue: 'Select Venue',
    VbookingType: 'Select Booking Type',
    VfacilityType: 'Select Facility Type',
    VfacilityName: 'Select Facility Sub-Type Name',
    VpurposeOfBooking: 'Select Purpose Of Booking',
    Vcaddres: 'Please enter an current address',

    VbankName: 'Select Bank Name',
    VbranchName: 'Please enter an Branch Name',
    VbankAccountHolderName: 'Please enter an Bank Account Holder Name',
    VbankAccountNo: 'Please enter an Bank Account No',
    VifscCode: 'Please enter an IFSC Code',
    VbankAddress: 'Please enter an Bank Address',
    generateLoi: 'Generate LOI',
    pay: 'Pay',
    receiptModeDetails: 'Receipt Mode Details',
  },
  mr: {
    paymentDetails: 'Payment Details',
    receiptModeDetails: 'पैसे भरावयाची पद्धत',
    type: 'commonLabels',
    pay: 'पैसे भरा',
    module: 'क्रीडा विभाग',
    // dashboard: 'डॅशबोर्ड',
    dashboard: 'पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड',
    master: 'मास्टर्स',
    transaction: 'व्यवहार',
    report: 'अहवाल',
    masterPath: 'क्रीडा विभाग/ मास्टर्स ',
    transactionPath: 'कायदेशीर प्रकरण/ व्यवहार ',
    reportPath: 'कायदेशीर प्रकरण/ अहवाल ',

    type: 'master',

    master: 'मास्टर्स',
    // transaction: "व्यवहार",
    report: 'अहवाल',
    masterPath: 'क्रीडा विभाग/ मास्टर ',
    // transactionPath: "क्रीडा विभाग/ व्यवहार ",

    //breadcrum
    viewImage: 'प्रतिमा पहा',
    facilityNamePath: 'क्रीडा विभाग/ मास्टर्स / सुविधा उप-प्रकार मास्टर',
    venuePath: 'क्रीडा विभाग/ मास्टर्स / ठिकाण मास्टर ',
    bookingTimePath: 'क्रीडा विभाग/ मास्टर्स / बुकिंग वेळ मास्टर्स',
    facilityTypePath: 'क्रीडा विभाग/ मास्टर्स / सुविधा प्रकार मास्टर',

    //titles
    facilityNameMaster: 'सुविधा उप-प्रकार मास्टर',
    facilityTypeMaster: 'सुविधा प्रकार मास्टर',
    venueMaster: 'सुविधा ठिकाण मास्टर',
    bookingTimeMaster: 'बुकिंग वेळ स्लॉट मास्टर',

    //labels
    facilityNameId: 'सुविधा उपप्रकार आयडी',
    facilityTypeId: 'सुविधा प्रकार आयडी',
    venueId: 'ठिकाण आयडी',
    zone: 'झोन',
    ward: 'प्रभाग',
    subDepartment: 'उप विभाग',
    department: 'विभाग',
    facilityType: 'सुविधा प्रकार',
    facilityName: 'सुविधा उपप्रकार नाव',
    gisCode: 'GIS कोड',
    remark: 'शेरा',
    venue: 'सुविधा ठिकाण',
    date: 'तारीख',
    fromBookingTime: '(पासून) बुकिंगची वेळ',
    toBookingTime: '(ते) बुकिंगची वेळ',
    capacity: 'क्षमता/एकूण सदस्य',
    Lattitude: 'अक्षांश',
    Longitute: 'रेखांश',
    cityOrVillage: 'शहर / गाव',
    pincode: 'पिनकोड',
    area: 'क्षेत्राचे नाव',
    name: 'नाव',
    mobile: 'मोबाईल नं.',
    phone: 'दूरध्वनी नं.',
    email: 'इलेक्ट्रॉनिक संदेश',
    aadharNo: 'आधार नं.',
    panNo: 'पॅन नं.',
    advocateCreation: 'वकिल यशस्वीपणे तयार केला',
    advocateDetails: 'वकील तपशील',
    bankDetails: 'बँक तपशील',
    documentUpload: 'दस्तऐवज अपलोड',
    title: 'शीर्षक ',
    fname: 'पहिले नाव ',
    mname: 'मधले  नाव ',
    lname: 'शेवटचे नाव ',
    advocateCategory: 'वकील श्रेणी *',
    nameOfBarCouncil: 'वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *',
    remarks: 'टिप्पणी *',
    bankName: 'बँकेचे नाव *',
    branchName: 'शाखेचे नाव *',
    accountNo: 'खाता क्रमांक *',
    bankIFSC: 'बँक IFSC कोड *',
    bankMICR: 'बँक MICR कोड *',

    VbankName: 'बँकेचे नाव निवडा',
    VbranchName: 'शाखेचे नाव भरा',
    VbankAccountHolderName: 'बँक खातेधारकाचे नाव भरा',
    VbankAccountNo: 'खाता क्रमांक भरा',
    VifscCode: 'बँक IFSC कोड भरा',
    VbankAddress: 'बँकेचा पत्ता भरा',

    Vvenue: 'सुविधा ठिकाण निवडा',

    application: 'अर्ज:',
    aadharCard: 'आधार कार्ड:',
    panCard: 'पॅन कार्ड:',
    barCouncilCertificate: 'वकिलांचे मंडळचे प्रमाणपत्र:',
    bankPassbook: 'बँक पासबुक:',
    subType: 'उप-प्रकार',
    slots: 'स्लॉट',
    timePeriod: 'कालावधी',

    attachFile: 'फाईल जोडा',
    srNo: 'अनुक्रमांक',
    actions: 'क्रिया ',
    sendOtp: 'ओटीपी पाठवा',
    Addfile: 'फाइल जोडा',
    //Remarks
    selectDate: 'कृपया तारीख निवडा',
    selectTitle: 'कृपया शीर्षक निवडा',
    enterFName: 'कृपया पहिले नाव भरा ',
    enterMName: 'कृपया मधले  नाव भरा ',
    enterLName: 'कृपया शेवटचे नाव भरा ',
    selectAdvocateCategory: 'कृपया वकील श्रेणी निवडा',
    enterCouncilName: 'कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा',
    enterArea: 'कृपया क्षेत्राचे नाव भरा ',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा ',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा ',
    enterPinCode: 'कृपया पिनकोड भरा',
    enterPhoneNo: 'कृपया दूरध्वनी नं. भरा',
    enterMobileNo: 'कृपया मोबाईल नं. भरा',
    enterEmailAddress: 'कृपया इलेक्ट्रॉनिक संदेश भरा',
    enteraadhaarNo: 'कृपया आधार नं. भरा',
    enterpanNo: 'कृपया पॅन नं. भरा',
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: 'कृपया टिप्पणी. द्या',

    //buttons
    add: 'जोडा',
    save: 'जतन करा',
    update: 'अद्यायावत करा',
    clear: 'रिक्त',
    exit: 'बाहेर पडा',
    back: 'मागे',
    saveAndNext: 'जतन करा आणि पुढे',
    finish: 'समाप्त',

    type: 'transaction',

    transaction: 'व्यवहार',
    transactionPath: 'कायदेशीर प्रकरण/ व्यवहार ',

    //breadcrum

    //titles
    sportBooking: 'क्रीडा बुकिंग',
    check: 'उपलब्धता स्थिती तपासा',
    swimmingPool: 'जलतरण तलाव',

    //titles
    bookingDetails: 'नोंदणी तपशील',
    personalGroupDetails: 'वैयक्तिक गट तपशील',
    personalDetails: 'वैयक्तिक माहिती',
    aadharAuthentication: 'आधार प्रमाणीकरण',
    aadharAuthenticationDetails: 'आधार प्रमाणीकरण तपशील',
    eCSDetails: 'ECS तपशील',
    documentsUpload: 'दस्तऐवज अपलोड करा',

    //other labels
    fromDate: 'तारीख (पासून)',
    toDate: 'तारीख (ते)',
    formDateTime: '(पासून) तारीख आणि वेळ',
    toDateTime: '(ते) तारीख आणि वेळ',
    bookingRegistrationId: 'बुकिंग नोंदणी आयडी',
    documentUpload: 'दस्तऐवज अपलोड',
    applicationDate: 'अर्जाची तारीख',
    bookingType: 'बुकिंग प्रकार',
    VbookingType: 'बुकिंग प्रकार निवडा',
    zone: 'झोन',
    ward: 'प्रभाग',
    subDepartment: 'उप विभाग',
    department: 'विभाग ',
    facilityType: 'सुविधा प्रकार',
    facilityName: 'सुविधेचे उपप्रकार',
    venue: 'सुविधा ठिकाण',
    totalGroupMember: 'एकूण गट सदस्य',
    groupDetails: 'गट तपशील',
    title: 'शीर्षक',
    firstName: 'पहिले नाव',
    middleName: 'मधले नाव',
    lastName: 'आडनाव',
    gender: 'लिंग',
    dateOfBirth: 'जन्मतारीख',
    age: 'वय',
    mobileNo: 'मोबाईल क्र',
    aadharNo: 'आधार क्र',
    emailAddress: 'ईमेल आयडी',
    currentAddress: 'सध्याचा पत्ता',
    permanentAddress: 'कायमचा पत्ता',
    cityName: 'शहराचे नाव',
    state: 'राज्य',
    pinCode: 'पिन कोड',
    bankName: 'बँकेचे नाव',
    branchName: 'शाखेचे नाव',
    bankAccountHolderName: 'बँक खातेधारकाचे नाव',
    bankAccountNo: 'बँक खाते क्र',
    ifscCode: 'IFSC कोड',
    bankAddress: 'बँकेचा पत्ता',
    aadharCard: 'आधार कार्ड',
    panCard: 'पॅन कार्ड',
    otherDocumentPhoto: 'इतर दस्तऐवज फोटो',
    checkBox: 'सध्याचा रहिवाशी पत्ता कायमचा पत्ता',
    purposeOfBooking: 'बुकिंगचा उद्देश',
    bookingPersonDetails: 'बुकिंग व्यक्ती तपशील',

    //buttons
    add: 'जोडा',
    save: 'जतन करा',
    update: 'अद्यायावत करा',
    clear: 'रिक्त',
    exit: 'बाहेर पडा',
    back: 'मागे',
    saveAndNext: 'जतन करा आणि पुढे',
    finish: 'समाप्त',

    onlyeng: 'फक्त इंग्लिश मध्ये',
    onlymarathi: 'फक्त मराठी मध्ये',
    APPROVE: 'मंजूर करा',

    REASSIGN: 'पुन्हा नियुक्त करा',
    remarkModel: 'अर्जावर टिप्पणी प्रविष्ट करा',

    oldLabel: 'पूर्वीची माहिती',
    newLabel: 'नवीन माहिती',
    onlyMIMC: 'विवाह प्रमाणपत्रात बदल',
    State: 'स्टेट (इंग्लिश मध्ये) ',
    statemr: 'स्टेट (मराठी मध्ये) ',
    UploadFile: 'फाइल अपलोड करा',
    electrbill: 'वीज बिल',
    OtherDocument: 'इतर दस्तऐवज',
    rationcard: 'रेशान कार्ड',
    adharcard: 'आधार कार्ड',
    panCard: 'पॅन कार्ड',
    boardorgphotocpy: 'संस्था किंवा मंडळची दस्तऐवज',
    boardheadphoto: 'मंडळाच्या प्रमुख व्यक्तीच छायाचित्र',
    document: 'दस्तऐवज',
    Owneraddress: ' मंडळच्या प्रमुख व्यक्तीचा पत्ता  :',
    OwnerDetails: 'मंडळच्या प्रमुख व्यक्तीची माहिती',
    titleInmarathi: 'शीर्षक मराठी मध्ये',
    titleInenglish: 'शीर्षक इंग्लिश मध्ये',
    OwnerChkeck: 'जर अर्जादारच विवाह मंडळाचा प्रमुख असेल',
    apply: 'जतन करा',
    ifsc: 'आय एफ एस सी कोड',
    accountNumber: 'खाते क्रमांक',
    bankName: 'बँकेचे नाव',
    branchName: 'शाखेचे नाव',
    bankAccountNo: 'बँक खाते क्रमांक',
    ddDate: 'डिमांड ड्राफ्ट तारीख',
    ddNo: 'डिमांड ड्राफ्ट क्रमांक',
    receiptAmount: 'पावती रक्कम',
    receiptNumber: 'पावती क्रमांक',
    receiptDate: 'पावती तारीख',
    paymentMode: 'Payment Mode',
    paymentType: 'Payment Type',
    receiptModeDetails: 'Receipt Mode Details',
    chargesDetails: 'शुल्क तपशील',
    applicantDetails: 'अर्जदाराची माहिती',
    generateLoi: 'स्विकृती पत्र तयार करा',
    totalCharges: 'एकुण रक्कम',
    totalInWords: 'एकुण अक्षरी रक्कम ',
    amount: 'रक्कम',
    EnterDocName: 'कृपया दस्तऐवजाच नाव भरा ',
    witnessAddressC: 'कृपया पत्ता भरा  ',
    witnessRelation: 'कृपया साक्षीदारशी नाते भरा  ',

    birthProf: 'कृपया जन्म तारीख पुरावा निवडा ',
    ResideProof: 'कृपया रहिवासाचा पुरावा निवडा ',
    IdentyProof: 'कृपया ओळखपत्र पुरावा निवडा ',
    // //Remarks
    selectReligionby: 'कृपया जन्माने धर्म निवडा ',
    selectAdoptionby: 'कृपया दत्तक घेऊन धर्म निवडा ',
    selectStatusAt: 'कृपया लग्नाच्या वेळची स्थिती निवडा ',

    enterAge: 'कृपया वय भरा ',
    selectGender: 'कृपया लिंग निवडा ',
    selectZone: 'कृपया झोन निवडा',
    selectWard: 'कृपया वार्ड निवडा',
    selectDate: 'कृपया तारीख निवडा',
    selectTitle: 'कृपया शीर्षक निवडा',
    enterFName: 'कृपया पहिले नाव भरा (इंग्लिश मध्ये)',
    enterMName: 'कृपया मधले  नाव भरा (इंग्लिश मध्ये)',
    enterLName: 'कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)',

    enterFNameMr: 'कृपया पहिले नाव भरा (मराठी मध्ये) ',
    enterMNameMr: 'कृपया मधले  नाव भरा (मराठी मध्ये)',
    enterLNameMr: 'कृपया शेवटचे नाव भरा (मराठी मध्ये)',

    enterFlat: 'कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ',
    enterApartment: 'कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा (इंग्लिश मध्ये)',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा (इंग्लिश मध्ये)',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश मध्ये)',
    state: 'कृपया  राज्य नाव भरा (इंग्लिश मध्ये)',

    enterFlatMr: 'कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)',
    enterApartmentMr: 'कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)',
    enterRoadNameMr: 'कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)',
    enterLandmarkMr: 'कृपया  महत्त्वाची खूण भरा  (मराठी मध्ये)',
    enterCityMr: 'कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)',
    stateMr: 'कृपया  राज्य नाव भरा  (मराठी मध्ये)',

    enterArea: 'कृपया क्षेत्राचे नाव भरा ',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा ',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा ',

    enterPinCode: 'कृपया पिनकोड भरा',
    enterPhoneNo: 'कृपया दूरध्वनी नं. भरा',
    enterMobileNo: 'कृपया मोबाईल नं. भरा',
    enterEmailAddress: 'कृपया इलेक्ट्रॉनिक संदेश भरा',
    enteraadhaarNo: 'कृपया आधार नं. भरा',
    enterpanNo: 'कृपया पॅन नं. भरा',
    enterRemarks: 'कृपया टिप्पणी. द्या',
    //mr
    selectWard: 'कृपया प्रभाग निवडा ',
    selectZone: 'कृपया झोन निवडा ',
    selectTitle: 'कृपया शीर्षक निवडा ',
    placeMarriage: 'कृपया  विवाहाचा ठिकाण भरा (इंग्लिश मध्ये)',
    placeMarriageMr: 'कृपया  विवाहाचा ठिकाण भरा  (मराठी मध्ये)',
    VfacilityType: 'सुविधा प्रकार निवडा',
    VfacilityName: 'सुविधेचे उपप्रकार निवडा',
    VpurposeOfBooking: 'बुकिंगचा उद्देश निवडा',
    Vcaddres: 'कृपया  सध्याचा पत्ता भरा   ',
  },
}
