export default {
  en: {
    applicantType: "Applicant / Complainee Type",
    applicantTypeMr: "Applicant / Complainee Type (मराठी)",
    complaintStausMr: "Complaint Status (मराठी)",
    complaintStaus: "Complaint Status",
    templateData: "Template Data",
    templateDataMr: "Template Data (मराठी)",
    remarkMr: "Remark (मराठी)",
    categoryType: "Category Type",
    categoryTypeMr: "Category Type (मराठी)",
    descriptionMr: "Description (मराठी)",
    complaintSubTypeMr: "Complaint Sub Type (मराठी)",
    mediaNameMr: "Media Name (मराठी)",
    mediaPrefixMr: "Prefix(मराठी)",

    module: "Marriage Registration",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    receipt: "Receipts",
    usertask: "User task",
    serviceName: "Service Name ",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    demo: "",
    //mr
    MrMasters: "Marriage Registration / Masters",
    marriageRegistrationMaritalStatus: "Marriage Registration / Masters / Marital Status",

    pay: "PAY",
    marriageRegistrationrelation: "Marriage Registration / Masters / relation",
    receiptModeDetails: "Receipt Mode Details",
    maritialSatus: "Marital Status",
    relation: "Relation",

    AptBook: "Appointment Slot Booking",
    serviceChargeTypeName: "Service Charge Type Name",

    // field label
    srNo: "Sr. No",
    actions: "Actions",
    statusDetails: "Status Details",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",

    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",
    results: "Results",
    searchArea: "Search Area",

    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    //marathi details
    gFNameMr: "",
    gMNameMr: "",
    gLNameMr: "",
    ApplicatCheck1: "If the Applicant is Groom",
    ApplicatCheck2: "If the Applicant is Bride",
    OwnerChkeck: "If the Applicant is Owner",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //mr
    Tnc: "accept term & Condition",
    // instrustion
    onlyMHR:
      " Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.",
    docNote:
      "Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.",
    //table
    newMRtable: "NEW MARRIAGE REGISTRATION ",
    boardtitle: "  Marriage Board Registration ",
    zone: "Zone",
    ward: "Ward",
    Addrees: "Applicant Address :",
    CrrtAdree: "Current Address :",
    parmtAdree: "Permanent Address :",
    personalDetails: "Personal Information :",
    Adress: "Address  :",
    BriNBM: "  (  Name are before marriage)",
    AppliToGroom: "If the Applicant is Groom ",
    AppliToBride: "If the Applicant is Bride",
    marrigeDetails: "  Marriage Details :",
    marrigeDate: "Marriage Date",
    //aprove
    GPhoto: "Groom Photo  ",
    Bphoto: "Bride Photo  ",
    witnessphto1: "Witness 1 Photo  ",
    witnessphto2: "Witness 2 Photo  ",
    witnessphto3: "Witness 3 Photo  ",
    Gthumb: "Groom Thumb  ",
    Bthumb: "Bride Thumb  ",
    witnessthumb1: "Witness 1 Thumb  ",
    witnessthumb2: "Witness 2 Thumb  ",
    witnessthumb3: "Witness 3 Thumb  ",

    //title
    ApplicatDetails: "APPLICANT DETAILS",
    ApplicatName: "Applicant Name",
    groomDetail: "GROOM DETAILS",
    groomParaentDetail: "Groom Parents Details ",
    brideDetails: "BRIDE DETAILS",
    brideParaentDetail: "Bride Parents Details",
    priestDetails: "PRIEST DETAILS",
    witness: "Witness",
    witnessAdd: "Witness",
    witnessDetails: "WITNESS DETAILS",
    documentsUpload: "DOCUMENT UPLOAD",
    boardDetail: "Board Details :",
    otherDetail: "OTHER DETAILS",
    titleInmarathi: "Title In Marathi",
    titleInenglish: "Title In english",

    // viceversa
    titleV: "शीर्षक",
    firstNameV: "प्रथम नावं  ",
    middleNameV: "मधले नावं  ",
    lastNameV: "आडनाव  ",

    //Groom
    // title: 'Title  ',
    // firstName: 'First Name  ',
    // middleName: 'Middle Name  ',
    // lastName: 'Last Name  ',
    title: "Title ",
    title1: "Title ",
    firstName: "First Name (In English) ",
    middleName: "Middle Name (In English) ",
    lastName: "Last Name (In English) ",
    titlemr: "शीर्षक ",
    firstNamemr: "First Name (In Marathi) ",
    middleNamemr: "Middle Name (In Marathi) ",
    lastNamemr: "Last Name (In Marathi) ",

    BirthDate: "Birth Date   ",
    Gender: "Gender",
    AadharNo: "Aadhar No",
    Age: "Age (at the time of marriage)",
    mobileNo: "Mobile / Phone Number",
    phoneNo: "Phone Number",
    email: "Email",

    flatBuildingNo: "Flat/Building No (In English)  ",
    buildingName: "Apartment Name (In English) ",
    roadName: "Road Name (In English) ",
    Landmark: "Landmark (In English) ",
    villageName: "Village Name (In English) ",
    cityName: "City Name / Village Name (In English) ",

    flatBuildingNomr: "Flat/Building No (In Marathi) ",
    buildingNamemr: "Apartment Name (In Marathi) ",
    roadNamemr: "Road Name (In Marathi) ",
    Landmarkmr: "Landmark (In Marathi) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "City Name / Village Name (In Marathi) ",

    State: "State (In English) ",
    statemr: "State (In Marathi) ",
    pincode: "Pin Code",
    Religion1: "Religion by Birth",
    Religion2: " Religion by Adoption",
    StatusOfMarrige: " Status at time of marriage",
    AgeDocument: "Birth Proof Document",
    IdDocument: "Id Document",
    residentialDocument: "Residential Document",
    StatusOfDocument: "Status Of Document",

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: "Place of Marriage (in English)",
    placeofMarriage1: "Place of Marriage (in Marathi)",

    //witness
    address: "Address",
    wRelation: "Witness Relation",
    wDocument: "Witness Document",

    //Document

    DBProof: "Date of Birth Proof",
    ResProof: "Residence Proof",
    IdProof: "ID Proof",

    ResProofW1: "Residence Proof of first witness",
    ResProofW2: "Residence Proof of second witness",
    ResProofW3: "Residence Proof of third witness",
    marrigeRelatedDoc: "Marriage Related Document",
    invetaionCard: "Marriage Invitation card / affidavit ",
    marrigePhotoC: "Marriage Photograph (Couple) ",
    marDrf: "Draft an application on the 100 Rs Stamp paper",
    DivorcePaper: "Valid Divorce Paper (if applicable)",
    DeathC: "Death Certificate (if applicable)",
    certiByReligiousPlc: " Certificate issued by religious place i.e Temple, Mosque etc",
    docFormat: " (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)",
    enterDoc: "Document Name",
    TandC: "",
    //board
    applicantName: "Applicant Name :",
    boardNameT: "Marriage Board Name",
    boardName: "Marriage Board Name (In English)  ",
    boardNamemr: "Marriage Board Name (In Marathi)  ",
    remark: "Remarks",
    documentList: " Documents List",
    ValidtyofMBR: "  Validity Of MBR",
    documentsUploadF: "Documents Upload",

    //button
    back: "Back",
    next: "Next",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",
    submit: "Submit",
    apply: "Apply",
    addFile: "Upload File",

    //table filed
    srNo: "Sr. No",
    ApplicantName: "Applicant Name",
    hName: "Groom Name",
    wName: "Bride Name",
    actions: "Actions",

    //brudcrum
    newMarriageRegistration: "Marriage Registration / New Marriage Registration",
    BoardMarriageRegistration: "Marriage Registration / New Board Registration",

    //ReIssuance of Marriage Certificate

    onlyRIMC: "Re-Issuance of Marriage Certificate",
    mRegNo: "Marriage Reg No",
    marriageDate: "Marriage Date",
    marriageYear: "Marriage Year",
    brideName: "Bride Name",
    groomName: "Groom Name",
    regDate: "Registration Date",

    //Renewal of Marriage Board Registration
    onlyRMBR: "Renewal of Marriage Board Registration",
    mbrName: "Marriage Board Name",
    mbrDate: "Marriage Board Reg Date",
    mbrYear: "Marriage Board Reg Year",
    search: "Search",

    //Application Details

    onlyApplDetail: "Application Details",
    applFName: "Applicant First Name",
    applMName: "Applicant Middle Name",
    applLName: "Applicant Last Name",
    groomFName: "Groom First Name",
    groomMName: "Groom Middle Name",
    groomLName: "Groom Last Name",
    brideFName: "Bride First Name",
    brideMName: "Bride Middle Name",
    brideLName: "Bride Last Name",
    mDate: "Marriage Date",

    //ReIssuance of marriage Certificate
    newRMItable: "ReIssuance of Marriage Certificate",
    applFullName: "Applicant Full Name",
    applicationNo: "Application No",
    generateLoi: "Generate LOI",

    //Modification in Marriage Board Registration

    onlyMMBR: "Modification in Marriage Board Registration",
    applicationDate: "Application Date",
    registerationDate: "Registeration Date",
    registerationNo: "Registeration No",
    orgName: "Organisation Name",

    //Payment Collection
    bankName: "Bank Name",
    branchName: "Branch Name",
    ifsc: "IFSC Code",
    accountNumber: "Account Number ",
    pay: "Pay",
    exit: "Exit",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    state: "Please enter State (In English)",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    stateMr: "Please enter State (In Marathi)",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (in English)",
    placeMarriageMr: "Please enter Place of Marriage (in Marathi)",
    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",
    witnessAddressC: "Please enter an Address ",
    witnessRelation: "Please enter an Relation. ",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    //Modification in Marriage Certificate

    onlyMIMC: "Modification of Marriage Certificate",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab :",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark on application",
    APPROVE: "APPROVE",

    REASSIGN: "REASSIGN",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    module: "Legal Case Management System",
    formType: "masters",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",

    masterPath: "Legal Case / Master ",
    transactionPath: "Legal Case / Transaction ",

    courtPath: "Legal Case / Master /Court",
    advocatePath: "Legal Case / Master /Advocate",
    serviceHierachyPath: "Legal Case / Master / Service Hierachy",
    caseTypePath: "Legal Case/ Master / Case Type",
    caseSubTypePath: "Legal Case / Master / Case Sub Type",
    caseStagesPath: "Legal Case/ Master / Case Type",
    employeeAndUserCreationPath: "Legal Case / Master / Employee and User Creation",
    counterSchedulingPath: "Legal Case / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath: "Legal Case / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath: "Legal Case / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath: "Legal Case / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "Legal Case / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",

    //other labels
    complaintType: "Complaint Type",
    complaintSubType: "Complaint Sub Type",
    status: "Status *",
    mediaName: "Media Name *",
    mediaPrefix: "Prefix *",
    remark: "Remark",
    eventType: "Event Type",
    eventDate: "Event Date *",
    alertDateTime: "Alert Date & Time *",
    description: "Description",
    courtName: "Court Name *",
    address: "Address *",
    roadName: "Road Name *",
    landmark: "Landmark *",
    cityOrVillage: "City / Village *",
    pincode: "Pincode *",
    area: "Area *",
    name: "Name *",
    mobile: "Mobile No. *",
    phone: "Phone No. *",
    email: "E-mail *",
    aadharNo: "Aadhar No. *",
    panNo: "Pan No. *",
    advocateCreation: "Advocate Created Successfully",
    advocateDetails: "Advocate Details",
    bankDetails: "Bank Details",
    documentUpload: "Document Upload",
    title: "Title *",
    fname: "First Name *",
    mname: "Middle Name *",
    lname: "Last Name *",
    advocateCategory: "Advocate Category *",
    nameOfBarCouncil: "Name Of Bar Council *",
    remarks: "Remarks *",
    bankName: "Bank Name *",
    branchName: "Branch Name *",
    accountNo: "Account No. *",
    bankIFSC: "Bank IFSC code *",
    bankMICR: "Bank MICR code *",
    application: "Application:",
    aadharCard: "Aadhar Card:",
    panCard: "Pan Card:",
    barCouncilCertificate: "Bar Council Certificate:",
    bankPassbook: "Bank Passbook:",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    grievanceCategory: "Grievance Category",
    grievanceStatus: "Grievance Status",
    complaintTypeMr: "Subject/Complaint Type(मराठी)",
    MediaMaster: "Media Master",

    ///////////////////////////////// ADDED BY ANSARI ////////////////////////////////////
    grievanceId: "Grievance Id",
    grievanceRaiseDate: "Grievance Raise Date",
    departmentName: "Department Name",
    subDepartmentName: "Sub-Department Name",
    subject: "Subject",
    grievanceType: "Grievance Type",
    complaintStatusText: "Status",
    welcomeToTheDashboard: "Welcome To The Dashboard",
    resolvedGrievances: "Resolved Grievances",
    raiseGrievance: "Raise Grievance",
    myGrievance: "MY GRIEVANCES",
    closeModal: "Close Modal",
    grievancesBehalfOfMyDepartment: "Grievances Related To My Department",
    /////////////////////FOR RAISE GRIEVANCE////////////////////
    personalDetailss: "PERSONAL DETAILS",
    grievanceDetailss: "GRIEVANCE DETAILS",
    titles: "Title",
    firstNames: "First Name",
    middleNames: " Middle Name",
    surnames: "Surname",
    houseNumberEn: "House Number (In English)",
    houseNumberMr: "House Number (In Marathi)",
    roadNamesEn: "Road Names (In English)",
    roadNamesMr: "Road Names (In Marathi)",

    areasEn: "Area (In English)",
    areasMr: "Area (In Marathi)",

    lacationsEn: "Location (In English)",
    lacationsMr: "Location (In Marathi)",

    citysEn: "City (In English)",
    citysMr: "City (In Marathi)",

    pincodesEn: "Pincode (In English)",
    pincodesMr: "Pincode (In Marathi)",

    emailIds: "Email-Id",
    buildingNos: "Building No.",

    ////////////////////////// GRIEVANCE DETAILS///////////////////////
    grievanceDetails: "GRIEVANCE DETAILS",
    applicantTypes: "Applicant Type",
    mediaTypes: "Media Type",
    complaintTypes: "Complaint Type",
    complaintSubTypes: "Complaint-Sub Type",
    categories: "Categories",

    subjectEn: "Subject (In English)",
    subjectMr: "Subject (In Marathi)",

    complaintDescriptionEn: "Complaint Description (In English)",
    complaintDescriptionMr: "Complaint Description (In Marathi)",

    uploadGeotagImage: "UPLOAD GEOTAG IMAGE",
    addDocuments: "ADD DOCUMENTS",
    fileUpload: "FILE UPLOAD",
    cancel: "Cancel",
    uploads: "Upload",
    originalFileName: "File Name",
    fileType: "File Type",
    attachedDate: "Attached Date",
    actionns: "Actions",

    //////////////////////////////////////
    ForwadToDepartmentName: "Forward To Department Name",
    ////////////////////////// VIEW GRIEVANCE ///////////////////////
    viewGrievance: "VIEW GRIEVANCE",
    reply: "Reply",
    backToDashboard: "back To Dashboard",
    closeGrievance: "Close Grievance",
    reOpen: "Re-Open",
    downloadAcknowledgement: "Download Acknowledgement",
    forwardGrievance: "FORWARD GRIEVANCE",
    print: "Print",

    ////////////////////////// TRACK GRIEVANCE ///////////////////////

    trackGrievance: "TRACK GRIEVANCE",
    getResults: "Get Result",
    fullName: "Grievance Raised By",

    ////////////////////////// ..GRIEVANCE MASTERS.. ///////////////////////
    addUsersBasedOnDepartment: "USERS WISE LEVEL  MAPPING",
    user: "Users",
    level: "Level",
    userName: "User Name",
    depName: "Department Name",
    ////////////////////////////////////////////////
    ///////////////////////////////////////////////
    complaintName: "Complaint Name",
    complaintSubTypeName: "Complaint Sub Type Name",
    subDepName: "Sub Dept. Name",
    totalLevels: "Total Levels",
    defaultEscDurationDays: "Escalation Duration In Days",
    defaultEscDurationHours: "Escalation Duration In Hours",

    ///////////////////////
    totalLevelsAndDefaultDuration: "TOTAL LEVELS AND DURATION",
    levels: "Levels",
    levelWiseEscalationDuration: "LEVEL WISE ESCALATION DURATION",
    escDurationInDays: "Escalation Duration In Days",
    escDurationInHours: "Escalation Duration In Hours",
    days: "Days",
    hours: "Hours",
    ////////////////////////////////////////////////
    ///////////////////////////////////////////////
    DepartmentWiseGrievanceDetails: "DEPARTMENT WISE GRIEVANCE COUNT",
    EventWiseGrievanceDetails: "GRIEVANCE SUMMARY EVENT AND DEPARTMENT WISE DETAILS",
    ComplaintWiseGrievanceDetails: "SUBJECT WISE GRIEVANCE COUNT",
    MediaWiseGrievanceDetails: "MEDIA WISE GRIEVANCE REPORT",
    fromDate: "From Date",
    toDate: "To Date",
    details: "Details",
    count: "Count",
    complaintStatus: "Complaint Status",
    corporationName: "Corporation Name",
    eventName: "Event Name",
    totalCount: "Total Count",
    complaintSubject: "Complaint Subject",
    totalComplaintsCount: "Total Complaints Count",
    download: "Download",
    /////////////////////////////////////////////
    ReviewMeetingReport: "REVIEW MEETING REPORT (POINT_WISE)",
    openCount: "Open Count",
    closeCount: "Close Count",
    /////////////////////////////////////////////
    DeptAndCitizenWiseGrievanceDetails: "DEPARTMENT WISE GRIEVANCE DETAILS",
    citizenName: "Citizen Name",
    citizenAddress: "Citizen Address",
    citizenContact: "Citizen Contact",
    /////////////////////////////////////////////
    WardWiseGrievanceDetails: "GRIEVANCE BY WARD REPORT",
    wardss: "Ward Name",
    durations: "Duration",

    ////////////////////////////////////////////////
    areaSearch: "Search By Area Name",
  },

  mr: {
    applicantType: "अर्ज प्रकार / तक्रारदार प्रकार",
    applicantTypeMr: "अर्ज प्रकार / तक्रारदार प्रकार (मराठी)",
    complaintStausMr: "तक्रारीची स्थिती (मराठी)",
    complaintStaus: "तक्रारीची स्थिती",
    templateData: "टेम्पलेट डेटा",
    templateDataMr: "टेम्पलेट डेटा (मराठी)",
    remarkMr: "टिप्पणी (मराठी)",
    categoryType: "श्रेणी प्रकार",
    categoryTypeMr: "श्रेणी प्रकार (मराठी)",
    descriptionMr: "वर्णन (मराठी)",
    complaintSubTypeMr: "तक्रारीचा उप प्रकार (मराठी)",
    mediaNameMr: "मीडियाचे नाव (मराठी)",
    mediaPrefixMr: "मीडिया उपसर्ग (मराठी)",

    onlyeng: "फक्त इंग्लिश मध्ये",
    onlymarathi: "फक्त मराठी मध्ये",
    APPROVE: "मंजूर करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    newLabel: "नवीन माहिती",
    onlyMIMC: "विवाह प्रमाणपत्रात बदल",
    State: "स्टेट (इंग्लिश मध्ये) ",
    statemr: "स्टेट (मराठी मध्ये) ",
    UploadFile: "फाइल अपलोड करा",
    electrbill: "वीज बिल",
    OtherDocument: "इतर दस्तऐवज",
    rationcard: "रेशान कार्ड",
    adharcard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    boardorgphotocpy: "संस्था किंवा मंडळची दस्तऐवज",
    boardheadphoto: "मंडळाच्या प्रमुख व्यक्तीच छायाचित्र",
    document: "दस्तऐवज",
    Owneraddress: " मंडळच्या प्रमुख व्यक्तीचा पत्ता  :",
    OwnerDetails: "मंडळच्या प्रमुख व्यक्तीची माहिती",
    titleInmarathi: "शीर्षक मराठी मध्ये",
    titleInenglish: "शीर्षक इंग्लिश मध्ये",
    OwnerChkeck: "जर अर्जादारच विवाह मंडळाचा प्रमुख असेल",
    apply: "जतन करा",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    EnterDocName: "कृपया दस्तऐवजाच नाव भरा ",
    witnessAddressC: "कृपया पत्ता भरा  ",
    witnessRelation: "कृपया साक्षीदारशी नाते भरा  ",

    birthProf: "कृपया जन्म तारीख पुरावा निवडा ",
    ResideProof: "कृपया रहिवासाचा पुरावा निवडा ",
    IdentyProof: "कृपया ओळखपत्र पुरावा निवडा ",
    // //Remarks
    selectReligionby: "कृपया जन्माने धर्म निवडा ",
    selectAdoptionby: "कृपया दत्तक घेऊन धर्म निवडा ",
    selectStatusAt: "कृपया लग्नाच्या वेळची स्थिती निवडा ",

    enterAge: "कृपया वय भरा ",
    selectGender: "कृपया लिंग निवडा ",
    selectZone: "कृपया झोन निवडा",
    selectWard: "कृपया वार्ड निवडा",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश मध्ये)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश मध्ये)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)",

    enterFNameMr: "कृपया पहिले नाव भरा (मराठी मध्ये) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी मध्ये)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी मध्ये)",

    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)",
    enterRoadName: "कृपया रस्त्याचे नाव भरा (इंग्लिश मध्ये)",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा (इंग्लिश मध्ये)",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश मध्ये)",
    state: "कृपया  राज्य नाव भरा (इंग्लिश मध्ये)",

    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)",
    enterLandmarkMr: "कृपया  महत्त्वाची खूण भरा  (मराठी मध्ये)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)",
    stateMr: "कृपया  राज्य नाव भरा  (मराठी मध्ये)",

    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",

    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    //mr
    selectWard: "कृपया प्रभाग निवडा ",
    selectZone: "कृपया झोन निवडा ",
    selectTitle: "कृपया शीर्षक निवडा ",
    placeMarriage: "कृपया  विवाहाचा ठिकाण भरा (इंग्लिश मध्ये)",
    placeMarriageMr: "कृपया  विवाहाचा ठिकाण भरा  (मराठी मध्ये)",

    pay: "पैसे भरा",
    titlemr: "शीर्षक ",
    title1: "Title ",
    newMRtable: "नवीन विवाह नोंदणी",
    module: "विवाह नोंदणी",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    masters: "मास्टर्स",
    transactions: "ट्रैन्ज़ैक्शन",
    reports: "अहवाल",
    receipt: "पावती",
    usertask: "User task",
    serviceChargeTypeName: "सेवा शुल्काचा प्रकार",

    chargeName: "शुल्काचा प्रकार",
    masters: "मास्टर्स",
    masterPath: "तक्रार निरीक्षण / मास्टर्स",

    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    //mr
    MrMasters: "विवाह नोंदणी/ मास्टर ",
    marriageRegistrationMaritalStatus: "विवाह नोंदणी/ मास्टर / वैवाहिक स्थिती",

    marriageRegistrationrelation: "विवाह नोंदणी/ मास्टर / नाते",

    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",

    documentUpload: "दस्तऐवज अपलोड",
    addFile: "फाइल जोडा",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    verify: "सत्यापित",
    reject: "नाकारा",
    noFileFound: "कोणतीही फाइल आढळली नाही",
    verified: "तपासून झाले",

    upload: "अपलोड करा",
    next: "पुढे",
    preview: "पूर्वावलोकन",

    attachFile: "फाईल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    serviceName: "सेवेचे नाव ",
    //titles

    calendarScheduling: " दिनदर्शिका शेड्युलिंग",
    maritialSatus: "वैवाहिक स्थिती",
    relation: "नाते",
    //field label
    srNo: "अनु क्रमांक",
    actions: "क्रिया ",
    statusDetails: "स्थिती तपशील",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",
    results: "परिणाम",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ApplicatCheck1: "जर अर्जदार वर असेल तर",
    ApplicatCheck2: "जर अर्जदार वधु असेल तर",

    transactions: " ट्रैन्ज़ैक्शन",
    transactionPath: "कायदेशीर प्रकरण/  ट्रैन्ज़ैक्शन ",

    //mr
    // instrustion
    onlyMHR:
      "महाराष्ट्रातील विवाहाचे रजिस्ट्रेशन केले जाते आणि वधू किंवा वर यापैकी एक जण पिंपरी चिंचवड महानगर पालिकेच्या हद्दी मधील रहिवासी असावा.",
    docNote:
      "आयडी पुरावा, रहिवासी पुरावा, वयाचा पुरावा वेगळा असावा, (लग्नाच्या वेळी स्थिती असल्यास मागील स्टेटस प्रूफमध्ये मूल्य असते विधवा/विधुर किंवा घटस्फोटीत आहे) आधारकार्ड पुरावा जोडल्यास व नागरिक भाड्याने राहत असलेस नोंदणीकृत करारनामा आवश्यक आहे.",

    //aprove
    GPhoto: "वरचा फोटो  ",
    Bphoto: "वधुचा फोटो  ",
    witnessphto1: "साक्षीदारचा १ फोटो  ",
    witnessphto2: "साक्षीदारचा २ फोटो  ",
    witnessphto3: "साक्षीदारचा ३ फोटो  ",
    Gthumb: "वरचा अंगठाचा ठसा  ",
    Bthumb: "वधुचा अंगठाचा ठसा  ",
    witnessthumb1: "साक्षीदारचा १ अंगठाचा ठसा  ",
    witnessthumb2: "साक्षीदारचा २ अंगठाचा ठसा  ",
    witnessthumb3: "साक्षीदारचा ३ अंगठाचा ठसा  ",

    //table
    Tnc: "नियम व अटी",
    newMRtable: "नवीन विवाह नोंदणी",
    boardtitle: "विवाह मंडळाची माहिती",
    zone: "झोन",
    ward: "वार्ड",
    Addrees: "अर्जदाराचा रहिवासाचा पत्ता :",

    CrrtAdree: "सध्याचा रहिवासाचा पत्ता :",
    parmtAdree: "कायमचा रहिवासाचा पत्ता :",
    personalDetails: "वैयक्तिक माहिती :",
    Adress: "पत्ता :",
    BriNBM: "  (  लग्नाआधीचे नाव)",
    AppliToGroom: "",
    AppliToBride: "",
    marrigeDetails: "विवाहाची माहिती :",
    marrigeDate: "विवाहाची दिनांक",

    //title
    ApplicatDetails: "अर्जदाराची माहिती",
    ApplicatName: "अर्जदाराच नाव",
    groomDetail: "वराची माहिती",
    groomParaentDetail: "वराच्या पालकांची माहिती",
    brideDetails: "वधुची माहिती",
    brideParaentDetail: "वधुच्या पालकांची माहिती",
    priestDetails: "पुजारी माहिती",
    witness: "साक्षीदार",
    witnessDetails: "साक्षीदार माहिती",
    documentsUpload: "दस्तऐवज अपलोड",
    boardDetail: "विवाह मंडळाची माहिती :",
    otherDetail: "इतर तपशील",

    // viceversa
    titleV: "Title  ",
    firstNameV: "First Name  ",
    middleNameV: "Middle Name  ",
    lastNameV: "Last Name  ",

    //groom
    title: "शीर्षक",
    firstName: "प्रथम नाव (इंग्लिश मध्ये) ",
    middleName: "मधले नाव (इंग्लिश मध्ये) ",
    lastName: "आडनाव (इंग्लिश मध्ये) ",
    firstNamemr: "प्रथम नाव (मराठी मध्ये) ",
    middleNamemr: "मधले नाव (मराठी मध्ये) ",
    lastNamemr: "आडनाव (मराठी मध्ये) ",
    BirthDate: "जन्म दिनांक  ",
    Gender: "लिंग",
    AadharNo: "आधार नंबर",
    Age: "वय (लग्नाच्या वेळीचे वय)",
    mobileNo: "दूरध्वनी क्रमांक",
    phoneNo: "फोन नंबर",
    email: "ई-मेल",

    flatBuildingNo: "फ्लॅट नंबर (इंग्लिश मध्ये) ",
    buildingName: "अपार्टमेंट नाव (इंग्लिश मध्ये) ",
    roadName: "गल्लीचे नाव (इंग्लिश मध्ये) ",
    Landmark: "जमीन चिन्ह (इंग्लिश मध्ये) ",
    villageName: "Village Name (In English) ",
    cityName: "शहराचे नाव (इंग्लिश मध्ये) ",

    flatBuildingNomr: "फ्लॅट नंबर (मराठी मध्ये) ",
    buildingNamemr: "अपार्टमेंट नाव (मराठी मध्ये) ",
    roadNamemr: "गल्लीचे नाव (मराठी मध्ये) ",
    Landmarkmr: "जमीन चिन्ह (मराठी मध्ये) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "शहराचे नाव (मराठी मध्ये) ",

    // flatBuildingNo: 'फ्लॅट नंबर',
    // buildingName: 'अपार्टमेंट नाव',
    // roadName: 'गल्लीचे नाव',
    // Landmark: 'जमीन चिन्ह',
    // villageName: 'गावाचे नाव ',
    // cityName: 'शहराचे नाव',
    state: "राज्य (इंग्लिश मध्ये) ",
    statemr: "राज्य (मराठी मध्ये)  ",

    pincode: "पिन कोड",
    Religion1: "जन्माने धर्म",
    Religion2: "दत्तक घेऊन धर्म",
    StatusOfMarrige: "लग्नाच्या वेळची स्थिती",
    AgeDocument: "वयाचे कागदपत्र",
    IdDocument: "ओळख कागदपत्र ",
    residentialDocument: "रहिवाशी कागदपत्र",
    StatusOfDocument: "कागदपत्र स्थिती ",

    //groomFather
    firstNameF: "वडिलांचं प्रथम नाव  ",
    middleNameF: "वडिलांचं मधले नाव  ",
    lastNameF: "वडिलांचं आडनाव  ",
    AgeF: "वडिलांच वय",
    mobileNoF: "वडिलांचं दूरध्वनी क्रमांक",
    AadharNoF: "वडिलांचं आधार नंबर",

    //groomMother
    firstNameM: "आईचे प्रथम नाव  ",
    middleNameM: "आईचे मधले नाव  ",
    lastNameM: "आईचे आडनाव  ",
    AgeM: "आईचे वय",
    mobileNoM: "आईचे दूरध्वनी क्रमांक",
    AadharNoM: "आईचे आधार नंबर",

    //prist
    placeofMarriage: "लग्नाचे ठिकाण (इंग्लिश मध्ये)",
    placeofMarriage1: "लग्नाचे ठिकाण (मराठी मध्ये) ",

    //witness
    address: "पत्ता",
    wRelation: "साक्षीदारशी नाते",
    wDocument: "साक्षीदाराचे कागदपत्र",
    witnessAdd: "साक्षीदार जोडा",

    //Document

    DBProof: "जन्म तारीख पुरावा",
    ResProof: "रहिवासाचा पुरावा",
    IdProof: "ओळखपत्र पुरावा",
    ResProofW1: "प्रथम साक्षीदार रहिवासाचा पुरावा",
    ResProofW2: "द्वितीय साक्षीदार रहिवासाचा पुरावा",
    ResProofW3: "तृतिय साक्षीदार रहिवासाचा पुरावा",
    marrigeRelatedDoc: "विवाह संबंधित दस्तऐवज",
    invetaionCard: "विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र ",
    marrigePhotoC: "विवाह छायाचित्र (जोडीचे) ",
    marDrf: "१०० रुपयांच्या स्टॅम्प पेपरवर अर्जाचा मसुदा तयार करा",
    DivorcePaper: "वैध घटस्फोट कागद (लागू असल्यास)",
    DeathC: "मृत्यू प्रमाणपत्र (लागू असल्यास)",
    certiByReligiousPlc: " मंदिर, मशीद इ. धार्मिक स्थळाद्वारे जारी केलेले प्रमाणपत्र",
    docFormat: " (फक्त jpg.jpeg.png.bmp.pdf फाइल अपलोड करण्याची परवानगी आहे. फोटो आकार कमाल 100 kb)",
    enterDoc: "दस्तऐवजाच नाव ",

    //board
    applicantName: "अर्जादारच नाव :",
    boardNameT: "विवाह मंडळचे नाव",
    boardName: "विवाह मंडळचे नाव (इंग्लिश मध्ये) ",
    boardNamemr: "विवाह मंडळचे नाव (मराठी मध्ये) ",

    remark: "शेरा",
    documentList: "दस्तऐवज यादी",
    ValidtyofMBR: "विवाह मंडळाची अंतिम वैधता",
    documentsUploadF: "दस्तऐवज अपलोड",
    TandC: "",
    //button
    back: "मागे",
    next: "पुढे",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    submit: "प्रस्तुत करणे",
    addFile: "फाइल जोडा",

    //table filed
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    hName: "वरचे नाव",
    wName: "वधूचे नाव",
    ApplicantName: "अर्जादारच नाव",

    //brudcrum
    newMarriageRegistration: "विवाह नोंदणी / नवीन विवाह नोंदणी ",
    BoardMarriageRegistration: "विवाह मंडळ नोंदणी / नवीन विवाह मंडळ नोंदणी ",

    //module: 'शहर नियोजन',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    // master: 'मास्टर्स',
    // transactions: 'व्यवहार',
    // report: 'अहवाल',
    // masterPath: 'शहर नियोजन/ मास्टर ',
    // transactionPath: 'शहर नियोजन/ व्यवहार ',
    // reportPath: 'शहर नियोजन/ अहवाल ',

    // //breadcrum
    // landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
    // tdrZoneGatAndVillageMappingPath:
    //   'शहर नियोजन/ मास्टर / टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntryPath:
    //   'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignationPath:
    //   'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',

    // //titles
    // landReservation: 'जमीन आरक्षण',
    // tdrZoneGatAndVillageMapping: 'टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',

    // //other labels
    // landReservationID: 'जमीन आरक्षण क्र',
    // reservationName: 'आरक्षणाचे नाव',
    // reservationNameEng: 'आरक्षणाचे नाव इंग्रजीत',
    // reservationNameMr: 'आरक्षणाचे नाव मराठीत',
    // surveyNumber: 'सर्वेक्षण क्र',
    // landReservationLegend: 'जमीन आरक्षण आख्यायिका',
    // reservationAreaInHector: 'हेक्टर मध्ये आरक्षण क्षेत्र',
    // landInPossession: 'ताब्यात जमीन',
    // remark: 'टिप्पणी',
    // villageName: 'गावाचे नाव',
    // gatName: 'गटाचे नाव',
    // zoneName: 'झोनचे नाव',
    // landReservationName: 'जमीन आरक्षण नाव',
    // citySurveyNo: 'शहर सर्वेक्षण क्र',
    // reservationNo: 'आरक्षण क्र',
    // landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
    // landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
    // ddtp: 'डी.डी.टी.पी',
    // deAndTp: 'उपअभियंता /नगर नियोजक',
    // atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',

    // attachFile: 'फाईल जोडा',
    // srNo: 'अनु क्र',
    // actions: 'क्रिया ',

    // //buttons
    // add: 'जोडा',
    // save: 'जतन करा',
    // update: 'अद्यायावत करा',
    // clear: 'रिक्त',
    // exit: 'बाहेर पडा',
    // back: 'मागे',
    // saveAndNext: 'जतन करा आणि पुढे',
    // finish: 'समाप्त',

    //ReIssuance of Marriage Certificate

    onlyRIMC: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    mRegNo: "विवाह रजि क्र",
    marriageDate: "लग्नाची तारीख",
    marriageYear: "लग्नाचे वर्ष",
    brideName: "वधूचे नाव",
    groomName: "वराचे नाव",
    regDate: "नोंदणी दिनांक",

    //Renewal of Marriage Board Registration
    onlyRMBR: "विवाह मंडळ नोंदणीचे नूतनीकरण",
    mbrName: "विवाह मंडळ नोंदणी नाव",
    mbrDate: "विवाह मंडळ नोंदणी तारीख",
    mbrYear: "विवाह मंडळ नोंदणी वर्ष",
    search: "शोधा",

    //Application Details

    onlyApplDetail: "अर्ज तपशील",
    applFName: "अर्जदाराचे पहिले नाव",
    applMName: "अर्जदाराचे मधले नाव",
    applLName: "अर्जदार आडनाव",
    groomFName: "वराचे पहिले नाव",
    groomMName: "वराचे मधले नाव",
    groomLName: "वराचे आडनाव",
    brideFName: "वधूचे पहिले नाव",
    brideMName: "वधू मधले नाव",
    brideLName: "वधू आडनाव",
    mDate: "लग्नाची तारीख",

    //ReIssuance of marriage Certificate
    newRMItable: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    applFullName: "अर्जदाराचे पूर्ण नाव",
    applicationNo: "अर्ज क्र",
    applicationDate: "अर्ज तारीख",

    module: "कायदेशीर प्रकरण व्यवस्थापन प्रणाली",
    formType: "masters",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",

    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    courtPath: "कायदेशीर प्रकरण/ मास्टर /न्यायालय",
    advocatePath: "कायदेशीर प्रकरण/ मास्टर /वकील",
    serviceHierachyPath: "कायदेशीर प्रकरण/ मास्टर / सेवा पदानुक्रम",
    caseTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा प्रकार",
    caseSubTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा उप-प्रकार",
    caseStagesPath: "कायदेशीर प्रकरण/ मास्टर / प्रकरण-टप्पे",
    employeeAndUserCreationPath: "कायदेशीर प्रकरण/ मास्टर / कर्मचारी आणि वापरकर्ता निर्मिती",
    counterSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplatesPath:
      "कायदेशीर प्रकरण/ मास्टर / संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRightsPath: "कायदेशीर प्रकरण/ मास्टर / वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPasswordPath:
      "कायदेशीर प्रकरण/ मास्टर / बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / दिनदर्शिका शेड्युलिंग",

    //titles
    court: "न्यायालय",
    advocate: "वकील",
    serviceHierachy: "सेवा पदानुक्रम",
    caseType: "प्रकरणाचा प्रकार",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    caseStages: "प्रकरण-टप्पे",
    employeeAndUserCreation: "कर्मचारी आणि वापरकर्ता निर्मिती",
    counterScheduling: " काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplates: " संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRights: " वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPassword: "बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarScheduling: " दिनदर्शिका शेड्युलिंग",

    //other labels
    complaintType: "तक्रारीचा प्रकार",
    complaintSubType: "तक्रारीचा उप प्रकार",
    status: "स्थिती *",
    mediaName: "मीडियाचे नाव *",
    mediaPrefix: "मीडिया उपसर्ग *",
    remark: "टिप्पणी",
    eventType: "कार्यक्रमाचा प्रकार *",
    eventDate: "कार्यक्रमाची तारीख *",
    alertDateTime: "सूचना तारीख आणि वेळ *",
    description: "वर्णन",
    courtName: "न्यायालयाचे नाव",
    address: "पत्ता",
    roadName: "रस्त्याचे नाव",
    landmark: "महत्त्वाची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक *",
    fname: "पहिले नाव *",
    mname: "मधले  नाव *",
    lname: "शेवटचे नाव *",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    grievanceCategory: "शिकायत श्रेणी",
    grievanceStatus: "तक्रारीची स्थिती",
    complaintTypeMr: "विषय/तक्रारीचा प्रकार (मराठी)",
    MediaMaster: "मीडिया मास्टर",

    ////////////////////////////////// ADDED BY ANSARI //////////////////////////////////////

    grievanceId: "तक्रार आयडी",
    grievanceRaiseDate: "तक्रार वाढवण्याची तारीख",
    departmentName: "विभागाचे नाव",
    subDepartmentName: "उप-विभागाचे नाव",
    subject: "विषय",
    grievanceType: "तक्रारीचा प्रकार",
    complaintStatusText: "स्थिती",
    ///////////////////////////////////////////
    welcomeToTheDashboard: "डॅशबोर्डवर आपले स्वागत आहे ",
    resolvedGrievances: "तक्रारींचे निराकरण केले",
    raiseGrievance: "तक्रार करा",
    myGrievance: "माझ्या तक्रारी",
    closeModal: "मोडल बंद करा",
    grievancesBehalfOfMyDepartment: "माझ्या विभागाच्या तक्रारी",
    ////////////////////////////////////////////
    personalDetailss: "वैयक्तिक माहिती",
    grievanceDetailss: "तक्रारीचे तपशील",
    titles: "शीर्षक",
    firstNames: "पहिले नाव",
    middleNames: "मधले नाव",
    surnames: "आडनाव",
    houseNumberEn: "घर क्रमांक (इंग्लिश मध्ये)",
    houseNumberMr: "घर क्रमांक (मराठी मध्ये)",

    roadNamesEn: "रस्त्याचे नाव (इंग्लिश मध्ये)",
    roadNamesMr: "रस्त्याचे नाव (मराठी मध्ये)",

    areasEn: "क्षेत्र (इंग्लिश मध्ये)",
    areasMr: "क्षेत्र (मराठी मध्ये)",
    lacations: "लॅकेशन",
    lacationsEn: "लॅकेशन (इंग्लिश मध्ये)",
    lacationsMr: "लॅकेशन (मराठी मध्ये)",
    citys: "शहर",

    citysEn: "शहर (इंग्लिश मध्ये)",
    citysMr: "शहर (मराठी मध्ये)",

    pincodesEn: "पिन कोड (इंग्लिश मध्ये)",
    pincodesMr: "पिन कोड (मराठी मध्ये)",

    emailIds: "ई - मेल आयडी",
    buildingNos: "इमारत क्रमांक",

    ////////////////////////// GRIEVANCE DETAILS///////////////////////
    grievanceDetails: "तक्रार तपशील",
    applicantTypes: "अर्जदाराचा प्रकार",
    mediaTypes: "मीडिया प्रकार",
    complaintTypes: "तक्रारीचे प्रकार",
    complaintSubTypes: "तक्रार - उपप्रकार",
    categories: "श्रेणी",

    subjectEn: "विषय (इंग्लिश मध्ये)",
    subjectMr: "विषय (मराठी मध्ये)",

    complaintDescriptionEn: "तक्रारीचे वर्णन (इंग्लिश मध्ये)",
    complaintDescriptionMr: "तक्रारीचे वर्णन (मराठी मध्ये)",

    uploadGeotagImage: "जिओटॅग प्रतिमा अपलोड करा",
    addDocuments: "दस्तऐवज जोडा",
    fileUpload: "फाइल अपलोड",
    cancel: "रद्द करा",
    uploads: "अपलोड करा",
    originalFileName: "फाईलचे नाव",
    fileType: "दस्तावेजाचा प्रकार",
    attachedDate: "संलग्न तारीख",
    actionns: "क्रिया",

    /////////////////////////////////////////////
    ForwadToDepartmentName: "विभागाच्या नाव",

    ////////////////////////// VIEW GRIEVANCE ///////////////////////
    viewGrievance: "तक्रार पहा",
    reply: "उत्तर द्या",
    backToDashboard: "डॅशबोर्डवर परत",
    closeGrievance: "तक्रार बंद करा",
    reOpen: "पुन्हा उघडा",
    downloadAcknowledgement: "पावती डाउनलोड करा",
    forwardGrievance: "तक्रार फॉरवर्ड करा",
    print: "छापणे",

    ////////////////////////// TRACK GRIEVANCE ///////////////////////

    trackGrievance: "तक्रारीचा मागोवा घ्या",
    getResults: "निकाल मिळवा",
    fullName: "यांनी मांडलेली तक्रार",

    ////////////////////////// ..GRIEVANCE MASTERS.. ///////////////////////
    addUsersBasedOnDepartment: "वापरकर्ते वार लेव्हल मॅपिंग",
    user: "वापरकर्ता",
    level: "पातळी",
    userName: "वापरकर्त्याचे नाव",
    depName: "विभागाचे नाव",
    ///////////////////////////////////////////////
    complaintName: "तक्रारीचे नाव",
    complaintSubTypeName: "तक्रार उपप्रकार नाव",
    subDepName: "उपविभागाचे नाव",
    totalLevels: "एकूण स्तर",
    defaultEscDurationDays: "एस्केलेशन कालावधी दिवसांमध्ये",
    defaultEscDurationHours: "एस्केलेशन कालावधी तासांमध्ये",

    ///////////////////////
    totalLevelsAndDefaultDuration: "एकूण स्तर आणि कालावधी",
    levels: "स्तर",
    levelWiseEscalationDuration: "पातळीनुसार वाढीचा कालावधी",
    escDurationInDays: "दिवसांमध्ये वाढीचा कालावधी",
    escDurationInHours: "तासांमध्ये वाढीचा कालावधी",
    days: "दिवस",
    hours: "तास",
    ////////////////////////////////////////////////

    ///////////////////////// GM REPORTS ADDED BY ANWAR ANSARI //////////////////////

    DepartmentWiseGrievanceDetails: "विभागनिहाय तक्रार तपशील",
    EventWiseGrievanceDetails: "घटनावार तक्रार तपशील",
    ComplaintWiseGrievanceDetails: "तक्रारवार तक्रार तपशील",
    MediaWiseGrievanceDetails: "मीडियानुसार तक्रार तपशील",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपयंत",
    details: "तपशील",
    count: "मोजणे",
    complaintStatus: "तक्रारीची स्थिती",
    corporationName: "कॉर्पोरेशनचे नाव",
    eventName: "कार्यक्रमाचे नाव",
    totalCount: "एकूण संख्या",
    event: "कार्यक्रम",
    complaintSubject: "तक्रारीचा विषय",
    totalComplaintsCount: "एकूण तक्रारींची संख्या",
    download: "डाउनलोड करा",
    /////////////////////////////////////////////
    ReviewMeetingReport: "सभेच्या अहवालाचे पुनरावलोकन करा(पॉइंट वाईज)",
    openCount: "संख्या उघडा",
    closeCount: "बंद संख्या",
    /////////////////////////////////////////////
    DeptAndCitizenWiseGrievanceDetails: "विभाग आणि नागरिकांनुसार तक्रारीचे तपशील",
    citizenName: "नागरिकाचे नाव",
    citizenAddress: "नागरिकांचा पत्ता",
    citizenContact: "नागरिक संपर्क",
    ////////////////////////////////////////////////
    WardWiseGrievanceDetails: "प्रभागनिहाय तक्रारीचा तपशील",
    wardss: "प्रभागाचे नाव",
    durations: "कालावधी",

    /////////////////////////////////////////////////
    areaSearch: "क्षेत्राच्या नावाने शोधा",
    searchArea: "क्षेत्र शोधा",
  },
};
