/* eslint-disable import/no-anonymous-default-export */
export default {
  en: {
    serviceChargeTypeName: "Service Charge Type Name",
    or: "OR",
    totalCharges: "Total Charges",
    loiPreview: "Loi Preview",
    chargeName: "Charge Name",
    amount: "Amount",
    iCard: "Identity Card",
    view: "View",
    ddNo: "Demand Draft Number",
    viewCertificate: "View Certificate",
    ddDate: "Demand Draft Date",
    AptBook: "Appointment Slot Booking",
    streetVendorQuestion: "Street Vendor Question",
    applicantName: "Applicant Name",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    loiRecord: "Loi Record",
    loiGeneration: "  LOI Generation",
    loiPrint: "  LOI Print",
    loiCollection: "LOI Collection",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    type: "commonLabels",
    search: "Search",
    loiNO: "LOI NO.",
    loiDetails: "LOI Details",
    and: "And",
    loiDate: "LOI Date",
    applicationNo: "Application NO.",
    loiCollection: "LOI Collection",
    rate: "Rate",
    amount: "Amount",
    total: "Total",
    totalInWords: "Total Charges in Words",
    licenseType: "License Type",
    years: "Years",
    months: "Months",

    durationOfLicenseValidity: " Duration of License Validity (in year)",
    checkFormLicenseValidityForm: " Check for License Validity Form",
    hawkerType: "Street Vendor",
    hawkerType1: "Street Vendor Type",
    hawkerTypeMr: "Street Vendor (in English) ",
    serviceCharge: "Service Charges",
    licenseValidity: "License Validity (in Years)",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    dateOfIssuance: "Date of Issuance",
    calendarYear: "Calendar Year",
    financialYear: "Financial Year",
    generateLoi: "Generate LOI",
    previewLoi: "Preview LOI",
    verifyLoi: "Verify LOI",
    HMS: "Street Vendor Management System",
    streetVendorManagmentSystem: "Street Vendor Management System",
    siteVisitPhotoUpload: "Upload Photos of a Site Visit",
    siteVisitPhoto: "Photos of a Site Visit",
    streetVendorInformation: "Street Vendor Information",
    businessHawkinglocation: "who is operating the business at the hawking location ?",
    remark: "Remark",
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    roadWithBusinessLocation: "Road Width at Business Location? (in feet)",
    streetVendorPhoto: "Photo",
    inFeet: "in feet",

    streetVendorThumb1: "Biometric Impression of Thumb 1",
    streetVendorThumb2: "Biometric Impression of Thumb 2",
    transactions: "Transactions",
    report: "Reports",
    masterPath: "Hawker Management System / masters",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",
    inspectionSellingGoods:
      "Did the inspection discover that the applicant is selling goods at the specified location?",
    HMS: "Street Vendor Management System",
    businessTrafficCongestion: "Does the business currently cause traffic congestion ?",
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transactions: "Transactions",
    report: "Reports",
    siteVisit: "Site Visit",
    masterPath: "Hawker Management System / masters",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",
    master: "Masters",
    hawkerType: "Street Vendor Type",
    masterPath: "SkySign/ Master",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    religionPath: "Street Vendor Management System / masters / Religion",
    hawkerTypePath: "Street Vendor Management System / masters / Street Vendor Type",
    businessTypeMasterPath: "Street Vendor Management System / masters / Business Type Master",
    businessSubTypePath: "Street Vendor Management System / masters / Business Sub Type",
    titlePath: "Street Vendor Management System / masters / Title",
    itemMasterPath: "Street Vendor Management System / masters / Item Master",
    itemCategoryMasterPath: "Street Vendor Management System / masters / Item Category Master",
    castCategoryPath: "Street Vendor Management System / masters / Caste Category",
    castMasterPath: "Street Vendor Management System / masters / Cast Master",
    hawkingZonePath: "Street Vendor Management System / masters / Hawking Zone",
    subCastMasterPath: "Street Vendor Management System / masters / Sub Caste Master",
    licenseValidityPath: "Street Vendor Management System / masters / License Validity",
    penaltyPath: "Street Vendor Management System / masters / Penalty",
    bankMasterPath: "Street Vendor Management System / masters /Bank Master",
    hawkingZoneWiseFacilitiesPath:
      "Street Vendor Management System / masters / StreetVendor Zone Wise Facilities",
    taxTypeMasterPath: "Street Vendor Management System / masters / Tax Type Master",
    taxNameMasterPath: "Street Vendor Management System / masters / Tax Name Master",
    serviceTaxCollectionCyclePath: "Street Vendor Management System / masters / Service Tax Collection Cycle",
    taxRateChartMasterPath: "Street Vendor Management System / masters / Tax Rate Chart Master",
    noHawkingZonePath: "Street Vendor Management System / masters / No StreetVendor Zone",
    hawkerMasterPath: "Street Vendor Management System / masters / Street Vendor Master",
    ward: "Ward",
    zone: "Zone",
    religion: "Religion",
    hawkerType: "Street Vendor Type",
    businessTypeMaster: "Business Type Master",
    businessSubType: "Business Sub Type",
    title: "Title",
    itemMaster: "Item Master",
    itemCategoryMaster: "Item Category Master",
    castCategory: "Caste Category",
    castMaster: "Caste Master",
    hawkingZone: "StreetVendor Zone",
    subCastMaster: "Sub Caste Master",
    licenseValidity: "License Validity (in years)",
    penalty: "Penalty",
    bankMaster: "Bank Master",
    hawkingZoneWiseFacilities: "StreetVendor Zone Wise Facilities",
    taxTypeMaster: "Tax Type Master",
    taxNameMaster: "Tax Name Master",
    serviceTaxCollectionCycle: "Service Tax Collection Cycle",
    taxRateChartMaster: "Tax Rate Chart Master",
    noHawkingZone: "No StreetVendor Zone",
    hawkerMaster: "Street Vendor Master",
    streetvendorApplicantCategory: "Street Vendor Applicant Categor",
    srNo: "Sr. No",
    actions: "Actions",
    hawkerTypePrefix: "Street Vendor Type Prefix (in English)",
    hawkerTypePrefixMr: "Street Vendor Type Prefix (in Marathi)",
    fromDate: "From Date",
    toDate: "To Date",
    hawkerType: "Street Vendor Type",
    action: "Action",
    zoneName: "Zone Name",
    hawkingZoneInfo: "Street Vendor Zone Info",
    itemName: "Item Name",
    noOfHawkersPresent: "No Of Street Vendors Present",
    capacityOfHawkingZone: "Capacity Of Street Vendor Zone",
    declarationOrder: "Declaration Order",
    declarationOrderNo: "Declaration Order No",
    declarationDate: "Declaration Date",
    areaName: "Area Name ",
    hawkingZoneName: "Street Vendor Zone Name",
    streetvendorModeName: "Street Vendor Mode Name",
    citySurveyNo: "City Survey No ",
    gisId: "GIS Id",
    hawkingZonePrefix: "Street Vendor Zone Prefix",
    constraint: "Constraint",
    serviceTaxCollectionCyclePrefix: "Service-Tax Collection Cycle Prefix",
    hawkerTypeName: "Street Vendor Type Name",
    licenseValidityPrefix: "License Validity Prefix",
    noHawkingZoneName: "No Street Vendor Zone Name",
    noHawkingZoneprefix: "No Street Vendor Zone Prefix",
    itemCategoryPrefixMr: "Item Category Prefix (in marathi)",
    itemCategoryPrefix: "Item Category Prefix (in english)",
    itemCategoryMr: "Item Category (in marathi)",
    itemCategory: "Item Category (in english)",
    itemCategoryT: "Item Category",
    hawkingZoneWiseFacilitiesPrefix: "Street Vendor Zone Wise Facilities Prefix",
    facilities: "Facilities",
    hawkingZoneName: "Street Vendor Zone Name",
    hawkerPrefix: "Street Vendor Prefix",
    citySurveyNo: "City Survey No",
    firstName: "First Name",
    transactions: "Transactions",
    transactionPath: "SkySign / Transaction",
    issuanceOfHawkerLicensePath: "Street Vendor Management System / issuanceOfStreetVendorLicense",
    siteVisitPath: "Street Vendor Management System / Site Visit",
    taskTransfer: "Street Vendor Management System / Task Transfer",
    viewLocationOnMap: "View Location On Map",
    issuanceOfHawkerLicensePath: "Street Vendor Management System / issuanceOfStreetVendorLicense",
    siteVisitPath: "Street Vendor Management System / Site Visit",
    taskTransfer: "Street Vendor Management System / Task Transfer",
    viewLocationOnMap: "View Location On Map",
    department: "Department Name",
    issuanceOfHawkerLicense: "Issuance of Street Vendor License",
    taskTransfer: "Task Transfer",
    applicantType: "Applicant Type",
    basicApplicationDetails: "Basic Application Details",
    serviceName: "Service Name ",
    applicationNumber: "Application Number",
    applicationDate: "Application Date",
    citySurveyNo: "City Survey No",
    hawkingZoneName: "Street Vendor Zone Name ",
    areaName: "Area Name",
    hawkerDetails: "Street Vendor Details",
    addressOfHawker: "Address",
    aadharAuthentication: "Aadhaar Authentication",
    aadhaarNo: "Aadhaar No",
    streetvendorModeName: "Street Vendor Mode Name",
    additionalDetails: "Business Details",
    documentsUpload: "Documents Upload",
    documentUploadview: "Documents View",
    renewalDocumentsUpload: "Renewal Documents Upload",
    title: "Title ",
    firstName: "First Name ",
    middleName: "Middle Name ",
    lastName: "Last Name / Surname",
    gender: "Gender",
    religion: "Religion",
    caste: "Caste",
    subCast: "Sub Caste",
    dateOfBirth: "Date of Birth ",
    age: "Age ",
    mobile: "Mobile No. ",
    emailAddress: "Email Address",
    disability: "Disability",
    rationCardNo: "Ration Card No",
    yes: "Yes",
    no: "No",
    typeOfDisability: "Type Of Disability",
    oldSVSLicenseDate: "Old License Date",
    oldLicenseNo: "Old License Number",
    currentAddressofHawker: "Current Address",
    citySurveyNumber: "City Survey Number ",
    areaName: "Area Name ",
    landmarkName: "Landmark ",
    villageName: "Village Name ",
    cityName: "City Name ",
    state: "State ",
    pinCode: "Pin Code ",
    lattitude: "Lattitude ",
    logitude: "Longitude ",
    permanentPostalAddressOfHawker: "Permanent/Postal Address",
    permanentAddressAsTheCorrespondenceAddress: "Permanent Address As The Correspondence Address",
    citySurveyNumber: "City Survey Number",
    aadharAuthentication: "Aadhaar Authentication",
    verfiyOtp: "Verify OTP",
    sendOTP: "Send OTP",
    aadhaarOtpVerified: "aadhaar otp verified successfully",
    verfiyOtp: "Verify OTP",
    otpVerification: "OTP VERIFICATION",
    verifiyOTP: "Verifiy OTP",
    resendOTP: "Resend OTP",
    sendOTPMessage: "a 6 digit one-time password is sent to your registered number",
    wardNo: "Ward No",
    wardName: "Ward Name",
    natureOfBusiness: "Nature of Business",
    hawkingDurationDaily: "Street Vendor Duration Daily",
    item: "Item",
    periodOfResidenceInMaharashtra: "Period of Residence In Maharashtra",
    periodOfResidenceInPcmc: "Period of Residence In PCMC",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",
    ifscCode: "IFSC Code",
    hawkerType: "Street Vendor Type",
    bankDetails: "Bank Details",
    documentUpload: "Documents Upload ",
    adharCard: "Aadhaar Card ",
    panCard: "Pan Card ",
    rationCard: "Ration Card ",
    disablityCretificatePhoto: "Disability Certificate ",
    otherDocumentPhoto: "Other Documents ",
    affidaviteOnRS100StampAttachement: "Affidavite On RS.100 Stamp Attachement ",
    affidavite: "Affidavite",
    fileNotUploaded: "File Not Uploaded",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    attachFile: "Attach File",
    srNo: "Sr.No",
    actions: "Actions",
    tax: "Tax",
    streetVendorType: "Street Vendor Type",
    waterAmount: "Water Amount",
    propertyTaxNumber: "Property Tax No",
    waterConsumerNo: "Water Consumer No",
    proprtyAmount: "Property Amount",
    viewBill: "View Bill",
    payBill: "Pay Bill",
    PropertyAndWaterTaxes: "Taxes",
    propertyTaxes: "Property Taxes",
    viewBill: "View Bill",
    pay: "Pay",
    waterTaxes: "Water Taxes",
    areaOfStreetvendor: "Area of Street Vendor",
    education: "Education",
    viewLocationOnMap: "view location on map",
    voterNameYN: "the name of applicant is present in Voters list?",
    voterId: "Voter Identity No.",
    additionalLabour: "are additional workers present at the site?",
    maharashtra: "Maharashtra",
    oldLicenseDate: "Old License Date",
    pimpriChinchwad: "Pimpri Chinchwad",
    applicantItsSelf: "Applicant its self",
    withHelpofFamilyMembers: "with help of family members",
    byKeepingservant: "by keeping servant",
    roadWithAtBusinessLocation: "road width at the business location",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    next: "Next",
    finish: "Finish",
    submit: "Submit",
    fileSizeInstrction: "file size should not be greater than 2 mb ",

    // Validations
    citySurveyNoValdation: "city survey number is required !!!",
    citySurveyNoValdationA: "city survey number must be number !!!",
    areaNameValidation: "area name selection is required !!!",
    hawkingZoneNameValidation: "StreetVendor zone name selection is required !!!",
    titleValidation: "title selection is required !!!",
    firstNameValidation: "first name is required !!!",
    middleNameValidation: "middle name is required !!!",
    lastNameValidation: "last name is required !!!",
    genderValidation: "gender selection is required !!!",
    religionValidation: "religion selection is required !!!",
    casteValidation: "caste selection is required !!!",
    subCasteValidation: "sub caste selection is required !!!",
    dateOfBirthValidation: "date of birth is required  !!!",
    ageValidation: "age is required !!!",
    mobileNovalidation: "mobile number is required  !!!",
    rationCardNoValidation: "ration card number is required !!!",
    applicantTypeValidation: "applicant type selection is required !!!",
    emailIdValidation: "email id is required !!!",
    emailIdValidationA: "please enter valid email address !!!",
    landmarkNameValidation: "landmark name selection is required !!!",
    villageNameValidation: "village name selection is required !!!",
    cityNameValidation: "city name is required !!!",
    stateNameValidation: "state name is required !!!",
    pinCodeValidation: "pin code selection is required !!!",
    lattitudeValidation: "latitude is required !!!",
    logitudeValidation: "longitude s required !!!",
    aadharNumberValidation: "aadhaar number is required !!!",
    propertyTaxNumberValidation: "property Tax Number is required !!!",
    waterConsumerNoValidation: "water Consumer Number is required !!!",
    proprtyTaxAmountNumberValidation: "property amount is required !!!",
    waterTaxAmountValidation: "water tax amount is required !!!",
    streetvendorModeNameValidation: "street vendor Mode Name selection is required !!!",
    wardNameValidation: "ward name selection is required !!!",
    natureOfBusinessValidation: "nature of business name is required !!!",
    hawkingDurationDailyValidation: "street vendor duration daily selection is required !!!",
    hawkerTypeValidation: "street vendor type selection is required !!!",
    itemValidation: "item selection is required !!!",
    educationValidation: "education selection is required !!!",
    areaOfStreetvendorValidation: "area of street vendor is required !!!",
    periodOfResidenceInPCMCValidation: "period of residence in PCMC is required !!!",
    periodOfResidenceInMaharashtraValidation: "period of residence in maharashtra is required !!!",
    voterIdValidation: "Voter Identity Number is required !!!",
    voterNameYNValidation: "selection is required !!!",
    bankMasterValidation: "bank name selection is required !!!",
    bankAccountNoValidation: "bank account number is required !!!",
    ifscCodeValidation: "IFSC code is required !!!",
    branchNameValidation: "branch name is required !!!",
    aadhaarCardPhotoValidation: "aadhaar card is required !!!",
    panCardPhotoValidation: "pan card is required !!!",
    rationCardPhotoValidation: "ration card is required !!!",
    disablityCertificatePhotoValidation: "disablity certificate is required !!!",
    affidaviteOnRS100StampAttacheValidation: "affidavite on rs100 statmp attachement is required !!!",

    // typeOfDisabilityValidation: "type of disability is required !!!",
    otherDocumentPhotoValidation: "other document is required !!!",
    oldLicenseNoValidation: "old license number is required !!!",
    oldLicenseDateValidation: "old license date is required !!!",

    documentUpload1: "Doucument Upload",
    documentUploadSuccessfully: "document uploaded successfully !!!",
    areYouWantDelete: "are you sure you want to delete the file ?",
    fileDeletedSuccessfully: "file deleted successfully !!!",
    fileIsSafe: "file is safe",
    somethingWentWrong: "something went wrong ..!!!",
    siteVisitPhoto1: "Site Visit Photo 1",
    siteVisitPhoto2: "Site Visit Photo 2",
    siteVisitPhoto3: "Site Visit Photo 3",
    siteVisitPhoto4: "Site Visit Photo 4",
    siteVisitPhoto5: "Site Visit Photo 5",
    oldLicenseYN: "old license is available ?",
    disablityNameYN: "is disabled ?",
    applicationStatus: "Application Status",
    viewForm: "View Form",
    print: "Print",
    paymentCollection: "Payment Collection",
    paymentReceipt: "Payment Receipt",
    generateCertitifcate: "Generate Certitifcate",
    generateIDCard: "Generate ID Card",
    viewIDCard: "View ID Card",
    loiGenerationRecipt: "Service Acceptance Letter",
    viewDocument: "View Document",
    siteVisitFormPreview: "Site Visit Form Preview",
    DocumentName: "Document Name",
    mandatory: "Mandatory",
    enterRemarkForApplication: "Enter Remark for Application",
    approve: "Approve",
    reassign: "Reassign",
    siteVisitAppointmentSchedule: "Site Visit Appointment Schedule",
    addSlotsOfSiteVisit: "Add Slots Of Site Visits",
    addMore: "Add More",
    delete: "Delete",
    bookNow: "Book Now",
    siteVisitSchedule: "Site Visit Schedule",
    fromDateValidation: "from date selection is required",
    hawkerTypePrefixValidation: "Street Vendor Type Prefix (in English) is required",
    hawkerTypePrefixMrValidation: "Street Vendor Type Prefix (in Marathi) is required",
    hawkerTypeValidationT: "Street Vendor Type (in English) is required",
    hawkerTypeMrValidation: "Street Vendor Type (in Marathi) is required",
    itemMaster: "Item Master ",
    itemCategoryPrefixValidation: "Item Category Prefix is Required (in English) !!! ",
    itemCategoryPrefixMrValidation: "Item Category Prefix is Required (in Marathi) !!! ",
    itemCategoryValidation: "Item Category is Required (in English) !!! ",
    itemCategoryMrValidation: "Item Category is Required (in Marathi) !!! ",
    itemPrefixValidation: "Item Master Prefix is Required (in English) !!! ",
    itemPrefixMrValidation: "Item Master Prefix is Required (in Marathi) !!! ",
    itemCategoryValidationEn: "item category is Required !!!",
    itemValidationEn: "item is Required (in English) !!! ",
    itemValidationMr: "item is Required (in Marathi) !!! ",
    itemPrefixEn: "Item Prefix (in English)",
    itemPrefixMr: "Item Prefix (in Marathi)",
    itemEn: "Item (in English)",
    itemMr: "Item (in Marathi)",
    licenseValidityPrefixValidation: "License Validity Prefix is required (in English) !!! ",
    licenseValidityPrefixMrValidation: "License Validity Prefix is required (in Marathi) !!! ",
    licenseValidityValidation: "License Validity is required ",
    licenseValidityMrValidation: "License Validity is required (in Marathi) !!! ",
    licenseValidityEn: "License Validity in (Year) (in English)",
    licenseValidityMr: "License Validity in (Year) (in Marathi)",
    licenseValidityPrefixEn: "License Validity Prefix (in English)",
    licenseValidityPrefixMr: "License Validity Prefix (in Marathi) ",
    hawkingZonePrefixValidation: "StreetVendor Zone Prefix is Required (in English) !!!",
    hawkingZonePrefixMrValidation: "StreetVendor Zone Prefix is Required (in Marathi) !!!",
    gisIdValidation: "GIS id is required !!!",
    hawkingNameValidation: "StreetVendor zone name is required (in English) !!! ",
    hawkingNameMrValidation: "StreetVendor zone name is required (in Marathi) !!! ",
    declarationDateValidation: "declaration date is required !!!",
    declarationOrderNoValidation: "declaration order number is required !!!",
    capacityOfHawkingZoneValidation: "capacity of StreetVendor zone is required !!!",
    noOfHawkersPresentValidation: "number of hawkers present is required !!!",
    hawkingZoneInfoValidation: "StreetVendor zone info is required (in English) !!! ",
    hawkingZoneInfoMrValidation: "StreetVendor zone info is required (in Marathi) !!! ",
    hawkingZoneInfo: "StreetVendor Zone Info (in English)",
    hawkingZoneInfoMr: "StreetVendor Zone Info (in Marathi)",
    capacityOfHawkingZone: "Capacity of Number of StreetVendor Zone",
    numberOfHawkersPresent: "Number of Hawkers Present",
    declarationOrderNumber: "Declaration Order Number",
    hawkingZonePrefixEn: "StreetVendor Zone Prefix (in English)",
    hawkingZonePrefixMr: "StreetVendor Zone Prefix (in Marathi)",
    zoneName: "Zone Name",
    hawkingZoneNameMr: "StreetVendor Zone Name (in Marathi) ",
    hawkingZoneNameEn: "StreetVendor Zone Name (in English) ",
    hawkerMode: "StreetVendor Mode",
    hawkerModePrefixEn: "StreetVendor Mode Prefix (in English)",
    noHawkingZonePrefixEn: "No Hawking Zone Prefix (in English)",
    noHawkingZonePrefixMr: "No Hawking Zone Prefix (in Marathi)",
    hawkerModePrefixMr: "StreetVendor Mode Prefix (in Marathi)",
    hawkerModeEn: "StreetVendor Mode (in English)",
    hawkerModeMr: "StreetVendor Mode (in Marathi)",
    hawkerModePrefixValidation: "StreetVendor mode prefix is required  (in English) !!! ",
    hawkerModePrefixMrValidation: "StreetVendor mode prefix is required  (in Marathi) !!! ",
    hawkerModeValidation: "StreetVendor mode is required  (in English) !!! ",
    hawkerModeMrValidation: "StreetVendor type mode is required  (in Marathi) !!! ",
    hawkerTypeValidation: "Street Vendor name is required  !!!",
    noHawkingZoneMr: "No Hawking Zone Name (in Marathi)",
    noHawkingZoneEn: "No Hawking Zone Name (in English)",
    noHawkingZoneInfoMr: "No Hawking Zone Info (in Marathi)",
    noHawkingZoneInfoEn: "No Hawking Zone Info (in English)",
    gisIdValidation: "GIS ID is required !!! ",
    zoneNameValidation: "zone name selection is required !!! ",
    declarationOrderValidation: "declaration order is required  !!! ",
    noHawkingZoneprefixEnValidation: "No Hawking Zone Prefix is Required !!!",
    noHawkingZoneprefixMrValidation: "No Hawking Zone Prefix is Required !!!",
    noHawkingZoneEnValidation: "No Hawking Zone Name is Required !!!",
    noHawkingZoneMrValidation: "No Hawking Zone Name is Required !!!",
    noHawkingZoneInfoEnValidation: "No Hawking Zone Info is Required !!!",
    noHawkingZoneInfoMrValidation: "No Hawking Zone Info is Required !!!",
    applicantPrefixMr: "Applicant Prefix (in Marathi)",
    applicantPrefixEn: "Applicant Prefix (in English)",
    applicantTypeMr: "Applicant Type (in Marathi)",
    applicantTypeEn: "Applicant Type (in English)",
    applicantSubTypeMr: "Applicant SubType (in Marathi)",
    applicantSubTypeEn: "Applicant SubType (in English)",
    applicantPrefixValidation: "applicant prefix is required !!!",
    typeValidation: "applicant type is required !!!",
    subtypeValidation: "applicant subtype is required !!!",
    applicantPrefixValidation: " अर्जदार उपसर्ग आवश्यक आहे !!!",
    hawkingZoneWiseFacilitiesPrefixEn: "Hawking Zone Wise Facilities Prefix (in English)",
    hawkingZoneWiseFacilitiesPrefixMr: "Hawking Zone Wise Facilities Prefix (in Marathi)",
    facilitynameEn: "Facility Name (in English)",
    facilitynameMr: "Facility Name (in English)",
    hawkingZoneWiseFacilitiesPrefixValidation: "hawking zonewise facility prefix is required !!!",
    hawkingZoneWiseFacilitiesPrefixMrValidation: "hawking zonewise facility prefix is required !!!",
    hawkigZoneValidation: "hawking zone selection is required !!!",
    facilitiesValidation: "facility name is required !!!",
    facilitiesMrValidation: "facility name is required !!!",
    hawkingDurationDailyPrefixEn: "hawking duration prefix (in English)",
    hawkingDurationDailyPrefixMr: "hawking duration prefix (in Marathi)",
    hawkingDurationDailyFrom: "Hawking Duration Daily From",
    hawkingDurationDailyTo: "Hawking Duration Daily To",
    businessSubType: "Business Subtype",
    businessType: "Business Type",
    hawkingDurationDailyPrefixValidation: "hawking Duration Daily Prefix is required !!!",
    hawkingDurationDailyFromValidation: "hawking duration daily from is required !!!",
    hawkingDurationDailyToValidation: "hawking duration daily to is required !!!",
    businessTypeValidation: "business type selection is required !!!",
    businessSubTypeValidation: "business subtype selection is required !!!",
    businessSubTypePrefixMr: "Business SubType Prefix (in marathi)",
    businessSubTypePrefixEn: "Business SubType Prefix (in english) ",
    businessSubTypeEn: "Business SubType (in english)",
    businessSubTypeMr: "Business SubType (in marathi)",
    businessSubTypePrefixEnValidation: "business subtype prefix is required !!!",
    businessSubTypePrefixMrValidation: "business subtype prefix is required !!!",
    businessSubTypeMrValidation: "business subtype name is required !!!",
    businessSubTypeEnValidation: "business subtype name is required !!!",

    businessTypePrefixEn: "Business Prefix (in english) ",
    businessTypePrefixMr: "Business Prefix (in marathi) ",
    businessTypeEn: "Business (in english)",
    businessTypeMr: "Business (in marathi)",
    businessTypePrefixEnValidation: "business prefix is required !!!",
    businessTypePrefixMrValidation: "business prefix is required !!!",
    businessTypeMrValidation: "business name is required !!!",
    businessTypeEnValidation: "business name is required !!!",
    renewalOfIssuanceOfHawkerLicense: "Renewal of Issuance of Hawker License",
    issuanceOfHawkerLicenseNumber: "Hawker License Number",
      siteVisitDate:"Site Visit Date",
    siteVisitTime: "Site Visit Time",
    streetVendorFullName: "StreetVendor Full Name",
    
    
  },
  mr: {
    loiGenerationRecipt: "LOI जनरेशन पावती",
    receiptModeDetails: "पावती प्रकार तपशील",
    chargeName: "शुल्काचे नाव",
    loiPreview: "Loi पूर्वावलोकन",
    iCard: "ओळखपत्र",
    view: "पहा",
    viewCertificate: "प्रमाणपत्र पहा",
    amount: "रक्कम",
    streetVendorQuestion: "रस्त्यावरील विक्रेता प्रश्न",
    or: "किंवा",
    loiRecord: "loi रेकॉर्ड",
    loiNO: "LOI क्र.",
    loiGeneration: "LOI जनरेशन",
    loiPrint: "LOI प्रिंट",
    siteVisitSchedule: "साइट भेटीचे वेळापत्रक",
    loiCollection: "पेमेंट संकलन",
    search: "शोधा",
    and: "आणि",
    paymentMode: "पेमेंट मोड",
    paymentType: "पैसे भरण्याची पध्दत",
    loiDetails: "LOI तपशील",
    loiDate: "LOI तारीख",
    applicationNo: "अर्ज क्र.",
    rate: "दर",
    total: "एकूण",
    totalInWords: "शब्दांमध्ये एकूण शुल्क",
    licenseType: "परवाना प्रकार",
    durationOfLicenseValidity: "परवान्याच्या वैधतेचा कालावधी (वर्षात)",
    hawkerType: "फेरीवाला प्रकार",
    licenseValidity: "परवाना वैधता",
    applicantDetails: "अर्जदाराचे तपशील",
    paymetMode: "पेमेंट मोड",
    dateOfIssuance: "जारी करण्याची तारीख",
    calendarYear: "जानेवारी ते डिसेंबर असे वर्ष",
    chargesDetails: "शुल्काचा तपशील",
    serviceCharge: "सेवा शुल्क",
    financialYear: "आर्थिक वर्ष",
    checkFormLicenseValidityForm: "परवाना वैधता फॉर्म तपासा",
    generateLoi: "LOI व्युत्पन्न करा",
    previewLoi: "LOI चे पूर्वावलोकन करा",
    verifyLoi: "LOI सत्यापित करा",
    serviceChargeTypeName: "सेवा शुल्काचे प्रकार नाव",
    totalCharges: "एकूण शुल्क",
    applicantName: "अर्जदाराचे नाव",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",
    streetVendorManagmentSystem: "पथविक्रेता व्यवस्थापन प्रणाली",
    HMS: "पथविक्रेता व्यवस्थापन प्रणाली",
    inFeet: "रुंदीमध्ये",
    streetVendorType: "पथविक्रेत्याचा प्रकार",
    oldLicenseDate: "जुनी परवाना तारीख",
    siteVisitPhotoUpload: "साइट भेटीचे फोटो अपलोड करा",
    siteVisitPhoto: "साइट भेटीचे फोटो",
    streetVendorThumb1: "बायोमेट्रिक अंगठ्याचा ठसा 1",
    streetVendorThumb2: "बायोमेट्रिक अंगठ्याचा ठसा 2",
    businessTrafficCongestion: "व्यवसायामुळे सद्द्यस्थितीत रहदारीस अडथळा होतो का?",
    remark: "Remark",
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    roadWithBusinessLocation: "व्यवसाय ठिकाणची रस्ता रुंदी(फूट)",
    streetVendorInformation: "पथविक्रेता माहिती",
    businessHawkinglocation: "व्यवसाय कार्य",
    applicantItsSelf: "अर्जदार स्वतः",
    withHelpofFamilyMembers: "कुटुंबातील सदस्यांच्या मदतीने",
    streetVendorPhoto: "फोटो",
    byKeepingservant: "नोकर ठेवून",
    inspectionSellingGoods: "अर्जदार नमूद केलेल्या जागेवर व्यवसाय करीत असल्याचे तपासणीत आढळले?",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    fileNotUploaded: "फाइल अपलोड केली नाही",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",
    hawkerType: "पथविक्रीचा प्रकार",
    department: "Department Name",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    report: "अहवाल",
    ward: "प्रभाग",
    zone: "झोन",
    religionPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / धर्म",
    hawkerTypePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता प्रकार",
    businessTypeMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / व्यवसाय प्रकार मास्टर",
    businessSubTypePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / व्यवसाय उपप्रकार",
    titlePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / शीर्षक",
    itemMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / वस्तु मास्टर",
    itemCategoryMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / वस्तु श्रेणी मास्टर",
    castCategoryPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कास्ट श्रेणी",
    castMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कास्ट मास्टर",
    hawkingZonePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर /  पथविक्रेता क्षेत्र",
    subCastMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / सब कास्ट मास्टर",
    licenseValidityPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / परवाना वैधता",
    penaltyPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / दंड",
    bankMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / बँक मास्टर",
    hawkingZoneWiseFacilitiesPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता झोननिहाय सुविधा",
    taxTypeMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर प्रकार मास्टर",
    taxNameMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर नाव मास्टर",
    serviceTaxCollectionCyclePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / सेवा कर संकलन सायकल",
    taxRateChartMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर दर चार्ट मास्टर",
    noHawkingZonePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता क्षेत्र नाही",
    hawkerMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता मास्टर",
    streetvendorApplicantCategory: "Street Vendor Applicant Categor",
    religion: "धर्म",
    hawkerType: "पथविक्रीचा प्रकार",
    businessTypeMaster: "व्यवसायचा प्रकार मास्टर",
    businessSubType: "व्यवसाय उपप्रकार",
    title: "शीर्षक",
    itemMaster: "वस्तु मास्टर",
    itemCategoryMaster: "वस्तु श्रेणी मास्टर",
    castCategory: "कास्ट श्रेणी",
    castMaster: "कास्ट मास्टर",
    hawkingZone: "पथविक्रेत्याचा क्षेत्र",
    subCastMaster: "सब कास्ट मास्टर",
    licenseValidity: "परवाना वैधता",
    penalty: " दंड",
    bankMaster: "बँक मास्टर",
    hawkingZoneWiseFacilities: "पथविक्रेत्याच्या झोननिहाय सुविधा",
    taxTypeMaster: " कर प्रकार मास्टर",
    taxNameMaster: "कर नाव मास्टर",
    serviceTaxCollectionCycle: "सेवा कर संकलन सायकल",
    taxRateChartMaster: "कर दर चार्ट मास्टर",
    noHawkingZone: "न पथविक्रेता क्षेत्र",
    hawkerMaster: "पथविक्रेत्याचा मास्टर",
    courtName: "न्यायालयाचे नाव",
    roadName: "रस्त्याचे नाव",
    address: "पत्ता",
    landmark: "जवळची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "Pin Code",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    hawkerTypePrefix: "पथविक्रेत्याचा उपसर्ग प्रकार (इंग्रजी मध्ये)",
    hawkerTypePrefixMr: "पथविक्रेत्याचा उपसर्ग प्रकार (मराठी मध्ये)",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    hawkerType: "पथविक्रीचा प्रकार (इंग्रजी मध्ये) ",
    hawkerType1: "पथविक्रीचा प्रकार",

    remark: "शेरा",
    roadWithAtBusinessLocation: "व्यवसायाच्या ठिकाणी रस्त्याची रुंदी",
    action: "क्रिया",
    zoneName: "पथविक्रेत्याचे नाव",
    hawkingZoneInfo: "पथविक्रेत्याच्या झोनची माहिती",
    itemName: "वस्तु",
    noOfHawkersPresent: "उपस्थित पथविक्रेता्सची संख्या",
    capacityOfHawkingZone: "पथविक्रेत्याच्या झोनची क्षमता",
    declarationOrder: "घोषणा आदेश",
    declarationOrderNo: "घोषणा आदेश क्र",
    declarationDate: "घोषणा तारीख",
    areaName: "क्षेत्राचे नाव",
    hawkingZoneName: "पथविक्रीच्या झोनचे नाव",
    streetvendorModeName: "पथविक्रीच्या व्यवसायाचे स्वरूप",
    citySurveyNo: "सिटी सर्व्हे क्र ",
    gisId: "GIS आयडी",
    serviceTaxCollectionCyclePrefix: "सेवा कर संकलन चक्र उपसर्ग",
    hawkingZonePrefix: "पथविक्रेत्याच्या झोनचा उपसर्ग",
    hawkerTypeName: "पथविक्रीच्या प्रकाराचे नाव",
    licenseValidityPrefix: "परवाना वैधता उपसर्ग",
    noHawkingZoneName: "न पथविक्रेता झोनचे नाव",
    noHawkingZoneprefix: "न पथविक्रेता झोनचा उपसर्ग नाही",
    itemCategoryPrefixMr: "वस्तुच्या श्रेणीचा उपसर्ग (मराठी मध्ये)",
    itemCategoryPrefix: "वस्तुच्या श्रेणीचा उपसर्ग (इंग्रजी मध्ये)",
    itemCategory: "वस्तुची श्रेणी (मराठी मध्ये)",
    itemCategoryT: "वस्तुची श्रेणी",
    itemCategoryMr: "वस्तुची श्रेणी (इंग्रजी मध्ये)",
    hawkingZoneWiseFacilitiesPrefix: "पथविक्रेता झोननिहाय सुविधा उपसर्ग",
    facilities: "सुविधा",
    hawkingZoneName: "पथविक्रीच्या झोनचे नाव",
    hawkerPrefix: "पथविक्रेत्याचा उपसर्ग",
    citySurveyNo: "सिटी सर्व्हे क्र",
    add: "नवीन नोंदणी करा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    next: " पुढे",
    fileSizeInstrction: "फाइल आकार 2 mb पेक्षा जास्त नसावा",
    transactions: "व्यवहार",
    transactionPath: "परवाना/ व्यवहार ",
    issuanceOfHawkerLicense: "पथविक्रेता परवाना जारी करणे",
    siteVisit: "स्थळ भेट",
    citySurveyNo: "सिटी सर्व्हे क्र ",
    streetvendorModeName: "पथविक्रीच्या व्यवसायाचे स्वरूप",
    issuanceOfHawkerLicensePath: "पथविक्रेता व्यवस्थापन प्रणाली / पथविक्रेता परवाना जारी करणे",
    siteVisitPath: "पथविक्रेता व्यवस्थापन प्रणाली /साइटला भेट द्या",
    taskTransfer: "पथविक्रेता व्यवस्थापन प्रणाली / कार्य हस्तांतरण",
    viewLocationOnMap: "नकाशावर स्थान पहा",
    back: "मागे",
    next: "पुढे",
    issuanceOfHawkerLicense: "पथविक्रेता परवाना जारी करणे",
    taskTransfer: "कार्य हस्तांतरण",
    siteVisit: "साइटला भेट द्या",
    oldSVSLicenseDate: "जुन्या परवाण्याची तारीख",
    oldLicenseNo: "जुना परवाना क्रमांक",
    issuanceOfHawkerLicenseT: "पथविक्रेता परवाना जारी करणे",
    applicantType: "अर्जदाराचा प्रकार",
    basicApplicationDetails: "मूलभूत अर्ज तपशील",
    serviceName: "सेवेचे नाव ",
    applicationNumber: "अर्ज क्रमांक",
    applicationDate: "अर्जाची तारीख",
    citySurveyNo: "शहर सर्वेक्षण क्रमांक",
    hawkingZoneName: "पथविक्रीच्या झोनचे नाव",
    areaName: "क्षेत्राचे नाव",
    hawkerDetails: "पथविक्रेत्याच्या तपशील",
    addressOfHawker: "पत्ता",
    aadharAuthentication: "आधार प्रमाणीकरण",
    aadhaarNo: "आधार क्रमांक",
    additionalDetails: "व्यवसाय तपशील",
       documentsUpload: "दस्तऐवज अपलोड",
    renewalDocumentsUpload: "नूतनीकरण दस्तऐवज अपलोड",
   documentUploadview:"दस्तऐवज पहा",
    title: "शीर्षक",
    firstName: "पहिले नाव",
    middleName: "वडीलांचे/पतीचे नाव",
    lastName: "आडनाव",
    gender: "लिंग",
    religion: "धर्म",
    caste: "जात",
    subCast: "पोटजात",
    dateOfBirth: "जन्मतारीख ",
    age: "वय",
    mobile: "दूरध्वनी क्रमांक",
    emailAddress: "ई-मेल आयडी ",
    disability: "दिव्यांग",
    rationCardNo: "शिधापत्रिका क्रमांक",
    yes: "होय",
    no: "नाही",
    typeOfDisability: "दिव्यांगाचा प्रकार",
    back: "मागे",
    next: "पुढे",
    finish: "प्रस्तुत करा",
    currentAddressofHawker: "सध्याचा पत्ता",
    citySurveyNumber: "शहर सर्वेक्षण क्रमांक ",
    areaName: "क्षेत्राचे नाव ",
    landmarkName: "जवळची खुण",
    villageName: "गावाचे नाव ",
    cityName: "शहराचे नाव ",
    state: "राज्य ",
    pinCode: "पिन कोड ",
    lattitude: "अक्षांश ",
    logitude: "रेखांश ",
    permanentPostalAddressOfHawker: "कायमस्वरूपीचा/पत्रव्यवहाराचा पत्ता",
    permanentAddressAsTheCorrespondenceAddress: "पत्रव्यवहाराचा पत्ता म्हणून कायमचा पत्ता",
    citySurveyNumber: "शहर सर्वेक्षण क्रमांक",
    wardNo: "प्रभाग क्रमांक ",
    wardName: "प्रभागाचे नाव ",
    natureOfBusiness: "व्यवसायाचे स्वरूप ",
    hawkingDurationDaily: "पथविक्रीचा दैनिक कालावधी",
    item: "वस्तु",
    periodOfResidenceInMaharashtra: "महाराष्ट्रात राहण्याचा कालावधी",
    periodOfResidenceInPcmc: "पीसीएमसीमध्ये राहण्याचा कालावधी",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ifscCode: "आयफएससी कोड",
    hawkerType: "पथविक्रीचा प्रकार (इंग्रजी मध्ये)",
    hawkerTypeMr: "पथविक्रीचा प्रकार (मराठी मध्ये)",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड करा",
    adharCard: "आधार कार्ड ",
    rationCard: "शिधापत्रिका ",
    disablityCretificatePhoto: "दिव्यांग प्रमाणपत्र ",
    otherDocumentPhoto: "इतर दस्तऐवज ",
    affidaviteOnRS100StampAttachement: "रु. १००/- चे स्टॅम्प पेपरवर प्रतिज्ञा पत्र ",
    affidavite: " प्रतिज्ञा पत्र ",
    panCard: "पॅन कार्ड ",
    waterConsumerNo: "पाणी ग्राहक क्र.",
    waterAmount: "रक्कम",
    proprtyAmount: "रक्कम",
    propertyTaxNumber: "मिळकत कर क्र.",
    tax: "कर",
    viewBill: "बिल पहा",
    pay: "बिल भरा",
    PropertyAndWaterTaxes: "कर",
    propertyTaxes: "मालमत्ता कर",
    waterTaxes: "पाणी कर ",
    pimpriChinchwad: "पिंपरी चिंचवड",
    maharashtra: "महाराष्ट्र",
    areaOfStreetvendor: "पथविक्री क्षेत्र",
    viewLocationOnMap: "नकाशावर स्थान पहा",
    voterNameYN: "अर्जदाराचे नाव मतदार यादीत आहे का?",
    voterId: "मतदार ओळखपत्र क्रमांक.",
    additionalLabour: "हॉकिन्सच्या ठिकाणी अतिरिक्त कामगार उपस्थित आहेत?",
    education: "शिक्षण",
    verfiyOtp: "ओटीपी तपसा",
    sendOTP: "ओटीपी पाठवा",
    aadhaarOtpVerified: "आधार ओटीपी यशस्वीरित्या सत्यापित",
    otpVerification: "ओटीपी पडताळणी",
    verifiyOTP: "ओटीपी सत्यापित करा",
    resendOTP: "ओटीपी पुन्हा पाठवा",
    sendOTPMessage: "तुमच्या नोंदणीकृत क्रमांकावर ६ अंकी वन-टाइम पासवर्ड पाठवला",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    submit: "प्रस्तुत करणे",

    // Validations
    citySurveyNoValdation: "शहर सर्वेक्षण क्रमांक आवश्यक आहे !!!",
    citySurveyNoValdationA: "शहर सर्वेक्षण क्रमांक आवश्यक आहे !!!",
    areaNameValidation: "क्षेत्राचे नाव निवडणे आवश्यक आहे !!!",
    hawkingZoneNameValidation: "पथविक्रेता झोनचे नाव निवडणे आवश्यक आहे !!!",
    titleValidation: "शीर्षक निवड आवश्यक आहे !!!",
    firstNameValidation: "पहिले नाव आवश्यक आहे !!!",
    middleNameValidation: "वडीलांचे/पतीचे नाव आवश्यक आहे !!!",
    lastNameValidation: "आडनाव आवश्यक आहे !!!",
    genderValidation: "लिंग निवड आवश्यक आहे !!!",
    religionValidation: "धर्म निवड आवश्यक आहे !!!",
    casteValidation: "जात निवड आवश्यक आहे !!!",
    subCasteValidation: "पोटजात निवड आवश्यक आहे !!!",
    dateOfBirthValidation: "जन्मतारीख आवश्यक आहे !!!",
    ageValidation: "वय आवश्यक आहे !!!",
    mobileNovalidation: "मोबाईल नंबर आवश्यक आहे !!!",
    rationCardNoValidation: "शिधापत्रिका क्रमांक आवश्यक आहे !!!",
    applicantTypeValidation: "अर्जदाराचे प्रकार निवड आवश्यक आहे !!!",
    emailIdValidation: "ई-मेल आयडी आवश्यक आहे !!!",
    emailIdValidationA: "कृपया वैध ई-मेल पत्ता प्रविष्ट करा !!!",
    landmarkNameValidation: "जवळची खूण नाव निवडणे  आवश्यक आहे ",
    villageNameValidation: "गावाचे नाव निवडणे आवश्यक आहे !!! ",
    cityNameValidation: "शहराचे नाव आवश्यक आहे !!!",
    stateNameValidation: "राज्याचे नाव आवश्यक आहे !!!",
    pinCodeValidation: "पिन कोड निवडणे आवश्यक आहे !!!",
    lattitudeValidation: "अक्षांश आवश्यक आहे !!!",
    logitudeValidation: "रेखांश आवश्यक आहे !!!",
    aadharNumberValidation: "आधार क्रमांक आवश्यक आहे !!!",
    propertyTaxNumberValidation: "मालमत्ता कर क्रमांक आवश्यक आहे !!!",
    waterConsumerNoValidation: "पाणी ग्राहक क्रमांक आवश्यक आहे !!!",
    proprtyTaxAmountNumberValidation: "मालमत्तेची रक्कम आवश्यक आहे !!!",
    waterTaxAmountValidation: "पाणी कराची रक्कम आवश्यक आहे !!!",
    streetvendorModeNameValidation: " पथविक्रीच्या व्यवसायाचे स्वरूप निवड आवश्यक आहे !!!",
    wardNameValidation: " प्रभाग नावाची निवड आवश्यक आहे  !!!",
    natureOfBusinessValidation: "व्यवसायाचे स्वरूप आवश्यक आहे !!!",
    hawkingDurationDailyValidation: "पथविक्रीचा दैनिक कालावधी निवड आवश्यक आहे !!!",
    hawkerTypeValidationT: "पथविक्रीचा प्रकार निवड आवश्यक आहे !!!",
    itemValidation: "वस्तु निवड आवश्यक आहे !!!",
    educationValidation: "शिक्षण निवड आवश्यक आहे !!!",
    areaOfStreetvendorValidation: "पथविक्री क्षेत्रनाव आवश्यक आहे !!!",
    periodOfResidenceInPCMCValidation: "पीसीएमसीमध्ये राहण्याचा कालावधी आवश्यक आहे !!!",
    periodOfResidenceInMaharashtraValidation: "महाराष्ट्रात राहण्याचा कालावधी आवश्यक आहे !!!",
    voterNameYNValidation: "निवड आवश्यक आहे",
    voterIdValidation: "मतदार ओळखपत्र क्रमांक आवश्यक आहे !!!",
    bankMasterValidation: "बँकेचे नाव निवडणे आवश्यक आहे !!!",
    branchNameValidation: "शाखेचे नाव आवश्यक आहे !!!",
    bankAccountNoValidation: "बँक खाते क्रमांक आवश्यक आहे !!!",
    ifscCodeValidation: "IFSC कोड आवश्यक आहे !!!",
    aadhaarCardPhotoValidation: "आधार कार्ड आवश्यक आहे !!!",
    panCardPhotoValidation: "पॅन कार्ड आवश्यक आहे !!!",
    rationCardPhotoValidation: "शिधापत्रिका आवश्यक आहे !!!",
    disablityCertificatePhotoValidation: "दिव्यांग प्रमाणपत्र आवश्यक आहे !!!",
    affidaviteOnRS100StampAttacheValidation: "रु. १००/- चे स्टॅम्प पेपरवर प्रतिज्ञा पत्र आवश्यक आहे !!!",
    otherDocumentPhotoValidation: "इतर दस्तऐवज आवश्यक आहे !!!",
    // typeOfDisabilityValidation: "अपंगत्वाचा प्रकार आवश्यक आहे !!!",
    oldLicenseNoValidation: "जुना परवाना क्रमांक आवश्यक आहे !!!",
    oldLicenseDateValidation: "जुनी परवाना तारीख आवश्यक आहे !!!",
    documentUpload1: "दस्तऐवज अपलोड",
    documentUploadSuccessfully: "दस्तऐवज यशस्वीरित्या अपलोड केले !!!",
    areYouWantDelete: "तुम्हाला खात्री आहे की तुम्हाला फाइल हटवायची आहे ?",
    fileDeletedSuccessfully: "फाइल यशस्वीरित्या हटवली !!!",
    fileIsSafe: "फाइल सुरक्षित आहे",
    somethingWentWrong: "काहीतरी चूक झाली ..!!!",
    siteVisitPhoto1: "साइट भेट फोटो 1",
    siteVisitPhoto2: "साइट भेट फोटो 2",
    siteVisitPhoto3: "साइट भेट फोटो 3",
    siteVisitPhoto4: "साइट भेट फोटो 4",
    siteVisitPhoto5: "साइट भेट फोटो 5",
    oldLicenseYN: "जुना परवाना उपलब्ध आहे का ?",
    disablityNameYN: "दिव्यांग आहात का ?",
    applicationStatus: "अर्जाची स्थिती",
    viewForm: "फॉर्म पहा",
    print: "छापणे",
    siteVisitSchedule: "साइट भेटीचे वेळापत्रक",
    paymentCollection: "पेमेंट संकलन",
    paymentReceipt: "पैसे भरल्याची पावती",
    generateCertitifcate: "प्रमाणपत्र व्युत्पन्न करा",
    generateIDCard: "ओळखपत्र तयार करा",
    viewIDCard: "ओळखपत्र पहा",
    viewDocument: "कागदपत्र पहा",
    siteVisitFormPreview: "साइट भेट फॉर्म पूर्वावलोकन",
    DocumentName: "दस्तऐवजाचे नाव",
    mandatory: "अनिवार्य",
    enterRemarkForApplication: "अर्जासाठी टिप्पणी प्रविष्ट करा",
    approve: "मंजूर",
    reassign: "पुन्हा नियुक्त करा",
    siteVisitAppointmentSchedule: "साइट भेट भेटीचे वेळापत्रक",
    addSlotsOfSiteVisit: "साइट भेटींचे स्लॉट जोडा",
    addMore: "आणखी जोडा",
    delete: "हटवा",
    bookNow: "Book Now",
    fromDateValidation: "तारीख पासून निवड आवश्यक आहे",
    hawkerTypePrefixValidation: "पथविक्रेता प्रकार उपसर्ग (इंग्रजीमध्ये) आवश्यक आहे",
    hawkerTypePrefixMrValidation: "पथविक्रेता प्रकार उपसर्ग (मराठीमध्ये) आवश्यक आहे",
    hawkerTypeValidation: "पथविक्रेता प्रकार (इंग्रजीमध्ये) आवश्यक आहे",
    hawkerTypeMrValidation: "पथविक्रेता प्रकार (मराठीमध्ये) आवश्यक आहे",
    itemMaster: "वस्तू मास्टर",
    itemCategoryPrefixValidation: "वस्तू श्रेणी उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    itemCategoryPrefixMrValidation: "वस्तू श्रेणी उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    itemCategoryValidation: "वस्तू श्रेणी आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    itemCategoryMrValidation: "वस्तू श्रेणी आवश्यक आहे (मराठीमध्ये) !!! ",
    itemPrefixValidation: "वस्तू मास्टर उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    itemPrefixMrValidation: "वस्तू मास्टर उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    itemCategoryValidationEn: "वस्तू श्रेणी आवश्यक आहे !!!",
    itemValidationEn: "वस्तू आवश्यक आहे  (इंग्रजीमध्ये) !!! ",
    itemValidationMr: "वस्तू आवश्यक आहे  (मराठीमध्ये) !!! ",
    itemPrefixEn: "वस्तू उपसर्ग (इंग्रजीमध्ये)",
    itemPrefixMr: "वस्तू उपसर्ग (मराठीमध्ये)",
    itemEn: "वस्तू (इंग्रजीमध्ये)",
    itemMr: "वस्तू (मराठीमध्ये)",
    licenseValidityPrefixValidation: "परवाना वैधता उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    licenseValidityPrefixMrValidation: "परवाना वैधता उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    licenseValidityValidation: "परवाना वैधता आवश्यक आहे !!! ",
    licenseValidityMrValidation: "परवाना वैधता आवश्यक आहे (मराठीमध्ये) !!! ",
    licenseValidityEn: "परवाना वैधता (वर्षे) (इंग्रजीमध्ये)",
    licenseValidity: "परवाना वैधता (वर्षे) ",

    licenseValidityMr: "परवाना वैधता (वर्षे) (मराठीमध्ये)",
    licenseValidityPrefixEn: "परवाना वैधता उपसर्ग (इंग्रजीमध्ये)",
    licenseValidityPrefixMr: "परवाना वैधता उपसर्ग (मराठीमध्ये)",
    hawkingZonePrefixValidation: "पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!!",
    hawkingZonePrefixMrValidation: "पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे (मराठीमध्ये) !!!",
    gisIdValidation: "जीआयएस आयडी आवश्यक आहे !!!",
    hawkingNameValidation: "पथविक्रेता झोनचे नाव आवश्यक आहे (इंग्रजीमध्ये) !!!",
    hawkingNameMrValidation: "पथविक्रेता झोनचे नाव आवश्यक आहे (मराठीमध्ये) !!!",
    declarationDateValidation: "घोषणा तारीख आवश्यक आहे !!!",
    declarationOrderNoValidation: "घोषणा ऑर्डर क्रमांक आवश्यक आहे !!",
    capacityOfHawkingZoneValidation: "पथविक्रेता झोनची क्षमता आवश्यक आहे !!!",
    noOfHawkersPresentValidation: "उपस्थित फेरीवाल्यांची संख्या आवश्यक आहे !!!",
    hawkingZoneInfoValidation: "पथविक्रेता क्षेत्र माहिती आवश्यक आहे (इंग्रजीमध्ये) !!!",
    hawkingZoneInfoMrValidation: "पथविक्रेता क्षेत्र माहिती आवश्यक आहे (मराठीमध्ये) !!!",
    hawkingZoneInfo: "पथविक्रेता क्षेत्र माहिती (इंग्रजीमध्ये)",
    hawkingZoneInfoMr: "पथविक्रेता क्षेत्र माहिती (मराठीमध्ये)",
    capacityOfHawkingZone: "पथविक्रेता झोनच्या संख्येची क्षमता",
    numberOfHawkersPresent: "सध्या पथविक्रेता्सची संख्या",
    declarationOrderNumber: "घोषणा ऑर्डर क्रमांक",
    hawkingZonePrefixEn: "पथविक्रेता क्षेत्र उपसर्ग (इंग्रजीमध्ये)",
    hawkingZonePrefixMr: "पथविक्रेता क्षेत्र उपसर्ग (मराठीमध्ये)",
    zoneName: "झोनचे नाव",
    constraint: "मर्यादा",
    hawkingZoneNameMr: "पथविक्रेता झोनचे नाव (मराठीमध्ये) ",
    hawkingZoneNameEn: "पथविक्रेता झोनचे नाव (इंग्रजीमध्ये) ",
    noHawkingZonePrefixMr: "न पथविक्रेता झोनचे नाव (मराठीमध्ये) ",
    noHawkingZonePrefixEn: "न पथविक्रेता झोनचे नाव (इंग्रजीमध्ये) ",
    hawkerMode: "फेरीवाला मोड",
    hawkerModePrefixEn: "पथविक्रेता मोड उपसर्ग (इंग्रजीमध्ये)",
    hawkerModePrefixMr: "पथविक्रेता मोड उपसर्ग (मराठीमध्ये)",
    hawkerModeEn: "पथविक्रेता मोड (इंग्रजीमध्ये)",
    hawkerModeMr: "पथविक्रेता मोड (मराठीमध्ये)",
    hawkerModePrefixValidation: "पथविक्रेता मोड उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    hawkerModePrefixMrValidation: "पथविक्रेता मोड उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    hawkerModeValidation: "पथविक्रेता मोड आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    hawkerModeMrValidation: "पथविक्रेता मोड आवश्यक आहे (मराठीमध्ये) !!! ",
    hawkerTypeValidation: "पथविक्रेता प्रकार आवश्यक आहे !!!",
    noHawkingZoneMr: "न पथविक्रेता झोनचे नाव (मराठीमध्ये)",
    noHawkingZoneEn: "न पथविक्रेता झोनचे नाव (इंग्रजीमध्ये)",
    noHawkingZoneInfoMr: "न पथविक्रेता झोनचे माहिती  (मराठीमध्ये)",
    noHawkingZoneInfoEn: "न पथविक्रेता झोनचे माहिती  (इंग्रजीमध्ये)",
    gisIdValidation: "GIS आयडी आवश्यक आहे !!! ",
    zoneNameValidation: "झोन नाव निवड आवश्यक आहे !!! ",
    zoneNameValidation: "घोषणा आदेश आवश्यक आहे !!! ",
    declarationOrderValidation: "घोषणा आदेश आवश्यक आहे  !!! ",
    noHawkingZoneprefixEnValidation: "न पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!!",
    noHawkingZoneprefixMrValidation: "न पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे (मराठीमध्ये) !!!",
    noHawkingZoneEnValidation: "न पथविक्रेता झोनचे नाव (इंग्रजीमध्ये) !!!",
    noHawkingZoneMrValidation: "न पथविक्रेता झोनचे नाव (मराठीमध्ये) !!!",
    noHawkingZoneInfoEnValidation: "न पथविक्रेता क्षेत्र माहिती आवश्यक आहे (इंग्रजीमध्ये) !!!",
    noHawkingZoneInfoMrValidation: "न क्षेत्र माहिती आवश्यक आहे (इंग्रजीमध्ये) !!!",
    applicantPrefixMr: "अर्जदार उपसर्ग (मराठीमध्ये)",
    applicantPrefixEn: "अर्जदार उपसर्ग (इंग्रजीमध्ये)",
    applicantTypeMr: "अर्जदाराचा प्रकार (मराठीमध्ये)",
    applicantTypeEn: "अर्जदाराचा प्रकार (इंग्रजीमध्ये)",
    applicantSubTypeMr: "अर्जदार उपप्रकार (मराठीमध्ये)",
    applicantSubTypeEn: "अर्जदार उपप्रकार (इंग्रजीमध्ये)",
    subtypeValidation: "अर्जदार उपप्रकार आवश्यक आहे !!!",
    typeValidation: "अर्जदाराचा प्रकार आवश्यक आहे !!!",
    applicantPrefixValidation: " अर्जदार उपसर्ग आवश्यक आहे !!!",
    hawkingZoneWiseFacilitiesPrefixEn: "हॉकिंग झोननिहाय सुविधा उपसर्ग (इंग्रजीमध्ये)",
    hawkingZoneWiseFacilitiesPrefixMr: "हॉकिंग झोननिहाय सुविधा उपसर्ग (मराठीमध्ये)",
    facilitynameEn: "सुविधेचे नाव (इंग्रजीमध्ये)",
    facilitynameMr: "सुविधेचे नाव (मराठीमध्ये)",
    hawkingZoneWiseFacilitiesPrefixValidation: "हॉकिंग क्षेत्र उपसर्ग आवश्यक आहे !!!",
    hawkingZoneWiseFacilitiesPrefixMrValidation: "हॉकिंग क्षेत्र उपसर्ग आवश्यक आहे !!!",
    hawkigZoneValidation: "हॉकिंग क्षेत्र निवड आवश्यक !!!",
    facilitiesValidation: "सुविधेचे नाव आवश्यक आहे !!!",
    facilitiesMrValidation: "सुविधेचे नाव आवश्यक आहे !!!",
    hawkingDurationDailyFrom: "हॉकिंग कालावधी दररोज पासून",
    hawkingDurationDailyTo: "हॉकिंग कालावधी दैनिक ते",
    hawkingDurationDailyPrefixEn: "हॉकिंग कालावधी उपसर्ग (इंग्रजीमध्ये)",
    hawkingDurationDailyPrefixMr: "हॉकिंग कालावधी उपसर्ग (मराठीमध्ये)",
    businessSubType: "व्यवसाय उपप्रकार",
    businessType: "व्यवसाय प्रकार",
    hawkingDurationDailyPrefixValidation: "हॉकिंग कालावधी दैनिक उपसर्ग आवश्यक आहे !!!",
    hawkingDurationDailyFromValidation: "पासून दररोज हॉकिंग कालावधी आवश्यक आहे !!!",
    hawkingDurationDailyToValidation: "दररोज हॉकिंग कालावधी आवश्यक आहे !!!",
    businessTypeValidation: "व्यवसाय प्रकार निवड आवश्यक आहे !!!",
    businessSubTypeValidation: "व्यवसाय उपप्रकार निवड आवश्यक आहे !!!",
    businessSubTypePrefixEn: "व्यवसाय उपप्रकार उपसर्ग (इंग्रजीमध्ये)",
    businessSubTypePrefixMr: "व्यवसाय उपप्रकार उपसर्ग (मराठीमध्ये)",
    businessSubTypeEn: "व्यवसाय उपप्रकार (इंग्रजीमध्ये) ",
    businessSubTypeMr: "व्यवसाय उपप्रकार (मराठीमध्ये)",
    businessSubTypePrefixEnValidation: "व्यवसाय उपप्रकार उपसर्ग आवश्यक आहे !!!",
    businessSubTypePrefixMrValidation: "व्यवसाय उपप्रकार उपसर्ग आवश्यक आहे !!!",
    businessSubTypeEnValidation: "व्यवसाय उपप्रकार नाव आवश्यक आहे !!!",
    businessSubTypeMrValidation: "व्यवसाय उपप्रकार नाव आवश्यक आहे !!!",
    years: "वर्षे",
    months: "महिने",
    businessTypePrefixEn: "व्यवसाय उपसर्ग (इंग्रजीमध्ये)",
    businessTypePrefixMr: "व्यवसाय उपसर्ग (मराठीमध्ये)",
    businessTypeEn: "व्यवसाय (इंग्रजीमध्ये) ",
    businessTypeMr: "व्यवसाय (मराठीमध्ये)",
    businessTypePrefixEnValidation: "व्यवसाय उपसर्ग आवश्यक आहे !!!",
    businessTypePrefixMrValidation: "व्यवसाय उपसर्ग आवश्यक आहे !!!",
    businessTypeEnValidation: "व्यवसाय नाव आवश्यक आहे !!!",
    businessTypeMrValidation: "व्यवसाय नाव आवश्यक आहे !!!",
    renewalOfIssuanceOfHawkerLicense: "पथविक्रेता परवाना जारी करण्याचे नूतनीकरण",
    issuanceOfHawkerLicenseNumber: "फेरीवाला परवाना क्रमांक",
    siteVisitDate:"साइट भेट तारीख",
    siteVisitTime: "साइट भेट वेळ",
    streetVendorFullName: "रस्त्यावरील विक्रेत्याचे पूर्ण नाव",
  },
};
