export default {
  en: {
    //constants
    publicAud: "PUBLIC AUDITORIUM BOOKING AND BROADCAST MANAGEMENT",
    addAuditorium: "New Auditorium Entry",
    newAuditoriumEntry: "New Auditorium Entry",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    next: "Next",
    btnSaveText: "Save",
    srNo: "Sr No.",
    zone: "Zone",
    ward: "Ward",
    status: "Status",
    actions: "Actions",

    //equipment master
    equipmentCategory: "Equipment Category",
    equipmentName: "Equipment Name",
    equipmentNameMr: "Equipment Name (Marathi)",

    //auditorium master
    auditorium: "Auditorium Name",
    auditoriumMr: "Auditorium Name (Marathi)",
    address: "Address",
    addressMr: "Address (Marathi)",
    gisIdGeocode: "GISID Geocode",
    seatingCapacity: "Seating Capacity",
    startTime: "Start Time",
    endTime: "End Time",

    // equipment Category master
    equipmentCategoryNameEn: "Equipment Category Name",
    equipmentCategoryNameMr: "Equipment Category Name (Marathi)",

    //equipment Charges
    equipmentCharges: "Equipment Charges",
    auditorium: "Auditorium Name",
    equipment: "Equipment Name",
    equipmentCategory: "Equipment Category",
    equipmentCategoryMr: "Equipment Category (Marathi)",
    price: "Price",
    corporationRate: "Corporation Rate",
    multiplyingFactor: "Multiplying Factor",
    totalAmount: "Total Amount",

    //Check Auditorium availability
    auditorium: "Auditorium Name",
    selectSlot: "Select Slot",
    eventDate: "Event Date",
    selectEvent: "Select Event",

    //auditorium Events
    eventTimee: "Event Date",
    programEventDescription: "Program Event Description",
    eventHours: "Event Hours",
    eventNameEn: "Event Name",
    eventNameMr: "Event Name (Marathi)",

    //auditorium Events Charges
    auditoriumEventCharges: "Auditorium Event Charges",
    auditoriumEvents: "Auditorium Events",
    programEventDescription: "Program Event Description",
    depositAmount: "Deposit Amount",
    grandTotal: "Grand Total",
    eventTime: "Event Time",
    gstAmount: "GST Amount",
    rentAmount: "Rent Amount",
    securityAmount: "Security Guard Charges",
    totalAmount: "Total Amount",
    noOfDays: "No. Of Days",
    banner_boardCharges: "Banner/Board Charges",

    //Auditorium Schedule Master
    auditoriumSchedule: "Auditorium Schedule",
    shift: "Shift",
    auditorium: "Auditorium Name",
    eventTimeFrom: "Event Time From",
    eventTimeTo: "Event Time To",
    slotDescription: "Remark",

    //Rate Chart Master
    rateChartMaster: "Rate Chart Master",
    eventName: "Event Name",
    chargeName: "Charge Name",
    fromDate: "From Date",
    toDate: "To Date",
    range: "Discount",
    price: "Price",

    //transactions
    //Auditorium Booking online process

    auditoriumBooking: "Auditorium Booking",
    selectAuditorium: "Select Auditorium",
    auditoriumBookingNumber: "Auditorium Booking Number",
    bookingForPCMC: "Booking For PCMC",
    bookingForOtherVendor: "Booking For Other Vendor",
    organizationName: "Organization Name",
    title: "Title",
    flat_buildingNo: "Flat Building No.",
    organizationOwnerFirstName: "Organization Owner First Name",
    organizationOwnerMiddleName: "Organization Owner Middle Name",
    organizationOwnerLastName: "Organization Owner Last Name",
    buildingName: "Building Name",
    roadName: "Road Name",
    landmark: "Landmark",
    pinCode: "Pin Code",
    aadhaarNo: "Aadhaar Number",
    landline: "Landline",
    mobile: "Mobile",
    emailAddress: "Email Address",
    messageDisplay: "Message Display",
    eventDetails: "Event Details",
    eventDate: "Event Date",
    eventDay: "Event Day",
    eventTimeFrom: "Event Time From",
    eventTimeTo: "Event Time To",
    depositAmount: "Deposit Amount",
    payDepositAmount: "Pay Deposit Amount",
    rentAmount: "Rent Amount",
    payRentAmount: "Pay Rent Amount",
    depositReceipt: "Deposit Receipt",
    extendedRentAmount: "Extended Rent Amount",
    rentReceipt: "Rent Receipt",
    managersDigitalSignature: "Managers Digital Signature",
    termsAndConditions: "Terms And Conditions",
    ecsFormDetails: "ECS Form Details",
    bankAccountHolderName: "Bank Account Holder Name",
    bankAccountNumber: "Bank Account Number",
    typeOfBankAccount: "Type Of Bank Account",
    bankName: "Bank Name",
    bankAddress: "Bank Address",
    ifscCode: "IFSC Code",
    micrCode: "MICR Code",
    remark: "Remark",

    //auditorium booking cancellation
    bookingCancellation: "Booking Cancellation",
    selectAuditorium: "Auditorium",
    selectService: "Service",
    auditoriumBookingNumber: "Auditorium Booking Number",
    cancelByApplicant_Vendor: "Cancel by Applicant/Vendor",
    cancelByDepartment: "Cancel by Department",
    reasonForCancellation: "Reason for cancellation",
    searchByAuditoriumBookingNumber: "Search By Auditorium Booking Number",
    returnAmountDetails: "Return Amount Details",
    shownAnAmountToBeReturnedAfterBookingCancellation:
      "Shown an amount to be returned after booking cancellation",
    amountToBeReturned: "Amount to be returned",
    bookingCancellationDetails: "Booking Cancellation Details",
    budgetingUnit: "Budgeting Unit",
    notesheet_ReferenceNumber: "Notesheet / Reference number",
    billDate: "Bill Date",
    remark: "Remark",

    //depositeRefundProcessing
    searchByAuditoriumBookingNumber: "Search By Auditorium Booking Number",
    attachDocuments: "Attach Documents",
    depositRefundBillDetails: "Deposit Refund Bill Details",
    ecsPayment: "ECS Payment",
    depositeReceiptNo: "Deposite Receipt Number",
    depositeAmount: "Deposite Amount",
    depositeReceiptDate: "Deposite Receipt Date",
    bankAccountNo: "Bank Account Number",

    //shift master
    shiftTitle: "Shift Master",
    timeSlot: "Shift Hours",
    shift: "Shift Name",

    durationOfApplicationDistributionAndAcceptance: "Duration Of Application Distribution And Acceptance",
    holidayWeekendSchedule: "Holiday Weekend Schedule",

    //Reports
    //auditoriumBooking
    applicationDate: "Application Date",
    applicationNumber: "Application Number",
    loiNo: "LOI No",
    applicantName: "Applicant Name",
    applicantMobile: "Applicant Mobile",
    auditorium: "Auditorium",
    organizationName: "Organization Name",
    deposite: "Deposite",
    rent: "Rent",
    totalAmount: "Total Amount",
    remarks: "Remarks",
    downloadExcel: "DOWNLOAD EXCEL",
    downloadPdf: "DOWNLOAD PDF",
    cancel: "Cancel",
    submit: "Submit",
    process: "Process",
  },
  mr: {
    //constants
    publicAud: "पब्लिक ऑडिटोरियम बुकिंग आणि ब्रॉडकास्ट व्यवस्थापन",
    addAuditorium: "नवीन सभागृह नोंदणी",
    newAuditoriumEntry: "नवीन सभागृह नोंदणी",
    add: "नवीन नोंदणी",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    next: "पुढे",
    btnSaveText: "जतन करा",
    srNo: "अनु क्र",
    zone: "झोन",
    ward: "प्रभाग",
    status: "स्थिती",
    actions: "क्रिया",

    //equipment master
    equipmentCategory: "उपकरणे श्रेणी",
    equipmentName: "उपकरणाचे नाव",
    equipmentNameMr: "उपकरणाचे नाव मराठी",

    //Auditorium master
    auditorium: "सभागृहाचे नाव",
    auditoriumMr: "सभागृहाचे नाव (मराठी)",
    address: "पत्ता",
    addressMr: "पत्ता (मराठी)",
    gisIdGeocode: "जीएसआय आयडी जिओकोड",
    seatingCapacity: "आसन क्षमता",
    startTime: "सुरवातीची वेळ",
    endTime: "समाप्तीचा कालावधी",

    // equipment Category master
    equipmentCategoryNameEn: "उपकरण श्रेणीचे नाव",
    equipmentCategoryNameMr: "उपकरण श्रेणीचे नाव (मराठी)",

    //equipment Charges
    equipmentCharges: "उपकरणे शुल्क",
    auditorium: "सभागृहाचे नाव",
    equipment: "उपकरणाचे नाव",
    equipmentCategory: "उपकरणे श्रेणी",
    equipmentCategoryMr: "उपकरण श्रेणी (मराठी)",
    price: "किंमत",
    corporationRate: "महानगरपालिका दर",
    multiplyingFactor: "गुणाकार घटक",
    totalAmount: "एकूण रक्कम",

    //Check Auditorium availability
    auditorium: "सभागृहाचे नाव",
    selectSlot: "स्लॉट निवडा",
    eventDate: "कार्यक्रमाची तारीख",
    selectEvent: "कार्यक्रम निवडा",

    //auditorium Events
    eventTimee: "कार्यक्रमाची तारीख",
    programEventDescription: "कार्यक्रमाचे वर्णन",
    eventHours: "कार्यक्रमाचे तास",
    eventNameEn: "कार्यक्रमाचे नाव",
    eventNameMr: "कार्यक्रमाचे नाव (मराठी)",

    //auditorium Events Charges
    auditoriumEventCharges: "सभागृह कार्यक्रम शुल्क",
    auditoriumEvents: "सभागृह कार्यक्रम",
    programEventDescription: "कार्यक्रमाचे वर्णन",
    depositAmount: "ठेव रक्कम",
    grandTotal: "एकूण",
    eventTime: "कार्यक्रमाची वेळ",
    gstAmount: "जीएसटी रक्कम",
    rentAmount: "भाडे रक्कम",
    securityAmount: "सुरक्षा रक्कम",
    totalAmount: "एकूण रक्कम",
    noOfDays: "दिवसांची संख्या",
    banner_boardCharges: "बॅनर/बोर्ड शुल्क",

    //Auditorium Schedule Master
    auditoriumSchedule: "सभागृहाचे वेळापत्रक",
    shift: "शिफ्ट",
    auditorium: "सभागृहाचे नाव",
    eventTimeFrom: "पासून कार्यक्रम वेळ",
    eventTimeTo: "कार्यक्रमाची वेळ पर्यंत",
    slotDescription: "टिप्पणी",

    //Rate Chart Master
    rateChartMaster: "दर तक्ता मास्टर",
    eventName: "कार्यक्रमाचे नाव",
    chargeName: "शुल्क नाव",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    range: "सवलत",
    price: "किंमत",

    //transactions
    //Auditorium Booking online process

    auditoriumBooking: "प्रेक्षागृह बुकिंग",
    selectAuditorium: "प्रेक्षागृह निवडा",
    auditoriumBookingNumber: "प्रेक्षागृह बुकिंग क्रमांक",
    bookingForPCMC: "पीसीएमसी साठी बुकिंग",
    bookingForOtherVendor: "इतर विक्रेत्यासाठी बुकिंग",
    organizationName: "संस्थेचे नाव",
    title: "शीर्षक",
    flat_buildingNo: "फ्लॅट इमारत क्र.",
    organizationOwnerFirstName: "संस्थेच्या मालकाचे पहिले नाव",
    organizationOwnerMiddleName: "संस्थेच्या मालकाचे मधले नाव",
    organizationOwnerLastName: "संस्थेच्या मालकाचे आडनाव",
    buildingName: "इमारतीचे नाव",
    roadName: "रस्त्याचे नाव",
    landmark: "लँडमार्क",
    pinCode: "पिन कोड",
    aadhaarNo: "आधार क्रमांक",
    landline: "लँडलाइन",
    mobile: "मोबाईल",
    emailAddress: "ईमेल",
    messageDisplay: "संदेश प्रदर्शन",
    eventDetails: "कार्यक्रम तपशील",
    eventDate: "कार्यक्रमाची तारीख",
    eventDay: "कार्यक्रमाचा दिवस",
    eventTimeFrom: "पासून कार्यक्रम वेळ",
    eventTimeTo: "कार्यक्रमाची वेळ पर्यंत",
    depositAmount: "ठेव रक्कम",
    payDepositAmount: "ठेव रक्कम भरा",
    rentAmount: "भाडे रक्कम",
    payRentAmount: "भाड्याची रक्कम द्या",
    depositReceipt: "ठेव पावती",
    extendedRentAmount: "विस्तारित भाडे रक्कम",
    rentReceipt: "भाड्याची पावती",
    managersDigitalSignature: "व्यवस्थापकांची डिजिटल स्वाक्षरी",
    termsAndConditions: "नियम आणि अटी",
    ecsFormDetails: "ईसीएस फॉर्म तपशील",
    bankAccountHolderName: "बँक खातेधारकाचे नाव",
    bankAccountNumber: "बँक खाते क्रमांक",
    typeOfBankAccount: "बँक खात्याचा प्रकार",
    bankName: "बँकेचे नाव",
    bankAddress: "बँकेचा पत्ता",
    ifscCode: "आयएफएससी कोड",
    micrCode: "एमआयसीआर कोड",
    remark: "शेरा",

    //auditorium booking cancellation
    bookingCancellation: "बुकिंग रद्द करणे",
    selectAuditorium: "प्रेक्षागृह",
    selectService: "सेवा",
    auditoriumBookingNumber: "प्रेक्षागृह बुकिंग क्रमांक",
    cancelByApplicant_Vendor: "अर्जदार/विक्रेत्याद्वारे रद्द करा",
    cancelByDepartment: "विभागाकडून रद्द करा",
    reasonForCancellation: "रद्द करण्याचे कारण",
    searchByAuditoriumBookingNumber: "प्रेक्षागृह बुकिंग नंबर द्वारे शोधा",
    returnAmountDetails: "परतावा रक्कम तपशील",
    shownAnAmountToBeReturnedAfterBookingCancellation: "बुकिंग रद्द केल्यानंतर परत करावयाची रक्कम दर्शविली",
    amountToBeReturned: "परत करावयाची रक्कम",
    bookingCancellationDetails: "बुकिंग रद्दीकरण तपशील",
    budgetingUnit: "बजेटिंग युनिट",
    notesheet_ReferenceNumber: "नोटशीट / संदर्भ क्रमांक",
    billDate: "बिल तारीख",
    remark: "शेरा",

    //depositeRefundProcessing
    searchByAuditoriumBookingNumber: "ऑडिटोरियम बुकिंग नंबर द्वारे शोधा",
    attachDocuments: "कागदपत्रे संलग्न करा",
    depositRefundBillDetails: "ठेव परतावा बिल तपशील",
    ecsPayment: "ईसीएस पेमेंट",
    depositeReceiptNo: "जमा पावती क्रमांक",
    depositeAmount: "ठेव रक्कम",
    depositeReceiptDate: "जमा पावतीची तारीख",
    bankAccountNo: "बँक खाते क्रमांक",

    //shift master
    shiftTitle: "शिफ्ट मास्टर",
    timeSlot: "शिफ्ट तास",
    shift: "शिफ्ट नाव",

    durationOfApplicationDistributionAndAcceptance: "अर्ज वितरण आणि स्वीकृती कालावधी",
    holidayWeekendSchedule: "सुट्टीचे शनिवार व रविवार वेळापत्रक",

    //Reports
    //auditoriumBooking
    applicationDate: "अर्जाची तारीख",
    applicationNumber: "अर्ज क्रमांक",
    loiNo: "एलओआय क्र",
    applicantName: "अर्जदाराचे नाव",
    applicantMobile: "अर्जदार मोबाईल",
    auditorium: "सभागृह",
    organizationName: "संस्थेचे नाव",
    deposite: "ठेव",
    rent: "भाडे",
    totalAmount: "एकूण रक्कम",
    remarks: "शेरा",
    downloadExcel: "एक्सेल डाउनलोड करा",
    downloadPdf: "पीडीएफ डाउनलोड करा",
    cancel: "रद्द करा",
    submit: "प्रस्तुत",
    process: "प्रक्रिया",
  },
};
