export default {
  en: {
    mediumPrefix: "Medium Prefix",
    nameOfMedium: "Name of Medium",
    nameOfMediumMr: "Name of Medium in Marathi",
    infoTransferMediumMaster: "Medium Master",
    add: "Add",
    srNo: "Sr.No",
    actions: "Actions",
    address: "Address",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    rtiApplication: "RTI Application",
    applicantFirstName: "Applicant First Name",
    applicantMiddleName: "Applicant Middle Name",
    applicantLastName: "Applicant Last Name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    pinCode: "Pincode",
    contactDetails: "Contact Details",
    emailId: "Email Id",
    education: "Education",
    literate: "Literate",
    illiterate: "Illiterate",
    wardKey: "Ward",
    areaKey: "Area",
    zoneKey: "Zone",
    departmentKey: "Department",
    subDepartmentKey: "Sub department",
    isApplicantBelowToPovertyLine: "Is applicant below to poverty line?",
    bplCardNo: "BPL Card Number",
    yearOfIssues: "Year of Issues",
    issuingAuthority: "Issuing Authority",
    informationSubject: "Information Subject",
    fromDate: "From Date(Related Information)",
    toDate: "To Date(Related Information)",
    description: "Description of required Information",
    yes: "Yes",
    no: "No",
    requiredInfoDeliveryDetails: "Required Information Delivery Details",
    byPost: "By Post",
    byHand: "By Hand",
    softCopy: "Soft Copy/ By Email",
    departmentKey: "Department Name",
    subDepartmentKey: "Sub Department Name",


    rtiAppeal: "RTI Appeal",
    applicationNo: "Application No",
    search: "Search",
    descInfoOfOfficer: "Description of Information officer",
    dateOfOfficialorderAgainstAppeal: "Date of Official order against the appeal",
    descriptionOfInfo: "Description of Information",
    reqInfoSubjectAndDesc: "Required Information subject and description",
    concernOfficerDeptnmWhoseInfoRequired: "Concern office or department name whose information required",
    rtiFileDate: "RTI File Date",

    requiredInfoPurpose: "Required Information Purpose",
    reasonForAppeal: "Reason for Appeal",
    paymentModeKey: "Payment Mode",
    paymentAmount: "Application Charges",
    status: "Status",
    rtiApplicationList: "RTI Application List",
    ViewrtiApplication: "View RTI Application",

    appealApplicationNo: "Appeal Application No",
    rtiAppealList: "RTI Appeal List",
    appealFileDate: "Appeal File Date",
    viewrtiAppeal: "View RTI Appeal",
    currentStatus: "Current Status",
    isLOIGenerated: "Is Information Charges/LOI Generated?",
    payment: "Payment Done",
    saveAndPay: "Save and Pay",
    completeApplication: "Complete status of Application",
    loiGenerate: "Information Charges",
    closeModal: "Close",
    loiGenerateBtn: "LOI Generate",
    serviceName: "Service Name",
    noOfPages: "No of Pages",
    chargeType: "Charge Type",
    amount: "Amount",
    totalAmount: "Total Amount",
    remark: "Remark",
    viewLoi: "View Letter of Intent",
    print: "Print",
    makePayment: "Make a Payment",
    applicationReceivedBy: "Application Received By",
    cfcuser: "CFC User",
    citizenuser: "Citizen User",
    pcmcportal: "PCMC Portal",
    aaplesarkar: "Aaple Sarkar",
    ratePerPage: "Rate Per Page",
    fileSize: " File size must be less than 2MB",
    fileExtension: "Attach Only .JPG, .PNG, .JPEG  and .PDF files",
    cancel: "Cancel",
    fileUpload: "File Upload",
    addDoc: " ADD DOCUMENTS",
    uploadDoc: "UPLOAD DOCUMENT/IMAGE",
    informationRemark: "Information Ready Remark",
    infoReady: "Information Ready",
    infoPages: "Information Pages",
    selectedReturnMedia: "Selected Return Media",
    infoReadyDate: "Information Ready Date",
    completeDate: "Completed Date",
    completeRemark: "Complete Remark",
    informationReturnMedia: "Information Return Media",
    hearingSchedule: "Hearing Schedule",
    decisionEntry: "Decision Entry",
    Tnc: "ACCEPT TERMS AND CONDITION",
    applicantName: "Applicant Name",
    appealNo: "Appeal No",
    scheduleDate: "Schedule Date",
    scheduleTime: "Schedule Time",
    venueForHearing: "Venue for Hearing",
    subject: "Subject",
    rtiApplicationNO: "RTI Application No",

    decisiontakenInHearing: "Decision taken in hearing",

    decisionStatus: "Decision Status by department",
    decisionOrderAttach: "Decision order upload",
    updloadScanInfoDelivered: "Upload Scan Copy of Information Delivered",
    hearingReschedule: "Hearing Reschedule",
    completeAppeal: "Complete Status of Appeal",
    decisionDetails: "Decision Details",
    documents: "Documents",
    completeDoc: "Complete Documents",
    RTIApplicationdoc: "RTI Application Documents",
    RTIAppealdoc: "RTI Appeal Documents",
    forwardApplication: "Forward/Transfer Application",
    currentdept: "Current department",
    currentSubDept: "Current sub department",
    forwardApplication: "Forward Application",
    forwardToDept: "Forward to department",
    forwardTosubDept: "Forward to sub department",
    downloadLoiReceipt: "Download Service Acceptance Letter Receipt",
    addInfo: "Additional Information",
    downloadAcknowldgement: "Download Acknowledgement",
    print: "Print",
    pimpariChinchwadMaha: "Pimpri Chinchwad Municipal Corporation",
    appAcknowldgement: "Application Acknowledgement",
    ackDear: "Dear",
    ackpcmcthanku: "Thank you for using PCMC Pimpri Chinchwad Citizen Service Portal !!",
    ackshortDesc:
      "Your application for Right To Information under PCMC of pune has been successfully submitted.",
    ackRTIAppealshortDesc:
      "Your application for Right To Information Appeal under PCMC of pune has been successfully submitted.",

    ackApplicationSummery: "Application Summary",
    applicationNo: "Application No",
    dateofApplication: "Date of the Application",
    ackplzContactNearestOperator:
      "For any query please contact your nearest operator or the following contact details:",
    ackpcmcAddress: "Mumbai Pune Highway Pimpri Pune 411-018",
    ackPcmcphNo: "Phone Number:91-020-2742-5511/12/13/14",
    ackstateCountry: "Maharashtra, India",
    applicantAddress: "Applicant Address",
    other: "Other",
    rti: "RTI",
    no1: "1)",

    chargeNm: "Charge Name",
    loiNo: "LOI NO",
    rtiApplicationAmt: "For your RTI service on Citizen Seva Portal please your amount Rs",
    determineandPayAmt: "Determine and pay the amount/charge for the service rendered.",
    contactNearestpcmcDivisionalOffice:
      "Or visit the nearest Pimpri Chinchwad Municipal Corporation Divisional Office.",
    serviceAcceptance: "Service Acceptance Letter",
    isApplicationMultiDept: "Is it application under multi department?",
    addDepartment: "Add Department",
    parentRemark: "Parent Remark",
    forwardRemark: "Forward Remark",
    applicationType: "Application Type",

    welcomeToTheDashboard: "Welcome To The Dashboard",
    dashboardTotalCount: "Total Applications",
    dashboardInProgress: "In Progress",
    dashboardLoiGenerated: "Loi Generated",
    dashboardInfoReady: "Information Ready",
    dashboardCompleted: "Completed Application",
    dashboardHearingScheduled: "Hearing Scheduled",

    dashboardTotalAppealCount: "Total Appeal",
    dashboardCompletedAppeal: "Completed Appeal",

    goToAppeal: "Go To Appeal",

    applicationinfoReady: "Application Information Ready",
    appealInfoReady: "Appeal Information Ready",

    ///////////////// FOR REPORTS ADDED BY ANWAR ANSARI /////////
    rtiApplicationRegister: "RTI APPLICATION REGISTER",
    applicationNumber: "Application Number",
    fullName: "Full Name",
    descriptioniOfInformationRequired: "Description Of Information Required",
    dateOfOrderAgainstAppeal: "Date Of Order Against Appeal",
    descriptionOfInformation: "Description Of Information",
    concernDepartmentOrOffice: "Concern Department Or Office",
    reasonOfAppeal: "Reason Of Appeal",
    informationPurpose: "Information Purpose",

    toDateR: "To Date",
    fromDateR: "From Date",

    submit: "Submit",
    downloadEXCELL: "Download Excel",
    downloadPDF: "Download Pdf",
    cancel: "Cancel",
    //////////////////////////////////////////////
    rtiApplicationDashboard: "RTI APPLICATION DASHBOARD",
    rtiAppealRegister: "RTI APPEAL REGISTER",
    subjectName: "Subject Name",
    systemEntryDate: "System Entry Date",
    wards: "Ward",
    bplCardNumber: "BPL Card Number",
    isApplicantBPL: "Is Applicant BPL",
    deptName: "Department Name",
    /////////////////////////////////////////////////
    vivaranPatra01: "Vivaran Patra_01",
    vivaranPatra02: "Vivaran Patra_02",
    vivaranPatra03: "Vivaran Patra_03",
    vivaranPatra04: "Vivaran Patra_04",
    vivaranPatra05: "Vivaran Patra_05",

    monthName: "Month",
    count: "Count",

    periodOfRelatedInformation: "Period Of Related Information",

    year: "Year",
    descriptionOfInformationOfficer: "Description Of Information Officer",

    serialNumber: "Serial Number",
    deptWiseCollection: "DEPARTMENT WISE COLLECTION",
    strFromDate: "From Date",
    strToDate: "To Date",
    total: "Total",
    totalApplication: "Total Application",
    grandTotal: "Grand Total",
    requiredInformationByPostOrPersonallly: "Required Information By Post Or Personallly",
    applicationDate: "Application Date",
    departmentName: "Department Name",
    fileNm: "File Name",
    fileType: "File Type",
    transferRemark: "Transfer Remark",
    viewAttach: "View Attachment",
    rtiDueDate: "RTI Due Date",
    totalNoOfDays: "Total Numbers of Days",


    //////////////////////rtiapplication wise collection label changes by shubham/////////////////
    appWiseCollection: "APPLICATION WISE COLLECTION",
    applicationName: "Application Name",
    serviceAcceptanceCharges: "Service Acceptance Charges",
    serviceCharges: "Service Charges",
    lastMonthPendingAppCount: "Last Month Pending application Count",
    reportingMonthRecivedAppConunt: "In Reporting Month's received application count",
    reportingMonthClearanceConunt: "In Reporting Month's application clearance count",
    infoDeleverdRTIAppCount: "Information Delivered as per RTI Application Count",
    infoRejectedRTIAppCount: "Information Rejected as per RTI Application Count",
    pendingAppCount: "Pending Application Count",
    reportingMonthRecivedAppealConunt: "In Reporting Month's received appeal count",
    reportingMonthAppealClearanceConunt: "In Reporting Month's appeal clearance count",
    appealAcceptedConunt: "Appeal Accepted Count",
    appealRejectedConunt: "Appeal Rejected Count",
    pendingAppealConunt: "Pending Appeal Count",
    lastMonthPendingAppealCount: "Last Month Pending Appeal Count",
    reportingMonthDeleveredAppealCount: "In Reporting Months Delivered Appeal Count",
    pendingAppealCount: "Pending Appeal Count",
    searchArea: "Search Area",
    getDetails: "Get Details",
    results: "Results",
    attachDoccument: "Attach document",
    rtiTermsndTitle: "Pimpri Chinchwad Municipal Corporation, Pimpri-411018",
    childDeptTitle: "Child Application Departments",
    rtiAct2005: "RTI Act, 2005 ",
    guidelineOfRti: "GUIDELINES FOR USE OF RTI ONLINE PORTAL",
    guideline1: '1)	This Web Portal can be used by Indian citizens to file RTI application online and also to make payment for RTI application online. First appeal can also be filed online.',
    guideline2: '2) An applicant who desires to obtain any information under the RTI Act can make a request through this Web Portal to the Pimpri Chinchwad Mahanagarpalika.',
    guideline3: `3) On clicking at "Submit Request", the applicant has to fill the required details on the page that will appear.`,
    guideline4: "4) The fields marked * are mandatory while the others are optional ",
    guideline5: '5) The text of the application may be written at the prescribed column.',
    guideline6: '6) At present, the text of an application that can be uploaded at the prescribed column is confined to 3000 characters only.',
    guideline7: '7) Only alphabets A-Z a-z number 0-9 and special characters, . - _ ( ) / @ : & ? \ % is allowed in Text for RTI Request application.',
    guideline8: '8) In case an application contains more than 3000 characters, it can be uploaded as an attachment, by using column "Supporting document". ',

    guideline9: "9) Do not upload Aadhar Card or PAN Card or any other personal Identification (Except BPL Card).",
    guideline10: "10) PDF file name should not have any blank spaces.",
    guideline11: '11) After filling the first page, the applicant has to click on "Make Payment" to make payment of the prescribed fee.',
    guideline12: '12) The applicant can pay the prescribed fee through the following modes: (a)Internet banking; (b) Using credit/debit card of Master/Visa; c) Using RuPay Card.',
    guideline13: '13) Fee for making an application is as prescribed in the RTI Rules, 2012.',
    guideline14: '14) After making payment, an application can be submitted.',
    guideline15: '15) After making payment, if applicant didn’t receive the registration number then applicant is advised to wait for the 24-48 working hours as registration number will be generated after reconciliation. Please do not make additional attempt to make payment again. If it is not generated within 24-48 hours kindly send an e-mail at help (sarthi@pcmcindia.gov.in), (egov@pcmcindia.com) with transaction details.',
    guideline16: '16) No RTI fee is required to be paid by any citizen who is below poverty line as per RTI Rules, 2012. However, the applicant must attach a copy of the certificate issued by the appropriate government in this regard, along with the application.',
    guideline17: '17) On submission of an application, a unique registration number would be issued, which may be referred by the applicant for any references in future.',
    guideline18: '18) The application filed through this Web Portal would reach electronically to the "Nodal Officer" of concerned Ministry/Department, who would transmit the RTI application electronically to the concerned PIO.',
    guideline19: '19) In case additional fee is required representing the cost for providing information, the PIO would intimate the applicant through this portal. This intimation can be seen by the applicant through Status Report or through his/her e-mail alert.',
    guideline20: '20) For making an appeal to the first Appellate Authority, the applicant has to click at "Submit First Appeal" and fill up the page that will appear.',


    guideline21: '21) The registration number of original application has to be used for reference.',
    guideline22: '22) As per RTI Act, no fee has to be paid for first appeal.',
    guideline23: '23) The applicant/the appellant should submit his/her mobile number to receive SMS alert.',
    guideline24: '24) Status of the RTI application/first appeal filed online can be seen by the applicant/appellant by clicking at "View Status".',
    guideline25: '25) 21	All the requirements for filing an RTI application and first appeal as well as other provisions regarding time limit, exemptions etc., as provided in the RTI Act, 2005 will continue to apply',


    mediumPrefReq: "Medium Prefix is Required !!!",
    nmOfMediumReq: "Name of Medium is Required !!!",
    nmOfMediumReqMr: "Name of Medium in Marathi is Required !!!",

    mediumMinLeng: "Name of medium must be at least 2 character",
    mediumMaxLen: "Name of medium is too long",


    mediumMinLengMr: "Name of medium in marathi must be at least 2 character",
    mediumMaxLenMr: "Name of medium in marathi is too long",

    mediumPrefMinLeng: "Medium Prefix must be at least 2 character",
    mediumPrefMaxLen: "Medium Prefix is too long",


    decisionMinLen: "Decision details must be at least 20 character",
    decisionMaxLen: "Decision details is too long",
    decisionReq: "Decision taken in hearing is Required !!!",
    decisionStatusReq: "Decision status is Required !!!",
    remarkReq: "Remark is Required !!!",
    venueReq: "Venue is Required !!!",
    chargeTypeReq: "Charge Type is Required !!!",

    educationReq: "Education is Required !!!",
    areaNmReq: "Area Name is Required !!!",
    wardNmReq: "Ward Name is Required !!!",
    zoneNmReq: "Zone Name is Required !!!",
    deptReq: "Department Name is Required !!!",
    isBplReq: "Is applicant below to poverty line is Required !!!",
    addReq: "Address is Required !!!",
    descriptionReq: "Descrition of required Information is Required !!!",
    reasonForAppealReq: "Reason for appeal is Required !!!",


    appliFirstNmReq: "Applicant First Name is Required !!!",
    appliMiddNmReq: "Applicant Middle Name is Required !!!",
    appliLastNmReq: "Applicant Last Name is Required !!!",
    genderReq: "Gender is Required !!!",
    pincodeReq: 'Pincode is Required !!!',
    inCorrectMsg: "Incorrect format",
    emailReq: "Email Id is Required !!!",
    contactReq: "Contact Details is Required !!!",
    attachDate: "Attached Date",

    uploadTitle: "Upload",
    descriptionMaxLen: "Description is exceeding limit",
    addressMaxLen: "Address is exceeding limit",
    reasonMaxLen:"Reason of appeal is exceeding limit",
    remarkMaxLen:"Remark is exceeding limit",
    venueMaxLen:"Venue is exceeding limit",
    decisionStatussMaxLen:"Decision status is exceeding limit"
  },

  mr: {
    mediumPrefix: "माध्यम उपसर्ग",
    nameOfMedium: "माध्यमाचे नाव",
    nameOfMediumMr: "माध्यमाचे नाव मराठी",
    infoTransferMediumMaster: "माध्यम मास्टर",
    srNo: "अनु क्रमांक",
    actions: "क्रिया",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    rtiApplication: "आरटीआय अर्ज",
    applicantFirstName: "अर्जदाराचे प्रथम नाव",
    applicantMiddleName: "अर्जदाराचे मधले नाव",
    applicantLastName: "अर्जदाराचे आडनाव",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    pinCode: "पिन कोड",
    contactDetails: "संपर्काची माहिती",
    emailId: "ई-मेल आयडी",
    education: "शिक्षण",
    literate: "साक्षर",
    illiterate: "निरक्षर",
    // wardKey: "प्रभाग",
    areaKey: "क्षेत्र",
    wardKey: "प्रभाग",
    zoneKey: "झोन",
    departmentKey: "विभाग",
    subDepartmentKey: "उपविभाग",
    isApplicantBelowToPovertyLine: "अर्जदार दारिद्र्य रेषेखालील आहे का?",
    bplCardNo: "बीपीएल कार्ड क्र",
    yearOfIssues: "कार्ड वितरीत वर्ष",
    issuingAuthority: "कार्ड मान्यता अधिकारी यांचे नाव",
    informationSubject: "माहितीचा विषय",
    fromDate: "तारखेपासून (संबंधित माहिती)",
    toDate: "तारखेपर्यंत (संबंधित माहिती)",
    description: "आवश्यक असलेल्या माहितीचे वर्णन",
    yes: "होय",
    no: "नाही",
    requiredInfoDeliveryDetails: "आवश्यक माहिती वितरण तपशील",
    byPost: "पोस्टाने",
    byHand: "हाताने",
    softCopy: "सॉफ्टकॉपी /ई- मेलद्वारे",
    address: "पत्ता",
    departmentKey: "विभागाचे नाव",
    subDepartmentKey: "उपविभागाचे नाव",


    rtiAppeal: "आरटीआय आवाहन",
    applicationNo: "अर्ज क्र",
    search: "शोधा",
    descInfoOfOfficer: "माहिती अधिकाऱ्याचा तपशील",
    dateOfOfficialorderAgainstAppeal: "ज्या आदेशाविरुद्ध अपिल केले तो आदेश मिळाल्याची दिनांक",

    descriptionOfInfo: "माहितीचा तपशील",
    reqInfoSubjectAndDesc: "आवश्यक असलेल्या माहितीचे स्वरूप आणि विषय",
    concernOfficerDeptnmWhoseInfoRequired:
      "माहिती ज्या कार्यालयाशी किंवा विभागाशी संबंधित विभागाशी आहे त्याचे नाव",
    requiredInfoPurpose: "ज्यासाठी माहिती आवश्यक आहे ते प्रयोजन",
    reasonForAppeal: "अपिलाचे कारण",
    paymentModeKey: "पेमेंट मोड",
    paymentAmount: "अर्ज शुल्क",
    rtiFileDate: "आरटीआय फाइलची तारीख",
    status: "स्थिती",
    rtiApplicationList: "आरटीआय अर्ज यादी",
    ViewrtiApplication: "आरटीआय अर्ज पहा",

    appealApplicationNo: "अपील अर्ज क्र",
    rtiAppealList: "आरटीआय अपील यादी",
    appealFileDate: "अपील फाइलची तारीख",
    viewrtiAppeal: "आरटीआय अपील पहा",
    currentStatus: "वर्तमान स्थिती",
    loiGenerate: "माहिती शुल्क",
    isLOIGenerated: "माहिती शुल्क/LOI व्युत्पन्न करणे आवश्यक आहे?",
    payment: "पैसे भरा",
    saveAndPay: "जतन करा आणि पैसे द्या",
    completeApplication: "अर्जाची संपूर्ण स्थिती",
    closeModal: "बंद करा",
    loiGenerateBtn: "loi व्युत्पन्न करा",
    serviceName: "सेवेचे नाव",
    noOfPages: "पृष्ठांची संख्या",
    chargeType: "चार्ज प्रकार",
    amount: "रक्कम",
    totalAmount: "एकूण रक्कम",
    remark: "टिप्पणी",
    completeRemark: "पूर्ण टिप्पणी",

    viewLoi: "हेतू पत्र पहा",
    print: "छापणे",
    makePayment: "पैसे भरा",
    applicationReceivedBy: "द्वारे अर्ज प्राप्त झाला",
    cfcuser: "cfc वापरकर्ता",
    citizenuser: "नागरिक वापरकर्ता",
    pcmcportal: "PCMC पोर्टल",
    aaplesarkar: "आपल सरकार",
    ratePerPage: "प्रति पृष्ठ दर",
    fileSize: " फाइल आकार 2MB पेक्षा कमी असणे आवश्यक आहे",
    fileExtension: "फक्त .JPG, .PNG, .JPEG आणि .PDF फाइल्सना अनुमती द्या",
    cancel: "रद्द करा",
    fileUpload: "फाइल अपलोड",
    addDoc: " दस्तऐवज जोडा",
    uploadDoc: "दस्तऐवज/इमेज अपलोड करा",
    informationRemark: "माहिती तयार टिप्पणी",
    inforReady: "माहिती तयार",
    infoPages: "माहिती पृष्ठे",
    selectedReturnMedia: "माहिती रिटर्न मीडिया",

    infoReadyDate: "माहिती तयार तारीख",
    completeDate: "पूर्ण तारीख",
    informationReturnMedia: "माहिती रिटर्न मीडिया",
    hearingSchedule: "सुनावणीचे वेळापत्रक",
    decisionEntry: "निर्णय प्रवेश",

    applicantName: "अर्जदाराचे नाव",
    appealNo: "अपील क्र",
    scheduleDate: "शेड्यूल तारीख",
    scheduleTime: "वेळ शेड्यूल करा",
    venueForHearing: "सुनावणीचे ठिकाण",

    subject: "विषय",
    rtiApplicationNO: "आरटीआय अर्ज क्र",
    decisiontakenInHearing: "सुनावणीत घेतलेला निर्णय",

    decisionStatus: "विभागानुसार निर्णयाची स्थिती",
    decisionOrderAttach: "निर्णय ऑर्डर अपलोड",
    updloadScanInfoDelivered: "वितरित केलेल्या माहितीची स्कॅन प्रत अपलोड करा",
    hearingReschedule: "सुनावणीचे पुन्हा वेळापत्रक",
    completeAppeal: "अपीलची संपूर्ण स्थिती",
    decisionDetails: "निर्णय तपशील",
    documents: "दस्तऐवज",
    completeDoc: "पूर्ण कागदपत्रे",
    RTIApplicationdoc: "आरटीआय अर्जाची कागदपत्रे",
    RTIAppealdoc: "आरटीआय अपील कागदपत्रे",
    forwardApplication: "अग्रेषित/हस्तांतरण अर्ज",
    currentdept: "वर्तमान विभाग",
    currentSubDept: "वर्तमान उपविभाग",
    forwardApplication: "अर्ज फॉरवर्ड करा",
    forwardToDept: "विभागाकडे पाठवा",
    forwardTosubDept: "उपविभागाकडे पाठवा",
    downloadLoiReceipt: "सेवा स्वीकृती पत्र डाउनलोड करा",
    addInfo: "अतिरिक्त माहिती",
    downloadAcknowldgement: "पावती डाउनलोड करा",
    print: "छापणे",
    pimpariChinchwadMaha: "पिंपरी चिंचवड महानगरपालिका",
    appAcknowldgement: "पोच पावती",
    ackDear: "प्रिय",
    ackpcmcthanku: "पिंपरी चिंचवड नागरिक सेवा वापरल्याबद्दल धन्यवाद !!",

    ackshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackRTIAppealshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अपील अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackApplicationSummery: "अर्जाचा तपशील",
    applicationNo: "अर्जाचा क्रमांक",
    dateofApplication: "अर्ज दिनांक",
    ackplzContactNearestOperator:
      "कोणत्याही प्रश्नासाठी कृपया तुमच्या जवळच्या ऑपरेटरशी संपर्क साधा खालील संपर्क तपशील:",
    ackpcmcAddress: "मुंबई पुणे महामार्ग पिंपरी पुणे ४११-०१८",
    ackPcmcphNo: "फोन क्रमांक:९१-०२०-२७४२-५५११/१२/१३/१४",
    ackstateCountry: "महाराष्ट्र, भारत",
    applicantAddress: "अर्जदाराचा पत्ता :",
    rti: "माहिती अधिकार",
    no1: "१)",
    chargeNm: "शुल्काचे नाव",
    loiNo: "हेतू पत्र क्र",
    rtiApplicationAmt: "तुमच्याकडे आरटीआय या सेवेसाठी नागरिक सेवा पोर्टलवर कृपया तुमची रक्कम रुपये",
    determineandPayAmt: "निश्चित करा आणि केलेल्या सेवेची रक्कम/शुल्क भरा.",
    contactNearestpcmcDivisionalOffice: "किंवा जवळील पिंपरी चिंचवड महानगरपलिका विभागीय कार्यालयाला भेट द्या.",

    serviceAcceptance: "सेवा स्वीकृती पत्र",
    isApplicationMultiDept: "बहु विभागांतर्गत अर्ज आहे का?",
    addDepartment: "विभाग जोडा",
    parentRemark: "पॅरेंट टिप्पणी",
    forwardRemark: "अग्रेषित टिप्पणी",

    applicationType: "अर्जाचा प्रकार",

    welcomeToTheDashboard: "डॅशबोर्डवर आपले स्वागत आहे",
    dashboardTotalCount: "एकूण अर्ज",
    dashboardInProgress: "प्रगतीपथावर आहे",
    dashboardLoiGenerated: "सेवा स्वीकृती पत्र व्युत्पन्न",
    infoReady: "माहिती तयार",

    dashboardInfoReady: "माहिती तयार",
    dashboardCompleted: "पूर्ण केलेले अर्ज",
    dashboardHearingScheduled: "सुनावणी नियोजित",

    dashboardCompletedAppeal: "पूर्ण केलेले अपील",
    dashboardTotalAppealCount: "एकूण अपील",
    goToAppeal: "अपील वर जा",

    applicationinfoReady: "अर्ज माहिती तयार आहे",
    appealInfoReady: "अपील माहिती तयार आहे",

    ///////////////// FOR REPORTS ADDED BY ANWAR ANSARI /////////
    rtiApplicationRegister: "आरटीआय अर्ज नोंदणी",
    applicationNumber: "अर्ज क्रमांक",
    fullName: "पूर्ण नाव",
    descriptioniOfInformationRequired: "आवश्यक माहितीचे वर्णन",
    dateOfOrderAgainstAppeal: "अपील विरुद्ध आदेशाची तारीख",
    descriptionOfInformation: "माहितीचे वर्णन",
    concernDepartmentOrOffice: "संबंधित विभाग किंवा कार्यालय",
    reasonOfAppeal: "अपीलचे कारण",
    informationPurpose: "माहितीचा उद्देश",

    toDateR: "या तारखे पर्यंत",
    fromDateR: "या तारखेपासून",

    submit: "प्रस्तुत करा",
    downloadEXCELL: "एक्सेल डाउनलोड करा",
    downloadPDF: "पीडीएफ डाउनलोड करा",
    cancel: "रद्द करा",

    //////////////////////////////////////////////
    rtiApplicationDashboard: "आरटीआय ऍप्लिकेशन डॅशबोर्ड",
    rtiAppealRegister: "आरटीआय अपील नोंदणी",
    subjectName: "विषयाचे नाव",
    systemEntryDate: "सिस्टम एंट्रीची तारीख",
    wards: "वार्ड",
    bplCardNumber: "बीपीएल कार्ड क्रमांक",
    isApplicantBPL: "अर्जदार बीपीएल आहे",
    deptName: "विभागाचे नाव",
    /////////////////////////////////////////////////
    vivaranPatra01: "विवरण पत्र_०१",
    vivaranPatra02: "विवरण पत्र_०२",
    vivaranPatra03: "विवरण पत्र_०३",
    vivaranPatra04: "विवरण पत्र_०४",
    vivaranPatra05: "विवरण पत्र_०५",

    monthName: "महिना",
    count: "मोजणे",

    periodOfRelatedInformation: "कालावधी संबंधित माहिती",

    year: "वर्ष",

    descriptionOfInformationOfficer: "माहिती अधिकाऱ्याचे वर्णन",

    serialNumber: "अनुक्रमांक",
    deptWiseCollection: "विभागनिहाय संकलन",
    strFromDate: "या तारखेपासून",
    strToDate: "या तारखेपर्यंत",
    total: "एकूण",
    totalApplication: "एकूण अर्ज",
    grandTotal: "ग्रँड टोटल",
    requiredInformationByPostOrPersonallly: "पोस्टाने किंवा वैयक्तिकरित्या आवश्यक माहिती",
    applicationDate: "अर्जाची तारीख",
    departmentName: "विभागाचे नाव",

    fileNm: "फाईलचे नाव",
    fileType: "दस्तावेजाचा प्रकार",
    transferRemark: "हस्तांतरण टिप्पणी",
    viewAttach: "संलग्नक पहा",

    //////////////////////RTI APPLICATION WISE COLLECTION LABEL CHANGES BY SHUBHAM /////////////////
    appWiseCollection: "अर्जानुसार संकलन",
    applicationName: "अर्जाचे नाव",
    serviceAcceptanceCharges: "सेवा स्वीकृती शुल्क",
    serviceCharges: "सेवा शुल्क",
    lastMonthPendingAppCount: "मागील महिन्यात प्रलंबित अर्जांची संख्या",
    reportingMonthRecivedAppConunt: "रिपोर्टिंग महिन्यात प्राप्त अर्ज संख्या",
    reportingMonthClearanceConunt: "रिपोर्टिंग महिन्याच्या अर्ज मंजुरीच्या संख्येत",
    infoDeleverdRTIAppCount: "आरटीआय अर्जाच्या संख्येनुसार माहिती वितरित केली",
    infoRejectedRTIAppCount: "आरटीआय अर्जाच्या संख्येनुसार माहिती नाकारली",
    pendingAppCount: "प्रलंबित अर्ज संख्या",
    reportingMonthRecivedAppealConunt: "रिपोर्टिंग महिन्यात प्राप्त अपील संख्या",
    reportingMonthAppealClearanceConunt: "रिपोर्टिंग महिन्याच्या अपील मंजुरीच्या संख्येत",
    appealAcceptedConunt: "अपील स्वीकृत संख्या",
    appealRejectedConunt: "अपील नाकारलेली संख्या",
    pendingAppealConunt: "प्रलंबित अपील संख्या",
    lastMonthPendingAppealCount: "गेल्या महिन्यात प्रलंबित अपील गणना",
    reportingMonthDeleveredAppealCount: "वितरीत अपील संख्या अहवाल महिन्यात",
    pendingAppealCount: "प्रलंबित अपील संख्या",
    rtiDueDate: "आरटीआय देय तारीख",
    totalNoOfDays: "दिवसांची एकूण संख्या",
    Tnc: "नियम व अटी",
    getDetails: "तपशील मिळवा",
    results: "परिणाम",
    searchArea: "क्षेत्र शोधा",
    rtiTermsndTitle: 'पिंपरी चिंचवड महानगरपलिका,पिंपरी-४११०१८',
    rtiAct2005: "महिती अधिकार कायदा, २००५ ",
    guidelineOfRti: "आरटीआय ऑनलाइन पोर्टलच्या वापरासाठी मार्गदर्शक तत्त्वे",
    guideline1: "१) या वेब पोर्टलचा वापर भारतीय नागरिक आरटीआय अर्ज ऑनलाइन दाखल करण्यासाठी आणि आरटीआय अर्जासाठी ऑनलाइन पेमेंट करण्यासाठी करू शकतात. प्रथम अपील ऑनलाइन देखील दाखल करता येईल.",
    guideline2: "२) आरटीआय कायद्यांतर्गत कोणतीही माहिती मिळवू इच्छिणारा अर्जदार या वेब पोर्टलद्वारे पिंपरी चिंचवड महानगरपालिकाला  विनंती करू शकतो.",
    guideline3: '३) "सबमिट रिक्वेस्ट" वर क्लिक केल्यावर, अर्जदाराने दिसणार्‍या पेजवर आवश्यक तपशील भरावा लागेल.',
    guideline4: '४) चिन्हांकित फील्ड अनिवार्य आहेत तर इतर पर्यायी आहेत.',
    guideline5: '५) अर्जाचा मजकूर विहित रकान्यात लिहिला जाऊ शकतो.',
    guideline6: '६) सध्या, विहित रकान्यात अपलोड करता येणारा अर्जाचा मजकूर केवळ 3000 वर्णांपुरताच मर्यादित आहे.',
    guideline7: '७) फक्त अक्षरे A-Z a-z क्रमांक 0-9 आणि विशेष वर्ण , . - _ ( ) / @ : & ? RTI विनंती अर्जासाठी मजकुरात \ % ला अनुमती आहे.',
    guideline8: '८) जर अनुप्रयोगामध्ये 3000 पेक्षा जास्त वर्ण असतील तर, "सपोर्टिंग डॉक्युमेंट" कॉलम वापरून ते संलग्नक म्हणून अपलोड केले जाऊ शकते.',
    guideline9: '९) आधार कार्ड किंवा पॅन कार्ड किंवा इतर कोणतीही वैयक्तिक ओळख (बीपीएल कार्ड वगळता) अपलोड करू नका.',
    guideline10: '१०) पीडीएफ फाइलच्या नावात रिक्त जागा असू नयेत.',
    guideline11: '११) पहिले पान भरल्यानंतर, विहित शुल्क भरण्यासाठी अर्जदाराला "पेमेंट करा" वर क्लिक करावे लागेल.',
    guideline12: '१२) अर्जदार खालील पद्धतींद्वारे विहित शुल्क भरू शकतात: o	इंटरनेट बँकिंग; o	मास्टर/व्हिसाचे क्रेडिट/डेबिट कार्ड वापरणे; o	RuPay कार्ड वापरणे.',
    guideline13: '१३) अर्ज करण्यासाठी शुल्क आरटीआय नियम, 2012 मध्ये विहित केलेले आहे.',
    guideline14: '१४) पेमेंट केल्यानंतर, अर्ज सबमिट केला जाऊ शकतो.',
    guideline15: '१५) पेमेंट केल्यानंतर, जर अर्जदाराला नोंदणी क्रमांक प्राप्त झाला नाही तर अर्जदाराला 24-48 कामकाजाच्या तासांची प्रतीक्षा करण्याचा सल्ला दिला जातो कारण नोंदणी क्रमांक सामंजस्यानंतर तयार केला जाईल. कृपया पुन्हा पेमेंट करण्याचा अतिरिक्त प्रयत्न करू नका. जर ते 24-48 तासांच्या आत व्युत्पन्न झाले नाही तर कृपया (sarthi@pcmcindia.gov.in), (egov@pcmcindia.com) येथे व्यवहाराच्या तपशीलांसह ई-मेल पाठवा.',
    guideline16: '१६) RTI नियम, 2012 नुसार दारिद्र्यरेषेखालील कोणत्याही नागरिकाला RTI फी भरण्याची आवश्यकता नाही. तथापि, अर्जदाराने या संदर्भात योग्य सरकारने जारी केलेल्या प्रमाणपत्राची प्रत अर्जासोबत जोडणे आवश्यक आहे.',
    guideline17: '१७) अर्ज सबमिट केल्यावर, एक अद्वितीय नोंदणी क्रमांक जारी केला जाईल, जो अर्जदार भविष्यात कोणत्याही संदर्भासाठी संदर्भित करू शकेल.',
    guideline18: '१८) या वेब पोर्टलद्वारे दाखल केलेला अर्ज इलेक्ट्रॉनिक पद्धतीने संबंधित विभागाच्या "नोडल ऑफिसर" पर्यंत पोहोचेल, जो संबंधित PIO कडे RTI अर्ज इलेक्ट्रॉनिक पद्धतीने पाठवेल.',
    guideline19: '१९) माहिती प्रदान करण्यासाठी खर्चाचे प्रतिनिधित्व करण्यासाठी अतिरिक्त शुल्क आवश्यक असल्यास, PIO अर्जदाराला या पोर्टलद्वारे सूचित करेल. ही सूचना अर्जदाराला स्टेटस रिपोर्टद्वारे किंवा त्याच्या/तिच्या ई-मेल अलर्टद्वारे पाहता येईल.',
    guideline20: '२०) प्रथम अपील प्राधिकरणाकडे अपील करण्यासाठी, अर्जदाराला "प्रथम अपील सबमिट करा" वर क्लिक करावे लागेल आणि दिसेल ते पृष्ठ भरावे लागेल.',
    guideline21: '२१) मूळ अर्जाचा नोंदणी क्रमांक संदर्भासाठी वापरावा लागेल.',
    guideline22: '२२) आरटीआय कायद्यानुसार, प्रथम अपीलसाठी कोणतेही शुल्क भरावे लागत नाही.',
    guideline23: '२३) अर्जदार/अपीलकर्त्याने एसएमएस अलर्ट प्राप्त करण्यासाठी त्याचा/तिचा मोबाईल क्रमांक सादर करावा.',
    guideline24: '२४) ऑनलाइन दाखल केलेल्या आरटीआय अर्जाची/प्रथम अपीलची स्थिती अर्जदार/अपीलकर्ता "स्थिती पहा" वर क्लिक करून पाहू शकतात.',
    guideline25: '२५) RTI कायदा, 2005 मध्ये प्रदान केल्याप्रमाणे RTI अर्ज आणि प्रथम अपील तसेच कालमर्यादा, सूट इत्यादींसंबंधीच्या इतर तरतुदी दाखल करण्याच्या सर्व आवश्यकता लागू राहतील.',

    mediumPrefReq: "माध्यम उपसर्ग आवश्यक आहे !!!",
    nmOfMediumReq: "माध्यमाचे नाव आवश्यक आहे !!!",
    nmOfMediumReqMr: "मराठीत माध्यमाचे नाव आवश्यक आहे !!!",


    mediumMinLeng: "माध्यमाचे नाव किमान 2 वर्ण असले पाहिजे",
    mediumMaxLen: "माध्यमाचे नाव खूप मोठे आहे",

    mediumMinLengMr: "मराठीतील माध्यमाचे नाव किमान २ अक्षरांचे असावे",
    mediumMaxLenMr: "मराठीत माध्यमाचे नाव खूप मोठे आहे",

    mediumPrefMinLeng: "माध्यम उपसर्ग किमान 2 वर्ण असणे आवश्यक आहे",
    mediumPrefMaxLen: "मध्यम उपसर्ग खूप मोठा आहे",


    decisionMinLen: "निर्णय तपशील किमान 20 वर्ण असणे आवश्यक आहे",
    decisionMaxLen: "निर्णयाचे तपशील खूप मोठे आहेत",
    decisionReq: "सुनावणीत घेतलेला निर्णय आवश्यक!!!",
    decisionStatusReq: "निर्णयाची स्थिती आवश्यक आहे !!!",
    remarkReq: "टिप्पणी आवश्यक आहे !!!",
    venueReq: "सुनावणीचे ठिकाण आवश्यक आहे !!!",
    chargeTypeReq: "शुल्काचा प्रकार आवश्यक आहे !!!",

    educationReq: "शिक्षण आवश्यक आहे !!!",
    areaNmReq: "क्षेत्राचे नाव आवश्यक आहे !!!",
    wardNmReq: "प्रभागाचे नाव आवश्यक आहे !!!",
    zoneNmReq: "झोनचे नाव आवश्यक आहे !!!",
    deptReq: "विभागाचे नाव आवश्यक आहे !!!",
    isBplReq: "दारिद्र्यरेषेखालील अर्जदार आवश्यक आहे !!!",
    addReq: "पत्ता आवश्यक आहे !!!",
    descriptionReq: "आवश्यक माहितीचे वर्णन आवश्यक आहे !!!",
    reasonForAppealReq: "अपीलचे कारण आवश्यक आहे !!!",
    appliFirstNmReq: "अर्जदाराचे पहिले नाव आवश्यक आहे !!!",
    appliMiddNmReq: "अर्जदाराचे मधले नाव आवश्यक आहे !!!",
    appliLastNmReq: "अर्जदाराचे आडनाव आवश्यक आहे !!!",
    genderReq: "लिंग आवश्यक आहे !!!",
    pincodeReq: 'पिनकोड आवश्यक आहे !!!',
    inCorrectMsg: "चुकीचे स्वरूप",
    emailReq: "ईमेल आयडी आवश्यक आहे !!!",
    contactReq: "संपर्क तपशील आवश्यक आहे !!!",
    attachDate: "जोडलेली तारीख",

    uploadTitle: "अपलोड करा",
    childDeptTitle: "Child अर्ज विभाग",
    attachDoccument: "दस्तऐवज संलग्न करा",
    descriptionMaxLen: "वर्णन मर्यादा ओलांडत आहे",
    addressMaxLen: "पत्ता मर्यादा ओलांडत आहे",
    reasonMaxLen:"अपीलचे कारण मर्यादा ओलांडत आहे",
    remarkMaxLen:"टिप्पणी मर्यादा ओलांडली आहे",
    venueMaxLen:"सुनावणीचे ठिकाण मर्यादा ओलांडत आहे",
    decisionStatussMaxLen:"निर्णयाची स्थिती मर्यादा ओलांडत आहे"

  },
};
