const schoolLabels = {
  en: {
    type: "commonLabels",
    module: "School",

    studentDailyAttendance: "Student Daily Attendance",
    classTimetable: "Class Timetable",
    timeAndSub: "Select Time and Subjects",

    studentList: "Student List",
    selectSchool: "Select School",
    schoolRequired: "School is required",
    selectAcademicYear: "Select Academic Year",
    academicYear: "Academic Year",
    academicYearRequired: "Academic Year is required",
    selectClass: "Select Standard",
    classRequired: "Class is required",
    selectDivision: "Select Division",
    divisionRequired: "Division is required",
    date: "Date",
    dateRequired: "Date is required",
    studentName: "Student Name",
    presentAbsent: "Present/Absent",
    examName: "Exam Name",
    examType: "Exam Type",
    othExamTypeName: "Other Exam Type Name",
    othExamTypeNameRequired: "Other Exam Type Name is Required",
    examNameRequired: "Exam Name is required",
    examTypeRequired: "Exam Type is required",
    examDate: "Exam Date",
    examDateRequired: "Exam Date is required",
    examFromTime: "Exam From Time",
    examFromTimeRequired: "Exam From Time is required",
    examToTime: "Exam To Time",
    examToTimeRequired: "Exam To Time is required",
    srNo: "Sr.No",

    ayFromDate: "From Date",
    ayToDate: "To Date",

    schoolClass: "School Standard",
    schoolDiv: "School Standard Division",

    schoolName: "School Name",
    schoolNameMr: "School Name (In Marathi)",
    studentGeneralRegisterNumber: "Student General Register Number",
    admissionDate: "Admission Date",
    rollNumber: "Roll Number",
    divisionName: "Division Name",
    divisionPrefix: "Division Code",
    intake: "Intake",
    firstName: " First Name",
    middleName: "Middle Name",
    surnameName: "Surname Name",
    address: "Address",
    mobileNumber: "Mobile Number",
    emailId: "Email ID",
    studentGRnumber: "Student GR Number",
    applicationStatus: "Application Status",
    className: "Standard Name",
    division: "Division",
    dateOfbirth: "Date of Birth",
    birthAddress: "Birth Address",
    remark: "Remark",
    bonafiedPurpose: "Purpose of bonafide certificate",
    bonafiedPurposeMr: "Purpose of bonafide certificate (in Marathi)",
    approveBonafiedDate: "Bonafide Approve Date",
    approveLCDate: "Leaving Certificate Approve Date",
    selectStudent: "Select Student",
    studentRequired: "Student is required",
    reasonForLeavingSchoolMr: "School leaving Reason (In Marathi)",
    reasonForLeavingSchoolEn: "School leaving Reason (In English)",

    addNewTimetable: "Add New Timetable",
    updateTimetable: "Update Timetable",
    periodList: "Period List",
    day: "Day",
    from: "From",
    to: "To",
    subject: "Subject",
    academicSubject: "Academic Subject",
    teacher: "Teacher",
    recess: "Recess",
    teachersForSubjects: "Assign Teachers for Subjects",
    selectSubject: "Select Subject",
    selectTeacher: "Select Teacher",

    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    7: "Saturday",
    fromTime: "From Time",
    toTime: "To Time",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",

    search: "Search",
    clear: "Clear",
    close: "Close",
    teacherParentCommunication: "Teacher Parent Communication",
    add: "Add",
    save: "Save",
    edit: "Edit",
    toggle: "Toggle",
    updateAttendance: "Update Attendance",
    update: "Update",
    exit: "Exit",

    success: "Success!",
    attendanceUpdated: "Attendance Updated Successfully",
    examSaved: "Exam Saved Successfully",
    examUpdated: "Exam Updated Successfully",
    error: "Error!",
    admissionRegitrationNo: "Admission Reg. No.",

    aadharNumber: "Aadhar Number",
    schoolTeacher: "School Teacher",
    gender: "Gender",
    male: "Male",
    female: "Female",
    motherTongue: "Mother Tongue",
    permanentAddress: "Permanent Address",
    pincode: "Pincode",
    contactPersonName: "Contact Person Name",
    contactPersonNumber: "Contact Person Number",
    schoolMaster: "School Master",
    schoolPrefix: "School Code",
    gisCode: "GIS Code",
    udiceCode: "UDICE Number",
    schoolAddress: "School Address",
    lattitude: "Lattitude",
    longitude: "Longitude",
    message: "Message",
    teacherName: "Teacher Name",
    selectAll: "Select All",
    actions: "Actions",
    action: "Action",
    age: "Age",
    status: "Status",
    reject: "Reject",
    approve: "Approve",
    submit: "Submit",
    view: "View",
    principalRemarksEn: "Principal Remarks (In Eng)",
    principalRemarksMr: "Principal Remarks (In Mar)",

    studentAdmissionForm: "Student Admission Form",
    studentPersonalInfo: "Personal Details",
    studentParentInfo: "Parents or Guardian Details",
    studentOthInfo: "Other Details",
    lastSchoolInfo: "Last School Information (If Applicable)",
    accountDetails: "Bank Account Details",
    accountNo: "Bank Account Number",
    confirmBankAcNumber: "Confirm Bank Account Number",
    bankName: "Bank Name",
    ifscCode: "Bank IFSC Code",
    bankAdderess: "Bank Adderess",
    documents: "Documents",
    accountHolderName: "Account Holder Name",
    zoneName: "Zone Name",
    wardName: "Ward Name",
    studentFirstName: "Student First Name",
    studentFirstNameMr: "Student First Name (In Marathi)",
    studentMiddleName: "Student Middle Name",
    studentMiddleNameMr: "Student Middle Name (In Marathi)",
    studentLastName: "Student Last Name",
    studentLastNameMr: "Student Last Name (In Marathi)",
    fatherFirstName: "Father First Name",
    fatherMiddleName: "Father Middle Name",
    fatherLastName: "Father Last Name",
    motherName: "Mother First Name",
    motherNameMr: "Mother First Name (In Marathi)",
    motherMiddleName: "Mother Middle Name",
    motherLastName: "Mother Last Name",
    religion: "Religion",
    casteName: "Caste Category",
    citizenship: "Citizenship",
    birthPlace: "Birth Place",
    birthPlaceMr: "Birth Place (In Marathi)",
    studentState: "Student Birth State",
    studentDist: "Student Birth District",
    parentAddress: "Parent Address",
    parentOccupation: "Parent Occupation",
    fatherMobileNumber: " Father Mobile Number",
    motherMobileNumber: " Mother Mobile Number",
    permanentAddress: "Permanent Address",
    parentFullName: "Parent Full Name",
    parentEmailId: "Parent Email",
    colony: "Colony",
    district: "District",
    state: "State",
    lastSchoolName: "Last School Name -if applicable",
    lastSchoolNameMr: "Last School Name (In Marathi) -if applicable",
    lastSchoolAdmissionDate: "Last School Admission Date -if applicable",
    lastSchoolAndFromWhenStudying: "Last School and from when Studying",
    lastSchoolLeavingDate: "Last School Leaving Date",
    studentBehaviour: "Student Behaviour",
    studentBehaviourMr: "Student Behaviour (In Marathi)",
    reasonForLeavingSchool: "Reason for Leaving School",

    studentBirthCertificate: "Student Birth Certificate",
    studentSchoolLeavingCertificate: "Student School Leaving Certificate (if applicable)",
    studentPhotograph: "Student Photograph",
    studentAadhar: "Student Aadhar Card",
    parentAadhar: "Parent Aadhar Card",
    studentLastYearMarksheet: "Student Last Year Marksheet (if applicable)",

    selectExam: "Select Examination",
    exam: "Examination",
    examMarks: "Exam Marks",
    examRequired: "Examination is required",
    selectTerm: "Select Term",
    term: "Term",
    termRequired: "Term is required",
    marksObtained: "Marks Obtained",
    outOfMarks: "Out of Marks",
    outOfMarksRequired: "Out of Marks is required",
    passingMarks: "Passing Marks",
    passingMarksRequired: "Passing Marks is required",
    marksError: "Marks should be less than or equal to out of marks",
    updateMarks: "Update Marks",
    marksUpdated: "Marks Updated Successfully",

    deactivate: "Deactivate",
    activate: "Activate",
    areYouSureToDeactivate: "Are you sure to deactivate this record?",
    areYouSureToActivate: "Are you sure to activate this record?",
    deactivateSuccess: "Record Deactivated Successfully",
    activateSuccess: "Record Activated Successfully",
    previewReport: "Preview Report",
    classTimetableReport: "Class Timetable Report",
    generateReport: "Generate Report",
    fromDate: "From Date",
    toDate: "To Date",
    studentsAttendanceReport: "Students Attendance Report",
    schoolLeavingCert: "School Leaving Certificate",
    studentBonafideCert: "Student Bonafide Certificate",
  },

  mr: {
    type: "commonLabels",
    module: "शाळा",

    studentDailyAttendance: "विद्यार्थी दैनिक उपस्थिती",
    classTimetable: "वर्ग वेळापत्रक",
    timeAndSub: "वेळ आणि विषय निवडा",

    studentList: "विद्यार्थी सूची",
    selectSchool: "शाळा निवडा",
    schoolRequired: "शाळा आवश्यक आहे",
    selectAcademicYear: "शैक्षणिक वर्ष निवडा",
    academicYear: "शैक्षणिक वर्ष",
    academicYearRequired: "शैक्षणिक वर्ष आवश्यक आहे",
    selectClass: "इयत्ता निवडा",
    classRequired: "वर्ग आवश्यक आहे",
    selectDivision: "तुकडी निवडा",
    divisionRequired: "तुकडी आवश्यक आहे",
    date: "तारीख",
    dateRequired: "तारीख आवश्यक आहे",
    studentName: "विद्यार्थ्याचे नाव",
    presentAbsent: "उपस्थित/अनुपस्थित",
    examName: "परीक्षेचे नाव",
    examType: "परीक्षेचा प्रकार",
    othExamTypeName: "इतर परीक्षा प्रकाराचे नाव",
    othExamTypeNameRequired: "इतर परीक्षा प्रकाराचे नाव आवश्यक आहे",
    examNameRequired: "परीक्षेचे नाव आवश्यक आहे",
    examTypeRequired: "परीक्षेचा प्रकार आवश्यक आहे",
    examDate: "परीक्षेची तारीख",
    examDateRequired: "परीक्षेची तारीख आवश्यक आहे",
    examFromTime: "सुरवातीची वेळ",
    examFromTimeRequired: "सुरवातीची वेळ आवश्यक आहे",
    examToTime: "समाप्तीची वेळ",
    examToTimeRequired: "समाप्तीची वेळ आवश्यक आहे",
    srNo: "अनु क्रमांक",
    ayFromDate: "पासून वर्ष",
    ayToDate: "आजपर्यंत",

    schoolClass: "शाळेची इयत्ता",
    schoolDiv: "शाळेतील इयत्तेची तुकडी",

    schoolName: "शाळेचे नाव",
    schoolNameMr: "शाळेचे नाव (मराठी मध्ये)",
    studentGeneralRegisterNumber: "अर्ज क्रमाांक",
    admissionDate: "प्रवेशाची तारीख",
    rollNumber: "हजेरी क्रमांक",
    divisionName: "तुकडीचे नाव",
    divisionPrefix: "तुकडी कोड",
    intake: "जागा",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    surnameName: "आडनाव",
    address: "पत्ता",
    mobileNumber: "मोबाईल नंबर",
    emailId: "ई - मेल आयडी",
    studentGRnumber: "विद्यार्थी GR क्रमांक",
    applicationStatus: "अर्जाची स्थिती",
    className: "इयत्तेचे नाव",
    division: "विभागणी",
    dateOfbirth: "जन्मतारीख",
    birthAddress: "जन्माचा पत्ता",
    remark: "शेरा",
    bonafiedPurpose: "बोनाफाईड प्रमाणपत्राचा उद्देश",
    bonafiedPurposeMr: "बोनाफाईड प्रमाणपत्राचा उद्देश (मराठीत)",
    approveBonafiedDate: "बोनाफाईड मंजूर दिनांक",
    approveLCDate: "शाळा सोडल्याचा दाखला मंजूर दिनांक",
    selectStudent: "विद्यार्थी निवडा",
    studentRequired: "विद्यार्थी आवश्यक आहे",
    reasonForLeavingSchoolMr: "शाळा सोडण्याचे कारण (मराठीत)",
    reasonForLeavingSchoolEn: "शाळा सोडण्याचे कारण (इंग्रजीमध्ये)",

    addNewTimetable: "नवीन वेळापत्रक जोडा",
    updateTimetable: "वेळापत्रक अद्यायावत करा",
    periodList: "वेळापत्रक सूची",
    day: "वार  ",
    from: "सुरू",
    to: "समाप्त",
    subject: "विषय",
    academicSubject: "शैक्षणिक विषय",
    teacher: "शिक्षक",
    recess: "सुट्टी",
    teachersForSubjects: "विषयांसाठी शिक्षक नियुक्त करा",
    selectSubject: "विषय निवडा",
    selectTeacher: "शिक्षक निवडा",

    2: "सोमवार",
    3: "मंगळवार",
    4: "बुधवार",
    5: "गुरुवार",
    6: "शुक्रवार",
    7: "शनिवार",
    fromTime: "या वेळेपासून",
    toTime: "या वेळेपर्यंत",
    Monday: "सोमवार",
    Tuesday: "मंगळवार",
    Wednesday: "बुधवार",
    Thursday: "गुरुवार",
    Friday: "शुक्रवार",
    Saturday: "शनिवार",

    search: "शोधा",
    clear: "हटवा",
    close: "बंद करा",
    teacherParentCommunication: "शिक्षक पालक संपर्क",
    add: "जोडा",
    save: "जतन करा",
    edit: "संपादित करा",
    toggle: "टॉगल करा",
    updateAttendance: "उपस्थिती अद्यायावत करा",
    update: "अद्यायावत करा",
    exit: "बाहेर पडा",

    success: "सफलता!",
    attendanceUpdated: "उपस्थिती यशस्वीरित्या अद्यायावत केली गेली आहे",
    examSaved: "परीक्षा यशस्वीरित्या जतन केली गेली आहे",
    examUpdated: "परीक्षा यशस्वीरित्या अद्यायावत केली गेली आहे",
    error: "त्रुटी!",
    admissionRegitrationNo: "प्रवेश नोंदणी क्रमांक",

    aadharNumber: "आधार क्रमांक",
    schoolTeacher: "शाळेतील शिक्षक",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    motherTongue: "मातृभाषा",
    permanentAddress: "कायमचा पत्ता",
    pincode: "पिन कोड",
    contactPersonName: "संपर्क व्यक्तीचे नाव",
    contactPersonNumber: "संपर्क व्यक्ती क्रमांक",
    schoolMaster: "शाळा मास्टर",
    schoolPrefix: "शाळेचा कोड",
    gisCode: "GIS कोड",
    udiceCode: "UDICE क्रमांक",
    schoolAddress: "शाळेचा पत्ता",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    message: "संदेश",
    teacherName: "शिक्षकाचे नाव",
    selectAll: "सर्व निवडा",
    actions: "क्रिया",
    action: "क्रिया",
    age: "वय",
    status: "स्थिती",
    reject: "नकार",
    approve: "मंजूर",
    submit: "सबमिट",
    view: "पहा",
    principalRemarksEn: "मुख्याध्यापक रिमार्क्स (इंग्रजीमध्ये)",
    principalRemarksMr: "मुख्याध्यापक रिमार्क्स (मराठीमध्ये)",

    studentAdmissionForm: "विद्यार्थी प्रवेश अर्ज",
    studentPersonalInfo: "वैयक्तिक माहिती",
    studentOthInfo: "इतर माहिती",
    studentParentInfo: "आईवडील / पालक माहिती",
    lastSchoolInfo: "शेवटच्या शाळेची माहिती (लागू असल्यास)",
    accountDetails: "बँक खाते तपशील",
    accountNo: "बँक खाते क्रमांक",
    confirmBankAcNumber: "बँक खाते क्रमांकाची पुष्टी करा",
    bankName: "बँकेचे नाव",
    ifscCode: "बँक IFSC कोड",
    bankAdderess: "बँकेचा पत्ता",
    documents: "कागदपत्रे",
    accountHolderName: "खातेधारकाचे नाव",
    zoneName: "झोनचे नाव",
    wardName: "प्रभागाचे नाव",
    studentFirstName: "विद्यार्थ्याचे पहिले नाव",
    studentFirstNameMr: "विद्यार्थ्याचे पहिले नाव (मराठी मध्ये)",
    studentMiddleName: "विद्यार्थ्याचे मधले नाव",
    studentMiddleNameMr: "विद्यार्थ्याचे मधले नाव (मराठी मध्ये)",
    studentLastName: "विद्यार्थ्याचे आडनाव",
    studentLastNameMr: "विद्यार्थ्याचे आडनाव (मराठी मध्ये)",
    fatherFirstName: "वडिलांचे पहिले नाव",
    fatherMiddleName: "वडिलांचे मधले नाव",
    fatherLastName: "वडिलांचे आडनाव",
    motherName: "आईचे पहिले नाव",
    motherNameMr: "आईचे पहिले नाव (मराठी मध्ये)",
    motherMiddleName: "आईचे मधले नाव",
    motherLastName: "आईचे आडनाव",
    religion: "धर्म",
    casteName: "जातीचे नाव",
    citizenship: "नागरिकत्व",
    birthPlace: "जन्म ठिकाण",
    birthPlaceMr: "जन्म ठिकाण (मराठी मध्ये)",
    studentState: "विद्यार्थी जन्मठिकाण राज्य",
    studentDist: "विद्यार्थी जन्मठिकाण जिल्हा",
    parentAddress: "पालकांचा पत्ता",
    parentOccupation: "पालकांचा व्यवसाय ",
    fatherMobileNumber: "वडिलांचा मोबाईल नंबर ",
    motherMobileNumber: "आईचा मोबाईल नंबर ",
    permanentAddress: "कायमचा पत्ता",
    parentFullName: "पालकांचे पूर्ण नाव",
    parentEmailId: "पालक ईमेल आयडी",
    colony: "वसाहत",
    district: "जिल्हा",
    state: "राज्य",
    lastSchoolName: "शेवटच्या शाळेचे नाव -जर लागू असेल तर",
    lastSchoolNameMr: "शेवटच्या शाळेचे नाव (मराठी मध्ये) -जर लागू असेल तर",
    lastSchoolAdmissionDate: "शाळा प्रवेशाची शेवटची तारीख - लागू असल्यास",
    lastSchoolAndFromWhenStudying: "शेवटचा वर्ग आणि कधीपासून अभ्यास",
    lastSchoolLeavingDate: "शाळा सोडण्याची शेवटची तारीख",
    studentBehaviour: "विद्यार्थ्याचे वर्तन",
    studentBehaviourMr: "विद्यार्थ्याचे वर्तन (मराठी मध्ये)",
    reasonForLeavingSchool: "शाळा सोडण्याचे कारण",

    studentBirthCertificate: "विद्यार्थी जन्म प्रमाणपत्र",
    studentSchoolLeavingCertificate: "विद्यार्थी शाळा सोडल्याचा दाखला (लागू असल्यास)",
    studentPhotograph: "विद्यार्थ्याचा फोटो",
    studentAadhar: "विद्यार्थी आधार कार्ड",
    parentAadhar: "पालक आधार कार्ड",
    studentLastYearMarksheet: "विद्यार्थी शेवटच्या वर्षाची मार्कशीट (लागू असल्यास)",

    selectExam: "परीक्षा निवडा",
    exam: "परीक्षा",
    examMarks: "परीक्षा गुण",
    examRequired: "परीक्षा आवश्यक आहे",
    selectTerm: "सत्र निवडा",
    term: "अवधी",
    termRequired: "सत्र आवश्यक आहे",
    marksObtained: "प्राप्त गुण",
    outOfMarks: "एकूण गुण",
    outOfMarksRequired: "एकूण गुण आवश्यक आहे",
    passingMarks: "उत्तीर्ण गुण",
    passingMarksRequired: "उत्तीर्ण गुण आवश्यक आहे",
    marksError: "मिळवलेले गुण हे एकूण गुणांच्या आत असणे आवश्यक आहे",
    updateMarks: "गुण अद्यायावत करा",
    marksUpdated: "गुण यशस्वीरित्या अद्यायावत केले गेले आहेत",

    deactivate: "निष्क्रिय करा",
    activate: "सक्रिय करा",
    areYouSureToDeactivate: "तुम्हाला निष्क्रिय करण्याची खात्री आहे?",
    areYouSureToActivate: "तुम्हाला सक्रिय करण्याची खात्री आहे?",
    deactivateSuccess: "निष्क्रिय करण्यात यशस्वी झाले",
    activateSuccess: "सक्रिय करण्यात यशस्वी झाले",
    previewReport: "पूर्वावलोकन अहवाल",
    classTimetableReport: "वर्ग वेळापत्रकाचा अहवाल",
    generateReport: "अहवाल तयार करा",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    studentsAttendanceReport: "विद्यार्थ्यांचा उपस्थिती अहवाल",
    schoolLeavingCert: "शाळा सोडल्याचा दाखला",
    studentBonafideCert: "विद्यार्थी बोनाफाईड प्रमाणपत्र",
  },
};

export default schoolLabels;
