export default {
  en: {
    RoadExcavation_NocPermission: "ROAD EXCAVATION / NOC PERMISSION",
    roadTypes: "Road Type",
    srNo: "Sr. No.",
    roadType: "Road Type",
    roadTypePrefix: "Road Type Prefix",
    remarks: "Remarks",
    actions: "Actions",
    add: "Add",
    roadTypeName: "Road Type Name",
    update: "Update",
    save: "Save",
    clear: "Clear",
    exit: "Exit",
    applicationNumber: "Application Number",
  },
  mr: {
    RoadExcavation_NocPermission: "रस्ता उत्खनन / एनओसी परवानगी",
    roadTypes: "रस्त्याचे प्रकार",
    srNo: "अ.क्र.",
    roadType: "रस्त्याचा प्रकार",
    roadTypePrefix: "रस्त्याचा प्रकार उपसर्ग",
    remarks: "टिप्पणी",
    actions: "क्रिया",
    add: "जोडा",
    roadTypeName: "रस्त्याचे नाव",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    applicationNumber: "अर्ज क्रमांक",
  },
};
