export default {
  en: {
    mediumPrefix: "Medium Prefix",
    nameOfMedium: "Name of Medium",
    nameOfMediumMr: "Name of Medium in Marathi",
    infoTransferMediumMaster: "Medium Master",
    add: "Add",
    srNo: "Sr.No",
    actions: "Actions",
    address: "Address",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    rtiApplication: "RTI Application",
    applicantFirstName: "Applicant First Name",
    applicantMiddleName: "Applicant Middle Name",
    applicantLastName: "Applicant Last Name",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    pinCode: "Pincode",
    contactDetails: "Contact Details",
    emailId: "Email Id",
    education: "Education",
    educated: "Educated",
    unEducated: "Uneducated",
    wardkey: "Ward",
    zoneKey: "Zone",
    departmentKey: "Department",
    subDepartmentKey: "Sub department",
    isApplicantBelowToPovertyLine: "Is applicant below to poverty line?",
    bplCardNo: "BPL Card Number",
    yearOfIssues: "Year of Issues",
    issuingAuthority: "Issuing Authority",
    informationSubject: "Information Subject",
    fromDate: "From Date(Related Information)",
    toDate: "To Date(Related Information)",
    description: "Descrition of required Information",
    yes: "Yes",
    no: "No",
    requiredInfoDeliveryDetails: "Required Information Delivery Details",
    byPost: "By Post",
    personally: "Personally",
    softCopy: "Soft Copy",
    departmentKey: "Department Name",
    subDepartmentKey: "Sub Department Name",
    wardKey: "Ward Name",

    rtiAppeal: "RTI Appeal",
    applicationNo: "Application No",
    search: "Search",
    descInfoOfOfficer: "Description of Information officer",
    dateOfOfficialorderAgainstAppeal: "Date of Official order against the appeal",
    descriptionOfInfo: "Description of Information",
    reqInfoSubjectAndDesc: "Required Information subject and description",
    concernOfficerDeptnmWhoseInfoRequired: "Concern office or department name whose information required",
    rtiFileDate: "RTI File Date",

    requiredInfoPurpose: "Required Information Purpose",
    reasonForAppeal: "Reason for Appeal",
    paymentModeKey: "Payment Mode",
    paymentAmount: "Application Charges",
    status: "Status",
    rtiApplicationList: "RTI Application List",
    ViewrtiApplication: "View RTI Application",

    appealApplicationNo: "Appeal Application No",
    rtiAppealList: "RTI Appeal List",
    appealFileDate: "Appeal File Date",
    viewrtiAppeal: "View RTI Appeal",
    currentStatus: "Current Status",
    isLOIGenerated: "Is Information Charges/LOI Generated?",
    payment: "Payment Done",
    saveAndPay: "Save and Pay",
    completeApplication: "Complete status of Application",
    loiGenerate: "Information Charges",
    closeModal: "Close",
    loiGenerateBtn: "LOI Generate",
    serviceName: "Service Name",
    noOfPages: "No of Pages",
    chargeType: "Charge Type",
    amount: "Amount",
    totalAmount: "Total Amount",
    remark: "Remark",
    viewLoi: "View Letter of Intent",
    print: "Print",
    makePayment: "Make a Payment",
    applicationReceivedBy: "Application Received By",
    cfcuser: "CFC User",
    citizenuser: "Citizen User",
    pcmcportal: "PCMC Portal",
    aaplesarkar: "Aaple Sarkar",
    ratePerPage: "Rate Per Page",
    fileSize: " File size must be less than 2MB",
    fileExtension: "Attach Only .JPG, .PNG, .JPEG  and .PDF files",
    cancel: "Cancel",
    fileUpload: "File Upload",
    addDoc: " ADD DOCUMENTS",
    uploadDoc: "UPLOAD DOCUMENT/IMAGE",
    informationRemark: "Information Ready Remark",
    infoReady: "Information Ready",
    infoPages: "Information Pages",
    selectedReturnMedia: "Selected Return Media",
    infoReadyDate: "Information Ready Date",
    completeDate: "Completed Date",
    completeRemark: "Complete Remark",
    informationReturnMedia: "Information Return Media",
    hearingSchedule: "Hearing Schedule",
    decisionEntry: "Decision Entry",

    applicantName: "Applicant Name",
    appealNo: "Appeal No",
    scheduleDate: "Schedule Date",
    scheduleTime: "Schedule Time",
    venueForHearing: "Venue for Hearing",
    subject: "Subject",
    rtiApplicationNO: "RTI Application No",

    decisiontakenInHearing: "Decision taken in hearing",

    decisionStatus: "Decision Status by department",
    decisionOrderAttach: "Decision order upload",
    updloadScanInfoDelivered: "Upload Scan Copy of Information Delivered",
    hearingReschedule: "Hearing Reschedule",
    completeAppeal: "Complete Status of Appeal",
    decisionDetails: "Decision Details",
    documents: "Documents",
    completeDoc: "Complete Documents",
    RTIApplicationdoc: "RTI Application Documents",
    RTIAppealdoc: "RTI Appeal Documents",
    forwardApplication: "Forward/Transfer Application",
    currentdept: "Current department",
    currentSubDept: "Current sub department",
    forwardApplication: "Forward Application",
    forwardToDept: "Forward to department",
    forwardTosubDept: "Forward to sub department",
    downloadLoiReceipt: "Download Service Acceptance Letter Receipt",
    addInfo: "Additional Information",
    downloadAcknowldgement: "Download Acknowledgement",
    print: "Print",
    pimpariChinchwadMaha: "Pimpri Chinchwad Municipal Corporation",
    appAcknowldgement: "Application Acknowledgement",
    ackDear: "Dear",
    ackpcmcthanku: "Thank you for using PCMC Pimpri Chinchwad Citizen Service Portal !!",
    ackshortDesc:
      "Your application for Right To Information under PCMC of pune has been successfully submitted.",
    ackRTIAppealshortDesc:
      "Your application for Right To Information Appeal under PCMC of pune has been successfully submitted.",

    ackApplicationSummery: "Application Summary",
    applicationNo: "Application No",
    dateofApplication: "Date of the Application",
    ackplzContactNearestOperator:
      "For any query please contact your nearest operator or the following contact details:",
    ackpcmcAddress: "Mumbai Pune Highway Pimpri Pune 411-018",
    ackPcmcphNo: "Phone Number:91-020-2742-5511/12/13/14",
    ackstateCountry: "Maharashtra, India",
    applicantAddress: "Applicant Address",
    other: "Other",
    rti: "RTI",
    no1: "1)",

    chargeNm: "Charge Name",
    loiNo: "LOI NO",
    rtiApplicationAmt: "For your RTI service on Citizen Seva Portal please your amount Rs",
    determineandPayAmt: "Determine and pay the amount/charge for the service rendered.",
    contactNearestpcmcDivisionalOffice:
      "Or visit the nearest Pimpri Chinchwad Municipal Corporation Divisional Office.",
    serviceAcceptance: "Service Acceptance Letter",
    isApplicationMultiDept: "Is it application under multi department?",
    addDepartment: "Add Department",
    parentRemark: "Parent Remark",
    forwardRemark: "Forward Remark",
    applicationType: "Application Type",

    welcomeToTheDashboard: "Welcome To The Dashboard",
    dashboardTotalCount: "Total Applications",
    dashboardInProgress: "In Progress",
    dashboardLoiGenerated: "Loi Generated",
    dashboardInfoReady: "Information Ready",
    dashboardCompleted: "Completed Application",
    dashboardHearingScheduled: "Hearing Scheduled",

    dashboardTotalAppealCount: "Total Appeal",
    dashboardCompletedAppeal: "Completed Appeal",

    goToAppeal: "Go To Appeal",

    applicationinfoReady: "Application Information Ready",
    appealInfoReady: "Appeal Information Ready",

    ///////////////// FOR REPORTS ADDED BY ANWAR ANSARI /////////
    rtiApplicationRegister: "RTI APPLICATION REGISTER",
    applicationNumber: "Application Number",
    fullName: "Full Name",
    descriptioniOfInformationRequired: "Description Of Information Required",
    dateOfOrderAgainstAppeal: "Date Of Order Against Appeal",
    descriptionOfInformation: "Description Of Information",
    concernDepartmentOrOffice: "Concern Department Or Office",
    reasonOfAppeal: "Reason Of Appeal",
    informationPurpose: "Information Purpose",

    toDateR: "To Date",
    fromDateR: "From Date",

    submit: "Submit",
    downloadEXCELL: "Download Excel",
    downloadPDF: "Download Pdf",
    cancel: "Cancel",
    //////////////////////////////////////////////
    rtiApplicationDashboard: "RTI APPLICATION DASHBOARD",
    rtiAppealRegister: "RTI APPEAL REGISTER",
    subjectName: "Subject Name",
    systemEntryDate: "System Entry Date",
    wards: "Ward",
    bplCardNumber: "BPL Card Number",
    isApplicantBPL: "Is Applicant BPL",
    deptName: "Department Name",
    /////////////////////////////////////////////////
    vivaranPatra01: "Vivaran Patra_01",
    vivaranPatra02: "Vivaran Patra_02",
    vivaranPatra03: "Vivaran Patra_03",
    vivaranPatra04: "Vivaran Patra_04",
    vivaranPatra05: "Vivaran Patra_05",

    monthName: "Month",
    count: "Count",

    periodOfRelatedInformation: "Period Of Related Information",

    year: "Year",
    descriptionOfInformationOfficer: "Description Of Information Officer",

    serialNumber: "Serial Number",
    deptWiseCollection: "DEPARTMENT WISE COLLECTION",
    strFromDate: "From Date",
    strToDate: "To Date",
    total: "Total",
    totalApplication: "Total Application",
    grandTotal: "Grand Total",
    requiredInformationByPostOrPersonallly: "Required Information By Post Or Personallly",
    applicationDate: "Application Date",
    departmentName: "Department Name",
    fileNm: "File Name",
    fileType: "File Type",
    transferRemark: "Transfer Remark",
    viewAttach: "View Attachment",

    //////////////////////rtiapplication wise collection label changes by shubham/////////////////
    appWiseCollection: "APPLICATION WISE COLLECTION",
    applicationName: "Application Name",
    serviceAcceptanceCharges: "Service Acceptance Charges",
    serviceCharges: "Service Charges",
    lastMonthPendingAppCount: "Last Month Pending application Count",
    reportingMonthRecivedAppConunt: "In Reporting Month's received application count",
    reportingMonthClearanceConunt: "In Reporting Month's application clearance count",
    infoDeleverdRTIAppCount: "Information Delevered as per RTI Application Count",
    infoRejectedRTIAppCount: "Information Rejected as per RTI Application Count",
    pendingAppCount: "Pending Application Count",
    reportingMonthRecivedAppealConunt: "In Reporting Month's received appeal count",
    reportingMonthAppealClearanceConunt: "In Reporting Month's appeal clearance count",
    appealAcceptedConunt: "Appeal Accepted Conunt",
    appealRejectedConunt: "Appeal Rejected Conunt",
    pendingAppealConunt: "Pending Appeal Conunt",
    lastMonthPendingAppealCount: "Last Month Pending Appeal Count",
    reportingMonthDeleveredAppealCount: "In Reporting Months Delivered Appeal Count",
    pendingAppealCount: "Pending Appeal Count",
  },

  mr: {
    mediumPrefix: "माध्यम उपसर्ग",
    nameOfMedium: "माध्यमाचे नाव",
    nameOfMediumMr: "माध्यमाचे नाव मराठी",
    infoTransferMediumMaster: "माध्यम मास्टर",
    srNo: "अनु क्रमांक",
    actions: "क्रिया",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    rtiApplication: "आरटीआय अर्ज",
    applicantFirstName: "अर्जदाराचे प्रथम नाव",
    applicantMiddleName: "अर्जदाराचे मधले नाव",
    applicantLastName: "अर्जदाराचे आडनाव",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    pinCode: "पिन कोड",
    contactDetails: "संपर्काची माहिती",
    emailId: "ई-मेल आयडी",
    education: "शिक्षण",
    educated: "शिक्षित",
    unEducated: "अशिक्षित",
    wardKey: "प्रभाग",
    zoneKey: "झोन",
    departmentKey: "विभाग",
    subDepartmentKey: "उपविभाग",
    isApplicantBelowToPovertyLine: "अर्जदार दारिद्र्य रेषेखालील आहे का?",
    bplCardNo: "बीपीएल कार्ड क्र",
    yearOfIssues: "कार्ड वितरीत वर्ष",
    issuingAuthority: "कार्ड मान्यता अधिकारी यांचे नाव",
    informationSubject: "माहितीचा विषय",
    fromDate: "तारखेपासून (संबंधित माहिती)",
    toDate: "तारखेपर्यंत (संबंधित माहिती)",
    description: "आवश्यक असलेल्या माहितीचे वर्णन",
    yes: "होय",
    no: "नाही",
    requiredInfoDeliveryDetails: "आवश्यक माहिती वितरण तपशील",
    byPost: "पोस्टाने",
    personally: "वैयक्तिकरित्या",
    softCopy: "सॉफ्टकॉपी",
    address: "पत्ता",
    departmentKey: "विभागाचे नाव",
    subDepartmentKey: "उपविभागाचे नाव",
    wardKey: "प्रभागाचे नाव",

    rtiAppeal: "आरटीआय आवाहन",
    applicationNo: "अर्ज क्र",
    search: "शोधा",
    descInfoOfOfficer: "माहिती अधिकाऱ्याचा तपशील",
    dateOfOfficialorderAgainstAppeal: "ज्या आदेशाविरुद्ध अपिल केले तो आदेश मिळाल्याची दिनांक",

    descriptionOfInfo: "माहितीचा तपशील",
    reqInfoSubjectAndDesc: "आवश्यक असलेल्या माहितीचे स्वरूप आणि विषय",
    concernOfficerDeptnmWhoseInfoRequired:
      "माहिती ज्या कार्यालयाशी किंवा विभागाशी संबंधित विभागाशी आहे त्याचे नाव",
    requiredInfoPurpose: "ज्यासाठी माहिती आवश्यक आहे ते प्रयोजन",
    reasonForAppeal: "अपिलाचे कारण",
    paymentModeKey: "पेमेंट मोड",
    paymentAmount: "अर्ज शुल्क",
    rtiFileDate: "आरटीआय फाइलची तारीख",
    status: "स्थिती",
    rtiApplicationList: "आरटीआय अर्ज यादी",
    ViewrtiApplication: "आरटीआय अर्ज पहा",

    appealApplicationNo: "अपील अर्ज क्र",
    rtiAppealList: "आरटीआय अपील यादी",
    appealFileDate: "अपील फाइलची तारीख",
    viewrtiAppeal: "आरटीआय अपील पहा",
    currentStatus: "वर्तमान स्थिती",
    loiGenerate: "माहिती शुल्क",
    isLOIGenerated: "माहिती शुल्क/LOI व्युत्पन्न करणे आवश्यक आहे?",
    payment: "पैसे भरा",
    saveAndPay: "जतन करा आणि पैसे द्या",
    completeApplication: "अर्जाची संपूर्ण स्थिती",
    closeModal: "बंद करा",
    loiGenerateBtn: "loi व्युत्पन्न करा",
    serviceName: "सेवेचे नाव",
    noOfPages: "पृष्ठांची संख्या",
    chargeType: "चार्ज प्रकार",
    amount: "रक्कम",
    totalAmount: "एकूण रक्कम",
    remark: "टिप्पणी",
    completeRemark: "पूर्ण टिप्पणी",

    viewLoi: "हेतू पत्र पहा",
    print: "छापणे",
    makePayment: "पैसे भरा",
    applicationReceivedBy: "द्वारे अर्ज प्राप्त झाला",
    cfcuser: "cfc वापरकर्ता",
    citizenuser: "नागरिक वापरकर्ता",
    pcmcportal: "PCMC पोर्टल",
    aaplesarkar: "आपल सरकार",
    ratePerPage: "प्रति पृष्ठ दर",
    fileSize: " फाइल आकार 2MB पेक्षा कमी असणे आवश्यक आहे",
    fileExtension: "फक्त .JPG, .PNG, .JPEG आणि .PDF फाइल्सना अनुमती द्या",
    cancel: "रद्द करा",
    fileUpload: "फाइल अपलोड",
    addDoc: " दस्तऐवज जोडा",
    uploadDoc: "दस्तऐवज/इमेज अपलोड करा",
    informationRemark: "माहिती तयार टिप्पणी",
    inforReady: "माहिती तयार",
    infoPages: "माहिती पृष्ठे",
    selectedReturnMedia: "माहिती रिटर्न मीडिया",

    infoReadyDate: "माहिती तयार तारीख",
    completeDate: "पूर्ण तारीख",
    informationReturnMedia: "माहिती रिटर्न मीडिया",
    hearingSchedule: "सुनावणीचे वेळापत्रक",
    decisionEntry: "निर्णय प्रवेश",

    applicantName: "अर्जदाराचे नाव",
    appealNo: "अपील क्र",
    scheduleDate: "शेड्यूल तारीख",
    scheduleTime: "वेळ शेड्यूल करा",
    venueForHearing: "सुनावणीचे ठिकाण",

    subject: "विषय",
    rtiApplicationNO: "आरटीआय अर्ज क्र",
    decisiontakenInHearing: "सुनावणीत घेतलेला निर्णय",

    decisionStatus: "विभागानुसार निर्णयाची स्थिती",
    decisionOrderAttach: "निर्णय ऑर्डर अपलोड",
    updloadScanInfoDelivered: "वितरित केलेल्या माहितीची स्कॅन प्रत अपलोड करा",
    hearingReschedule: "सुनावणीचे पुन्हा वेळापत्रक",
    completeAppeal: "अपीलची संपूर्ण स्थिती",
    decisionDetails: "निर्णय तपशील",
    documents: "दस्तऐवज",
    completeDoc: "पूर्ण कागदपत्रे",
    RTIApplicationdoc: "आरटीआय अर्जाची कागदपत्रे",
    RTIAppealdoc: "आरटीआय अपील कागदपत्रे",
    forwardApplication: "अग्रेषित/हस्तांतरण अर्ज",
    currentdept: "वर्तमान विभाग",
    currentSubDept: "वर्तमान उपविभाग",
    forwardApplication: "अर्ज फॉरवर्ड करा",
    forwardToDept: "विभागाकडे पाठवा",
    forwardTosubDept: "उपविभागाकडे पाठवा",
    downloadLoiReceipt: "सेवा स्वीकृती पत्र डाउनलोड करा",
    addInfo: "अतिरिक्त माहिती",
    downloadAcknowldgement: "पावती डाउनलोड करा",
    print: "छापणे",
    pimpariChinchwadMaha: "पिंपरी चिंचवड महानगरपालिका",
    appAcknowldgement: "पोच पावती",
    ackDear: "प्रिय",
    ackpcmcthanku: "पिंपरी चिंचवड नागरिक सेवा वापरल्याबद्दल धन्यवाद !!",

    ackshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackRTIAppealshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अपील अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackApplicationSummery: "अर्जाचा तपशील",
    applicationNo: "अर्जाचा क्रमांक",
    dateofApplication: "अर्ज दिनांक",
    ackplzContactNearestOperator:
      "कोणत्याही प्रश्नासाठी कृपया तुमच्या जवळच्या ऑपरेटरशी संपर्क साधा खालील संपर्क तपशील:",
    ackpcmcAddress: "मुंबई पुणे महामार्ग पिंपरी पुणे ४११-०१८",
    ackPcmcphNo: "फोन क्रमांक:९१-०२०-२७४२-५५११/१२/१३/१४",
    ackstateCountry: "महाराष्ट्र, भारत",
    applicantAddress: "अर्जदाराचा पत्ता :",
    rti: "माहिती अधिकार",
    no1: "१)",
    chargeNm: "शुल्काचे नाव",
    loiNo: "हेतू पत्र क्र",
    rtiApplicationAmt: "तुमच्याकडे आरटीआय या सेवेसाठी नागरिक सेवा पोर्टलवर कृपया तुमची रक्कम रुपये",
    determineandPayAmt: "निश्चित करा आणि केलेल्या सेवेची रक्कम/शुल्क भरा.",
    contactNearestpcmcDivisionalOffice: "किंवा जवळील पिंपरी चिंचवड महानगरपलिका विभागीय कार्यालयाला भेट द्या.",

    serviceAcceptance: "सेवा स्वीकृती पत्र",
    isApplicationMultiDept: "बहु विभागांतर्गत अर्ज आहे का?",
    addDepartment: "विभाग जोडा",
    parentRemark: "पॅरेंट टिप्पणी",
    forwardRemark: "अग्रेषित टिप्पणी",

    applicationType: "अर्जाचा प्रकार",

    welcomeToTheDashboard: "डॅशबोर्डवर आपले स्वागत आहे",
    dashboardTotalCount: "एकूण अर्ज",
    dashboardInProgress: "प्रगतीपथावर आहे",
    dashboardLoiGenerated: "सेवा स्वीकृती पत्र व्युत्पन्न",
    dashboardInfoReady: "माहिती तयार",
    dashboardCompleted: "पूर्ण केलेले अर्ज",
    dashboardHearingScheduled: "सुनावणी नियोजित",

    dashboardCompletedAppeal: "पूर्ण केलेले अपील",
    dashboardTotalAppealCount: "एकूण अपील",
    goToAppeal: "अपील वर जा",

    applicationinfoReady: "अर्ज माहिती तयार आहे",
    appealInfoReady: "अपील माहिती तयार आहे",

    ///////////////// FOR REPORTS ADDED BY ANWAR ANSARI /////////
    rtiApplicationRegister: "आरटीआय अर्ज नोंदणी",
    applicationNumber: "अर्ज क्रमांक",
    fullName: "पूर्ण नाव",
    descriptioniOfInformationRequired: "आवश्यक माहितीचे वर्णन",
    dateOfOrderAgainstAppeal: "अपील विरुद्ध आदेशाची तारीख",
    descriptionOfInformation: "माहितीचे वर्णन",
    concernDepartmentOrOffice: "संबंधित विभाग किंवा कार्यालय",
    reasonOfAppeal: "अपीलचे कारण",
    informationPurpose: "माहितीचा उद्देश",

    toDateR: "या तारखे पर्यंत",
    fromDateR: "या तारखेपासून",

    submit: "प्रस्तुत करा",
    downloadEXCELL: "एक्सेल डाउनलोड करा",
    downloadPDF: "पीडीएफ डाउनलोड करा",
    cancel: "रद्द करा",

    //////////////////////////////////////////////
    rtiApplicationDashboard: "आरटीआय ऍप्लिकेशन डॅशबोर्ड",
    rtiAppealRegister: "आरटीआय अपील नोंदणी",
    subjectName: "विषयाचे नाव",
    systemEntryDate: "सिस्टम एंट्रीची तारीख",
    wards: "वार्ड",
    bplCardNumber: "बीपीएल कार्ड क्रमांक",
    isApplicantBPL: "अर्जदार बीपीएल आहे",
    deptName: "विभागाचे नाव",
    /////////////////////////////////////////////////
    vivaranPatra01: "विवरण पत्र_०१",
    vivaranPatra02: "विवरण पत्र_०२",
    vivaranPatra03: "विवरण पत्र_०३",
    vivaranPatra04: "विवरण पत्र_०४",
    vivaranPatra05: "विवरण पत्र_०५",

    monthName: "महिना",
    count: "मोजणे",

    periodOfRelatedInformation: "कालावधी संबंधित माहिती",

    year: "वर्ष",

    descriptionOfInformationOfficer: "माहिती अधिकाऱ्याचे वर्णन",

    serialNumber: "अनुक्रमांक",
    deptWiseCollection: "विभागनिहाय संकलन",
    strFromDate: "या तारखेपासून",
    strToDate: "या तारखेपर्यंत",
    total: "एकूण",
    totalApplication: "एकूण अर्ज",
    grandTotal: "ग्रँड टोटल",
    requiredInformationByPostOrPersonallly: "पोस्टाने किंवा वैयक्तिकरित्या आवश्यक माहिती",
    applicationDate: "अर्जाची तारीख",
    departmentName: "विभागाचे नाव",

    fileNm: "फाईलचे नाव",
    fileType: "दस्तावेजाचा प्रकार",
    transferRemark: "हस्तांतरण टिप्पणी",
    viewAttach: "संलग्नक पहा",

    //////////////////////RTI APPLICATION WISE COLLECTION LABEL CHANGES BY SHUBHAM /////////////////
    appWiseCollection: "अर्जानुसार संकलन",
    applicationName: "अर्जाचे नाव",
    serviceAcceptanceCharges: "सेवा स्वीकृती शुल्क",
    serviceCharges: "सेवा शुल्क",
    lastMonthPendingAppCount: "मागील महिन्यात प्रलंबित अर्जांची संख्या",
    reportingMonthRecivedAppConunt: "रिपोर्टिंग महिन्यात प्राप्त अर्ज संख्या",
    reportingMonthClearanceConunt: "रिपोर्टिंग महिन्याच्या अर्ज मंजुरीच्या संख्येत",
    infoDeleverdRTIAppCount: "आरटीआय अर्जाच्या संख्येनुसार माहिती वितरित केली",
    infoRejectedRTIAppCount: "आरटीआय अर्जाच्या संख्येनुसार माहिती नाकारली",
    pendingAppCount: "प्रलंबित अर्ज संख्या",
    reportingMonthRecivedAppealConunt: "रिपोर्टिंग महिन्यात प्राप्त अपील संख्या",
    reportingMonthAppealClearanceConunt: "रिपोर्टिंग महिन्याच्या अपील मंजुरीच्या संख्येत",
    appealAcceptedConunt: "अपील स्वीकृत संख्या",
    appealRejectedConunt: "अपील नाकारलेली संख्या",
    pendingAppealConunt: "प्रलंबित अपील संख्या",
    lastMonthPendingAppealCount: "गेल्या महिन्यात प्रलंबित अपील गणना",
    reportingMonthDeleveredAppealCount: "वितरीत अपील संख्या अहवाल महिन्यात",
    pendingAppealCount: "प्रलंबित अपील संख्या",
  },
};
