export default {
  en: {

    //multiple file attachment
    attachmentSchema: "*the maximum upload size is 2MB.",
    addDocuments: "Add Documents",
    fileUpload: "File Upload",

    slumAddress : "Slum Owner's details",
    applicantInfo: "Applicant Information",
    additionalFields: "Additional Fields",
    outstandingTaxesAmount: "Outstanding Taxes Amount",
    waterTaxesAmount: "Water Taxes Amount",
    propertyTaxesAmount: "Property Taxes Amount",
    generateDocuments: "Generate Documents",
    selfDeclarationForm: "Self Declaration Form",
    selfAttestation: "Self-Declaration for Self-Attestation",
    completeSiteVisit: "Complete Site Visit",
    cancel: "Cancel",

    hutDetails: "Hut Details",

     ///// HUT Transfer

     hutTransfer: "Hut Transfer",
     searchHutDetails: "Search Hut Details",
     proposedOwner: "Proposed Owner",
     currentOwner : "Current Owner",
     transferType: "Transfer Type",
     marketValue: "Market Value",
     saleValue: "Sale Value",
     zoneName: "Zone",
     hutOwnerDetails: "Hut Owner's Details",
     hutOccupiersDetails: "Hut Occupiers Details",
     hutAddressDetails: "Hut Address Details",
     transferDetails: "Transfer Details",
     generateRejectionLetter: "Generate Rejection Letter",
     details: "Details",
     subTransferType: "Sub Transfer Type",
     transferDate: "Transfer Date",
     viewExistingOwnerName: "View Existing Owner's Name",
     ownerName: "Owner Name",
     addName: "Add Name",
     siteVisitRemark: "Site Visit Remark",
     oldHutNo: "Old Hut No",
     hutArea: "hutArea",
     close: "Close",
     currentOwnerTitle: "Current Owner Title",
     currentOwnerFirstName: "Current Owner First Name",
     currentOwnerMiddleName: "Current Owner Middle Name",
     currentOwnerLastName: "Current Owner Last Name",
     currentOwnerMobileNo: "Current Owner Mobile No",
     currentOwnerAadharNo: "Current Owner Aadhar No",
     proposedOwnerDetails: "Proposed Owner Details",
     proposedOwnerTitle: "Title",
     proposedOwnerFirstName: "First Name",
     proposedOwnerFirstNameMr: "First Name(In Marathi)",
     proposedOwnerMiddleName: "Middle Name",
     proposedOwnerMiddleNameMr: "Middle Name(In Marathi)",
     proposedOwnerLastName: "Last Name",
     proposedOwnerLastNameMr: "Last Name(In Marathi)",
     proposedOwnerMobileNo: "Mobile No",
     proposedOwnerAadharNo: "Aadhar No",
     proposedOwnerEmailId: "Email Id",
     transferRemarks: "Transfer Remarks",
     view: "View",
     scheduleSiteVisitDetails: "Site Visit Details",
     transferHutSiteDetails: "Transfer Hut Site Details",

    // SLUM Master
    slumPrefixEn: "Slum Prefix(In English)",
    slumPrefixMr: "Slum Prefix(In Marathi)",
    citySurveyNo: "City Survey No",
    declarationDate: "Declaration Date",
    declarationOrderNo: "Declaration Order No",
    slumNameEn: "Slum Name(In English)",
    slumNameMr: "Slum Name(In Marathi)",
    areaName: "Area Name",
    areaOfSlum: "Area Of Slum",
    declarationOrder: "Declaration Order",
    noOfHuts: "No Of Huts",
    hutOccupiedArea: "Hut Occupied Area",
    population: "Population",
    malePopulation: "Male Population",
    femalePopulation: "Female Population",
    scPopulation: "SC Population",
    stPopulation: "ST Population",
    slumBoundaryInfo: "Slum Boundary Info",
    slumStatus: "Slum Status",

    hutMaster: "Hut Master",
    hutMember: "Hut Member",
    age: "Age",
    genderKey: "Gender",
    religionKey: "Religion",
    casteKey: "Caste",
    subCasteKey: "Sub Caste",
    educationKey: "Education",
    headOfFamily: "Head of Family",
    collection: "Collection",
    trnCollectionDate: "Transaction Date",
    serviceName: "Service Name",
    receiptNo: "Receipt No",
    collectionCenter: "Collection Center",
    counter: "Counter",
    moduleName: "Module Name",
    userName: "User Name(SAP/NonCore/GIS)",
    receiptType: "Receipt Type",
    refernece: "Reference",
    referenceDate: "Reference Date",
    payerName: "Payer Name",
    address: "Address",
    narration: "Narration",
    paymentMode: "Payment Mode",
    accoundCode: "Account Code",
    codeDescription: "Code Description",
    amount: "Amount",
    totalAmount: "Total Amount",
    receivedAmount: "Received Amount",
    paymentModeKey: "Payment Mode",
    paymentAmount: "Payment Amount",
    transactionStatus: "Transaction Status",
    year: "Year",
    financialYear: "Financial Year",
    viewBill: "View Bill",
    bill: "Bill",
    completeAndIssueOrder: "Complete And Issue Order",

    ownershipTypePrefix: "Ownership Type Prefix",
    fromDate: "From Date",
    toDate: "To Date",
    ownershipType: "Ownership Type",
    ownershipTypeMr: "Ownership Type(मराठी)",
    btnSaveText: "Save",
    remarks: "Remark",

    constructionTypePrefix: "Construction Type Prefix",
    constructionType: "Construction Type",
    constructionTypeMr: "Construction Type(मराठी)",

    usageTypePrefix: "Usage Type Prefix",
    usageType: "Usage Type",
    usageTypeMr: "Usage Type (मराठी)",

    subUsageTypePrefix: "Sub Usage Type Prefix",
    subUsageType: "Sub Usage Type",
    subUsageTypeMr: "Sub Usage Type (मराठी)",

    factorPrefix: "Factor Prefix",
    factorName: "Factor name",
    factorNameMr: "Factor name (मराठी)",
    applicableOn: "Applicable On",

    setFor: "Set for",
    flagName: "Flag name",
    flagNameMr: "Flag name (मराठी)",

    billingCyclePrefix: "Billing Cycle Prefix",
    billingCycle: "Billing Cycle",
    billingCycleMr: "Billing Cycle (मराठी)",

    ageSlabPrefix: "Age Slab Prefix",
    ageSlabName: "Age Slab",
    ageSlabNameMr: "Age Slab (मराठी)",
    rangeOfAge: "Range of Age",

    educationCategoryPrefix: "Education Category Prefix",

    educationCategory: "Education Category",
    educationCategoryMr: "Education Category (मराठी)",
    stream: "Stream",
    std: "Std",
    constructionTypeKey: "Construction Type",
    usageTypeKey: "Usage Type ",
    usageSubTypeKey: "Usage Sub Type ",
    length: "Length",
    breadth: "Breadth",
    height: "Height(Approximate)",

    partNoInList: "Part No. in List ",
    module: "Marriage Registration",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    receipt: "Receipts",
    usertask: "User task",
    serviceName: "Service Name ",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    demo: "",
    //mr
    MrMasters: "Marriage Registration / Masters",
    marriageRegistrationMaritalStatus: "Marriage Registration / Masters / Marital Status",

    pay: "PAY",
    marriageRegistrationrelation: "Marriage Registration / Masters / relation",
    receiptModeDetails: "Receipt Mode Details",
    maritialSatus: "Marital Status",
    relation: "Relation",

    AptBook: "Appointment Slot Booking",
    serviceChargeTypeName: "Service Charge Type Name",

    // field label
    srNo: "Sr. No",
    actions: "Actions",
    statusDetails: "Status Details",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",
    Revert: "Revert Back",
    scheduleSiteVisit: "Schedule Site Visit",
    print:"Print",

    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",

    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    _preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",
    agreeAndProceed: "I Agree And Proceed",

    attachFile: "Attach File",
    srNo: "Sr. No",

    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    download: "Download",
    downloadPhotopass: "Download Photopass",

    //marathi details
    gFNameMr: "",
    gMNameMr: "",
    gLNameMr: "",
    ApplicatCheck1: "If the Applicant is Groom",
    ApplicatCheck2: "If the Applicant is Bride",
    OwnerChkeck: "If the Applicant is Owner",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //mr
    Tnc: "accept term & Condition",
    // instrustion
    onlyMHR:
      " Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.",
    docNote:
      "Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.",
    //table
    newMRtable: "NEW MARRIAGE REGISTRATION ",
    boardtitle: "  Marriage Board Registration ",
    zone: "Zone",
    ward: "Ward",
    Addrees: "Applicant Address :",
    CrrtAdree: "Current Address :",
    parmtAdree: "Permanent Address :",
    personalDetails: "Personal Information :",
    Adress: "Address  :",
    BriNBM: "  (  Name are before marriage)",
    AppliToGroom: "If the Applicant is Groom ",
    AppliToBride: "If the Applicant is Bride",
    marrigeDetails: "  Marriage Details :",
    marrigeDate: "Marriage Date",
    //aprove
    GPhoto: "Groom Photo  ",
    Bphoto: "Bride Photo  ",
    witnessphto1: "Witness 1 Photo  ",
    witnessphto2: "Witness 2 Photo  ",
    witnessphto3: "Witness 3 Photo  ",
    Gthumb: "Groom Thumb  ",
    Bthumb: "Bride Thumb  ",
    witnessthumb1: "Witness 1 Thumb  ",
    witnessthumb2: "Witness 2 Thumb  ",
    witnessthumb3: "Witness 3 Thumb  ",

    //title
    ApplicatDetails: "APPLICANT DETAILS",
    ApplicatName: "Applicant Name",
    groomDetail: "GROOM DETAILS",
    groomParaentDetail: "Groom Parents Details ",
    brideDetails: "BRIDE DETAILS",
    brideParaentDetail: "Bride Parents Details",
    priestDetails: "PRIEST DETAILS",
    witness: "Witness",
    witnessAdd: "Witness",
    witnessDetails: "WITNESS DETAILS",
    documentsUpload: "DOCUMENT UPLOAD",
    boardDetail: "Board Details :",
    otherDetail: "OTHER DETAILS",
    titleInmarathi: "Title In Marathi",
    titleInenglish: "Title In english",

    // viceversa
    titleV: "शीर्षक",
    firstNameV: "प्रथम नावं  ",
    middleNameV: "मधले नावं  ",
    lastNameV: "आडनाव  ",

    //Groom
    // title: 'Title  ',
    firstName: 'First Name  ',
    middleName: 'Middle Name  ',
    lastName: 'Last Name  ',
    title: 'Title ',
    title1: 'Title ',
    firstNameEn: 'First Name (In English) ',
    middleNameEn: 'Middle Name (In English) ',
    lastNameEn: 'Last Name (In English) ',
    titlemr: 'शीर्षक ',
    firstNamemr: 'First Name (In Marathi) ',
    middleNamemr: 'Middle Name (In Marathi) ',
    lastNamemr: 'Last Name (In Marathi) ',

    BirthDate: "Birth Date   ",
    Gender: "Gender",
    AadharNo: "Aadhar No",
    Age: "Age (at the time of marriage)",
    mobileNo: "Mobile / Phone Number",
    phoneNo: "Phone Number",
    email: "Email",

    flatBuildingNo: "Flat/Building No (In English)  ",
    buildingName: "Apartment Name (In English) ",
    roadName: "Road Name (In English) ",
    Landmark: "Landmark (In English) ",
    villageName: "Village Name (In English) ",
    cityName: "City Name / Village Name (In English) ",

    flatBuildingNomr: "Flat/Building No (In Marathi) ",
    buildingNamemr: "Apartment Name (In Marathi) ",
    roadNamemr: "Road Name (In Marathi) ",
    Landmarkmr: "Landmark (In Marathi) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "City Name / Village Name (In Marathi) ",

    State: "State (In English) ",
    statemr: "State (In Marathi) ",
    pincode: "Pin Code",
    Religion1: "Religion by Birth",
    Religion2: " Religion by Adoption",
    StatusOfMarrige: " Status at time of marriage",
    AgeDocument: "Birth Proof Document",
    IdDocument: "Id Document",
    residentialDocument: "Residential Document",
    StatusOfDocument: "Status Of Document",

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: "Place of Marriage (in English)",
    placeofMarriage1: "Place of Marriage (in Marathi)",

    //witness
    address: "Address",
    wRelation: "Witness Relation",
    wDocument: "Witness Document",

    //Document

    DBProof: "Date of Birth Proof",
    ResProof: "Residence Proof",
    IdProof: "ID Proof",

    ResProofW1: "Residence Proof of first witness",
    ResProofW2: "Residence Proof of second witness",
    ResProofW3: "Residence Proof of third witness",
    marrigeRelatedDoc: "Marriage Related Document",
    invetaionCard: "Marriage Invitation card / affidavit ",
    marrigePhotoC: "Marriage Photograph (Couple) ",
    marDrf: "Draft an application on the 100 Rs Stamp paper",
    DivorcePaper: "Valid Divorce Paper (if applicable)",
    DeathC: "Death Certificate (if applicable)",
    certiByReligiousPlc: " Certificate issued by religious place i.e Temple, Mosque etc",
    docFormat: " (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)",
    enterDoc: "Document Name",
    TandC: "",
    //board
    applicantName: "Applicant Name :",
    boardNameT: "Marriage Board Name",
    boardName: "Marriage Board Name (In English)  ",
    boardNamemr: "Marriage Board Name (In Marathi)  ",
    remark: "Remarks",
    documentList: " Documents List",
    ValidtyofMBR: "  Validity Of MBR",
    documentsUploadF: "Documents Upload",

    //button
    back: "Back",
    next: "Next",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",
    submit: "Submit",
    apply: "Apply",
    addFile: "Upload File",

    //table filed
    srNo: "Sr. No",
    ApplicantName: "Applicant Name",
    hName: "Groom Name",
    wName: "Bride Name",
    actions: "Actions",

    //brudcrum
    newMarriageRegistration: "Marriage Registration / New Marriage Registration",
    BoardMarriageRegistration: "Marriage Registration / New Board Registration",

    //ReIssuance of Marriage Certificate

    onlyRIMC: "Re-Issuance of Marriage Certificate",
    mRegNo: "Marriage Reg No",
    marriageDate: "Marriage Date",
    marriageYear: "Marriage Year",
    brideName: "Bride Name",
    groomName: "Groom Name",
    regDate: "Registration Date",

    //Renewal of Marriage Board Registration
    onlyRMBR: "Renewal of Marriage Board Registration",
    mbrName: "Marriage Board Name",
    mbrDate: "Marriage Board Reg Date",
    mbrYear: "Marriage Board Reg Year",
    search: "Search",

    //Application Details

    onlyApplDetail: "Application Details",
    applFName: "Applicant First Name",
    applMName: "Applicant Middle Name",
    applLName: "Applicant Last Name",
    groomFName: "Groom First Name",
    groomMName: "Groom Middle Name",
    groomLName: "Groom Last Name",
    brideFName: "Bride First Name",
    brideMName: "Bride Middle Name",
    brideLName: "Bride Last Name",
    mDate: "Marriage Date",

    //ReIssuance of marriage Certificate
    newRMItable: "ReIssuance of Marriage Certificate",
    applFullName: "Applicant Full Name",
    applicationNo: "Application Number",
    generateLoi: "Generate LOI",

    //Modification in Marriage Board Registration

    onlyMMBR: "Modification in Marriage Board Registration",
    applicationDate: "Application Date",
    registerationDate: "Registeration Date",
    registerationNo: "Registeration No",
    orgName: "Organisation Name",

    //Payment Collection
    bankName: "Bank Name",
    branchName: "Branch Name",
    ifsc: "IFSC Code",
    accountNumber: "Account Number ",
    pay: "Pay",
    exit: "Exit",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    state: "Please enter State (In English)",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    stateMr: "Please enter State (In Marathi)",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (in English)",
    placeMarriageMr: "Please enter Place of Marriage (in Marathi)",
    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",
    witnessAddressC: "Please enter an Address ",
    witnessRelation: "Please enter an Relation. ",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    payment: "Payment",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    //Modification in Marriage Certificate

    onlyMIMC: "Modification of Marriage Certificate",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab :",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark on application",
    APPROVE: "APPROVE",
    photo: "Photo",

    REASSIGN: "REASSIGN",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    module: "Legal Case Management System",
    formType: "masters",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",

    masterPath: "Legal Case / Master ",
    transactionPath: "Legal Case / Transaction ",

    courtPath: "Legal Case / Master /Court",
    advocatePath: "Legal Case / Master /Advocate",
    serviceHierachyPath: "Legal Case / Master / Service Hierachy",
    caseTypePath: "Legal Case/ Master / Case Type",
    caseSubTypePath: "Legal Case / Master / Case Sub Type",
    caseStagesPath: "Legal Case/ Master / Case Type",
    employeeAndUserCreationPath: "Legal Case / Master / Employee and User Creation",
    counterSchedulingPath: "Legal Case / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath: "Legal Case / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath: "Legal Case / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath: "Legal Case / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "Legal Case / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",

    //other labels
    complaintType: "Subject/Complaint Type *",
    complaintSubType: "Complaint Sub Type *",
    status: "Status *",
    mediaName: "Media Name *",
    mediaPrefix: "Prefix *",
    remark: "Remark",
    eventType: "Event Type",
    eventDate: "Event Date *",
    alertDateTime: "Alert Date & Time *",
    description: "Description",
    courtName: "Court Name *",
    address: "Address *",
    roadName: "Road Name *",
    landmark: "Landmark *",
    cityOrVillage: "City / Village *",
    pincode: "Pincode *",
    area: "Area *",
    name: "Name *",
    mobile: "Mobile No. *",
    phone: "Phone No. *",
    email: "E-mail *",
    aadharNo: "Aadhar No. *",
    panNo: "Pan No. *",
    advocateCreation: "Advocate Created Successfully",
    advocateDetails: "Advocate Details",
    bankDetails: "Bank Details",
    documentUpload: "Document Upload",
    title: "Title *",
    fname: "First Name *",
    mname: "Middle Name *",
    lname: "Last Name *",
    advocateCategory: "Advocate Category *",
    nameOfBarCouncil: "Name Of Bar Council *",
    remarks: "Remarks *",
    bankName: "Bank Name *",
    branchName: "Branch Name *",
    accountNo: "Account No. *",
    bankIFSC: "Bank IFSC code *",
    bankMICR: "Bank MICR code *",
    application: "Application:",
    aadharCard: "Aadhar Card:",
    panCard: "Pan Card:",
    barCouncilCertificate: "Bar Council Certificate:",
    bankPassbook: "Bank Passbook:",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    hutPrefix: "Hut Prefix",
    zoneKey: "Zone Name",
    hutNo: "Hut No",
    slumKey: "Slum",
    areaOfHut: "Area of Hut in Sq.Ft.(Approximate)",
    ownershipKey: "Ownership",

    rehabilitation: "Rehabilitation",
    eligibility: "Eligibility",
    waterConnection: "Water Connection",
    noOfFloors: "Total No. of Floors (G+)",
    maleCount: "Male Count ",
    femaleCount: "Female Count",
    totalFamilyMembers: "Total Family Members",
    areaKey: "Area Name",
    villageKey: "Village Name",
    cityKey: "City Name",
    pincode: "Pincode",
    lattitude: "Lattitude",
    longitude: "Longitude",
    assemblyConstituency: "Name of Assembly constituency",
    correction: "Correction",
    remarks: "Remark",
    applicationNo: "Application No",
    applicationDate: "Application Date",
    hutNo: "Hut No.",
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    photo: "Upload Photo",
    mobileNo: "Mobile No.",
    aadharNo: "Aadhar No.",
    emailId: "Email ID",
    slumName: "Slum Name",
    area: "Area",
    village: "Village",
    city: "City",
    pincode: "Pincode",
    lattitude: "Lattitude",
    longitude: "Longitude",
    title: "Title",
    noOfCopies: "No. of Copies",
    asOnDate: "As on Date",
    feesApplicable: "Fees Applicable",
    details: "Details",
    outstandingTaxesAmount: "Outstanding Taxes Amount",
    addApplicant: "Add Applicant",
    fullName: "Full Name",

    save: "Save",
    clear: "Clear",
    exit: "exit",
    search: "Search",

    srNo: "Sr No.",
    action: "Actions",

    // issuance of photopass

    searchSlumDetails: "Search Slum Details",
    hutNo: "Hut Number",
    insuranceOfPhotopass: "Issuance Of Photopass",
    noOfCopies: "No Of Copies",
    scheduleDateTime: "Schedule Date-Time",
    rescheduleDateTime: "Reschedule Date-Time",
    visitDateTime: "Visit Date-Time",
    back: "Back",
    photopassSiteDetails: "Photopass Site Details",
    fileUploadValidationError: "You can add only 5 Images",
    geocode: "Geo Code",
    attachImages: "Attach Images",
    uploadSiteVisitImages: "Upload site visit images",
    generateInspectionReport: "Generate Inspection Report",
    generatedInspectionReport: "Generated Inspection Report",
    viewPhoto: "View Photo",
    generate: "Generate",
    remarks: "Remark",
    Complete: "Complete",
    issuePhotopass : "Issue Photopass",
    loiDetails: "LOI Payment Details",
    transactionDateTime: "Transaction Date-Time",
    inssuranceOfPhotopassDetails: "Issuance Of Photopass Details",
    generateReports: "Generate Reports",
    clerkApprovalRemark: "Clerk Approval Remark",
    headClerkApprovalRemark: "Head Clerk Approval Remark",
    officeSuperintendantApprovalRemark: "Office Superintendant Approval Remark",
    administrativeOfficerApprovalRemark: "Administrative Officer Approval Remark",
    assistantCommissionerApprovalRemark: "Assistant Commissioner Approval Remark",

    //acknowledgement
    pimpariChinchwadMaha: "Pimpri Chinchwad Municipal Corporation",
    appAcknowldgement: "Application Acknowledgement",
    ackDear: "Dear",
    ackpcmcthanku: "Thank you for using PCMC Pimpri Chinchwad Citizen Service Portal !!",
    ackshortDesc:
      "Your application for Issuance of Photopass under PCMC of pune has been successfully submitted.",
    ackHutTransferShortDesc:
      "Your application for Hut Transfer under PCMC of pune has been successfully submitted.",

    ackApplicationSummery: "Application Summary",
    applicationNo: "Application No",
    dateofApplication: "Date of the Application",
    ackplzContactNearestOperator:
      "For any query please contact your nearest operator or the following contact details:",
    ackpcmcAddress: "Mumbai Pune Highway Pimpri Pune 411-018",
    ackPcmcphNo: "Phone Number:91-020-2742-5511/12/13/14",
    ackstateCountry: "Maharashtra, India",
    applicantAddress: "Applicant Address",
    other: "Other",
    no1: "1)",
    chargeNm: "Charge Name",
    loiNo: "LOI NO",
    rtiApplicationAmt: "For your Issuance of Photopass on Citizen Seva Portal please your amount Rs",
    hutTransferAmt: "For your Transfer of Hut on Citizen Seva Portal please your amount Rs",
    determineandPayAmt: "Determine and pay the amount/charge for the service rendered.",
    contactNearestpcmcDivisionalOffice:
      "Or visit the nearest Pimpri Chinchwad Municipal Corporation Divisional Office.",
    serviceAcceptance: "Service Acceptance Letter",
    isApplicationMultiDept: "Is it application under multi department?",
    addDepartment: "Add Department",
    parentRemark: "Parent Remark",
    forwardRemark: "Forward Remark",
    applicationType: "Application Type",
    departmentKey: "Department",

  },

  mr: {
    loiDetails: "LOI देयक तपशील",
    transactionDateTime: "व्यवहाराची तारीख-वेळ",
    inssuranceOfPhotopassDetails: "फोटोपास विमाचा तपशील ",
    generateReports: "अहवाल तयार करा",
    clerkApprovalRemark: "लिपिक मंजूरी टिप्पणी",
    headClerkApprovalRemark: "मुख्य लिपिक मंजूरी टिप्पणी",
    officeSuperintendantApprovalRemark: "कार्यालय अधीक्षक अनुमोदन टिप्पणी",
    administrativeOfficerApprovalRemark: "प्रशासकीय अधिकारी अनुमोदन टिप्पणी",
    assistantCommissionerApprovalRemark: "सहाय्यक आयुक्त अनुमोदन टिप्पणी",
    viewPhoto: "फोटो पहा",

    remarks: "टिप्पणी",
    generateInspectionReport: "तपासणी अहवाल तयार करा",
    generatedInspectionReport: "तपासणी अहवाल तयार केला",
    uploadSiteVisitImages: "साइट भेट प्रतिमा अपलोड करा",
    attachImages: "प्रतिमा संलग्न करा",
    geocode: "भौगोलिक कोड",
    photopassSiteDetails: "फोटोपास साइट तपशील",
    fileUploadValidationError: "आपण फक्त 5 प्रतिमा जोडू शकता",
    scheduleDateTime: "तारीख-वेळ शेड्यूल करा",
    rescheduleDateTime: "तारीख-वेळ पुन्हा शेड्यूल करा",
    visitDateTime: "भेटीची तारीख-वेळ",
    back: "मागे",
    generate: "उत्पन्न करा",
    generateDocuments: "कागदपत्रे तयार करा",
    selfDeclarationForm: "स्वयंघोषणा प्रपत्र",
    selfAttestation: "स्वयं - साक्षांकनासाठी स्वयंघोषणापत्र ",

    noOfCopies:"प्रतींची संख्या",
    slumAddress: "झोपडपट्टी मालकाचा तपशील",
    applicantInfo: "अर्जदाराची माहिती",
    additionalFields: "अतिरिक्त फील्ड",
    outstandingTaxesAmount: "थकबाकी कर रक्कम",
    waterTaxesAmount:"पाणीकराची रक्कम",
    propertyTaxesAmount: "मालमत्ता कर रक्कम",
    completeSiteVisit: "साइट भेट पूर्ण",
    cancel: "रद्द करा",

    ///// HUT Transfer

    hutTransfer: "झोपडी हस्तांतरण",
    proposedOwner: "प्रस्तावित मालक",
    currentOwner : "वर्तमान मालक",
    transferType: "हस्तांतरण प्रकार",
    marketValue: "बाजार भाव",
    saleValue: "विक्री मूल्य",
    searchHutDetails: "झोपडी तपशील शोधा",
    zoneName: "झोन",
    hutOwnerDetails: "झोपडी मालक तपशील",
    hutOccupiersDetails: "झोपडी व्यापणाऱ्यांचे तपशील",
    hutAddressDetails: "झोपडीचा पत्ता तपशील",
    transferDetails: "तपशील हस्तांतरित करा",
    generateRejectionLetter: "नकार पत्र उत्पन्न करा",
    details: "तपशील",
    subTransferType: "उपहस्तांतरण प्रकार",
    transferDate: "हस्तांतरण तारीख",
    viewExistingOwnerName: "विद्यमान मालकाचे नाव पहा",
    ownerName: "मालकाचे नाव",
    addName: "नाव जोडा",
    siteVisitRemark:"साइट भेट टिप्पणी",
    hutNo: "झोपडी क्र",
    oldHutNo: "जुनी झोपडी क्र",
    hutArea: "झोपडी क्षेत्र",
    close: "बंद",
    currentOwnerTitle: "वर्तमान मालक शीर्षक",
    currentOwnerFirstName: "वर्तमान मालकाचे नाव",
    currentOwnerMiddleName: "वर्तमान मालकाच्या वडिलांचे नाव",
    currentOwnerLastName: "वर्तमान मालकाचे आडनाव",
    currentOwnerMobileNo: "वर्तमान मालकाचा मोबाईल क्र",
    currentOwnerAadharNo: "वर्तमान मालक आधार क्र",
    proposedOwnerDetails: "प्रस्तावित मालकाचा तपशील",
    proposedOwnerTitle: "शीर्षक",
    proposedOwnerFirstName: "पहिले नाव",
    proposedOwnerFirstNameMr: "पहिले नाव(मराठीत)",
    proposedOwnerMiddleName: "वडीलांचे नावं",
    proposedOwnerMiddleNameMr: "वडीलांचे नावं(मराठीत)",
    proposedOwnerLastName: "आडनाव",
    proposedOwnerLastNameMr: "आडनाव(मराठीत)",
    proposedOwnerMobileNo: "मोबाईल क्र",
    proposedOwnerAadharNo: "आधार क्र",
    proposedOwnerEmailId: "ई-मेल आयडी",
    transferRemarks: "हस्तांतरित टिप्पण्या",
    scheduleSiteVisitDetails: "साइट भेट तपशील",
    transferHutSiteDetails: "हस्तांतरण झोपडी साइट भेट तपशील",

    //SLUM master
    slumPrefixEn: "झोपडपट्टी उपसर्ग(इंग्रजी)",
    slumPrefixMr: "झोपडपट्टी उपसर्ग(मराठी)",
    citySurveyNo: "शहर सर्वेक्षण क्र",
    declarationDate: "घोषणा तारीख",
    declarationOrderNo: "घोषणा आदेश क्रमांक",
    slumNameEn: "झोपडपट्टीचे नाव (इंग्रजी)",
    slumNameMr: "झोपडपट्टीचे नाव (मराठी)",
    areaName: "क्षेत्राचे नाव",
    areaOfSlum: "झोपडपट्टीचा परिसर",
    declarationOrder: "घोषणा आदेश",
    noOfHuts: "झोपड्यांची संख्या",
    hutOccupiedArea: "झोपडी व्यापलेले क्षेत्र",
    population: "लोकसंख्या",
    malePopulation: "पुरुष लोकसंख्या",
    femalePopulation: "महिला लोकसंख्या",
    scPopulation: "SC लोकसंख्या",
    stPopulation: "ST लोकसंख्या",
    slumBoundaryInfo: "झोपडपट्टीची माहिती",
    slumStatus: "झोपडपट्टीची स्थिती",

    hutMaster: "झोपडी मास्टर",
    hutMember: "झोपडी सदस्य",
    age: "वय",
    genderKey: "लिंग",
    religionKey: "धर्म",
    casteKey: "जात",
    subCasteKey: "पोटजाती",
    educationKey: "शिक्षण",
    headOfFamily: "कुटुंब प्रमुख",
    collection: "संकलन",
    trnCollectionDate: "व्यवहाराची तारीख",
    serviceName: "सेवेचे नाव",
    receiptNo: "पावती क्र",
    collectionCenter: "संकलन केंद्र",
    counter: "काउंटर",
    moduleName: "मॉड्यूलचे नाव",
    userName: "वापरकर्ता नाव(SAP/NonCore/GIS)",
    receiptType: "पावती प्रकार",
    refernece: "संदर्भ",
    referenceDate: "संदर्भ तारीख",
    payerName: "देयकाचे नाव",
    address: "पत्ता",
    narration: "कथन",
    payment: "पेमेंट",
    paymentMode: "पेमेंट मोड",
    accoundCode: "खाते कोड",
    codeDescription: "कोड वर्णन",
    amount: "रक्कम",
    totalAmount: "एकूण रक्कम",
    receivedAmount: "प्राप्त रक्कम",
    paymentModeKey: "देयक प्रकार",
    paymentAmount: "देयक रक्कम",
    transactionStatus: "व्यवहार स्थिती",
    year: "वर्ष",
    financialYear: "आर्थिक वर्ष",
    viewBill: "बील पहा",
    bill: "बील",
    completeAndIssueOrder: "पूर्ण करा आणि ऑर्डर जारी करा",

    ownershipTypePrefix: "मालकी प्रकार उपसर्ग",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    ownershipType: "मालकीचा प्रकार",
    ownershipTypeMr: "मालकीचा प्रकार (मराठी)",
    btnSaveText: "जतन करा",
    remark: "टिप्पणी",
    scheduleSiteVisit: "साइट भेटीचे वेळापत्रक",

    constructionTypePrefix: "बांधकाम प्रकार उपसर्ग",
    constructionType: "बांधकाम प्रकार",
    constructionTypeMr: "बांधकाम प्रकार (मराठी)",

    usageTypePrefix: "वापर प्रकार उपसर्ग",
    usageType: "वापर प्रकार",
    usageTypeMr: "वापर प्रकार (मराठी)",

    subUsageTypePrefix: "उप वापर प्रकार उपसर्ग",
    subUsageType: "उप वापर प्रकार",
    subUsageTypeMr: "उप वापर प्रकार (मराठी)",

    factorPrefix: "घटक उपसर्ग",
    factorName: "घटक नाव",
    factorNameMr: "घटक नाव (मराठी)",
    applicableOn: "वर लागू",

    setFor: "च्यासाठी ठेवा",
    flagName: "ध्वज नाव",
    flagNameMr: "ध्वज नाव (मराठी)",

    billingCyclePrefix: "बिलिंग सायकल उपसर्ग",
    billingCycle: "बिलिंग सायकल",
    billingCycleMr: "बिलिंग सायकल (मराठी)",

    ageSlabPrefix: "वय स्लॅब उपसर्ग",
    ageSlabName: "वय स्लॅब",
    ageSlabNameMr: "वय स्लॅब(मराठी)",
    rangeOfAge: "वयाची श्रेणी",

    educationCategoryPrefix: "शिक्षण श्रेणी उपसर्ग",

    educationCategory: "शिक्षण श्रेणी उपसर्ग",
    educationCategoryMr: "शिक्षण श्रेणी उपसर्ग (मराठी)",
    stream: "प्रवाह",
    std: "इयत्ता",

    onlyeng: "फक्त इंग्लिश मध्ये",
    onlymarathi: "फक्त मराठी मध्ये",
    APPROVE: "मंजूर करा",
    photo: "छायाचित्र",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    newLabel: "नवीन माहिती",
    onlyMIMC: "विवाह प्रमाणपत्रात बदल",
    State: "स्टेट (इंग्लिश मध्ये) ",
    statemr: "स्टेट (मराठी मध्ये) ",
    UploadFile: "फाइल अपलोड करा",
    electrbill: "वीज बिल",
    OtherDocument: "इतर दस्तऐवज",
    rationcard: "रेशान कार्ड",
    adharcard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    boardorgphotocpy: "संस्था किंवा मंडळची दस्तऐवज",
    boardheadphoto: "मंडळाच्या प्रमुख व्यक्तीच छायाचित्र",
    document: "दस्तऐवज",
    Owneraddress: " मंडळच्या प्रमुख व्यक्तीचा पत्ता  :",
    OwnerDetails: "मंडळच्या प्रमुख व्यक्तीची माहिती",
    titleInmarathi: "शीर्षक मराठी मध्ये",
    titleInenglish: "शीर्षक इंग्लिश मध्ये",
    OwnerChkeck: "जर अर्जादारच विवाह मंडळाचा प्रमुख असेल",
    apply: "जतन करा",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    EnterDocName: "कृपया दस्तऐवजाच नाव भरा ",
    witnessAddressC: "कृपया पत्ता भरा  ",
    witnessRelation: "कृपया साक्षीदारशी नाते भरा  ",

    birthProf: "कृपया जन्म तारीख पुरावा निवडा ",
    ResideProof: "कृपया रहिवासाचा पुरावा निवडा ",
    IdentyProof: "कृपया ओळखपत्र पुरावा निवडा ",
    // //Remarks
    selectReligionby: "कृपया जन्माने धर्म निवडा ",
    selectAdoptionby: "कृपया दत्तक घेऊन धर्म निवडा ",
    selectStatusAt: "कृपया लग्नाच्या वेळची स्थिती निवडा ",

    enterAge: "कृपया वय भरा ",
    selectGender: "कृपया लिंग निवडा ",
    selectZone: "कृपया झोन निवडा",
    selectWard: "कृपया वार्ड निवडा",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश मध्ये)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश मध्ये)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)",

    enterFNameMr: "कृपया पहिले नाव भरा (मराठी मध्ये) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी मध्ये)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी मध्ये)",

    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)",
    enterRoadName: "कृपया रस्त्याचे नाव भरा (इंग्लिश मध्ये)",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा (इंग्लिश मध्ये)",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश मध्ये)",
    state: "कृपया  राज्य नाव भरा (इंग्लिश मध्ये)",

    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)",
    enterLandmarkMr: "कृपया  महत्त्वाची खूण भरा  (मराठी मध्ये)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)",
    stateMr: "कृपया  राज्य नाव भरा  (मराठी मध्ये)",

    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",

    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    //mr
    selectWard: "कृपया प्रभाग निवडा ",
    selectZone: "कृपया झोन निवडा ",
    selectTitle: "कृपया शीर्षक निवडा ",
    placeMarriage: "कृपया  विवाहाचा ठिकाण भरा (इंग्लिश मध्ये)",
    placeMarriageMr: "कृपया  विवाहाचा ठिकाण भरा  (मराठी मध्ये)",

    pay: "पैसे भरा",
    titlemr: "शीर्षक ",
    title1: "Title ",
    newMRtable: "नवीन विवाह नोंदणी",
    module: "विवाह नोंदणी",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    masters: "मास्टर्स",
    transactions: "ट्रैन्ज़ैक्शन",
    reports: "अहवाल",
    receipt: "पावती",
    usertask: "User task",
    serviceChargeTypeName: "सेवा शुल्काचा प्रकार",

    chargeName: "शुल्काचा प्रकार",
    masters: "मास्टर्स",
    masterPath: "तक्रार निरीक्षण / मास्टर्स",

    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    //mr
    MrMasters: "विवाह नोंदणी/ मास्टर ",
    marriageRegistrationMaritalStatus: "विवाह नोंदणी/ मास्टर / वैवाहिक स्थिती",

    marriageRegistrationrelation: "विवाह नोंदणी/ मास्टर / नाते",

    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",

    documentUpload: "दस्तऐवज अपलोड",
    addFile: "फाइल जोडा",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    verify: "सत्यापित",
    reject: "नाकारा",
    noFileFound: "कोणतीही फाइल आढळली नाही",
    verified: "तपासून झाले",

    upload: "अपलोड करा",
    next: "पुढे",
    preview: "पूर्वावलोकन",
    _preview: "पूर्वावलोकन",
    agreeAndProceed: "सहमत आणि पुढे जा",

    attachFile: "फाईल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    serviceName: "सेवेचे नाव ",
    //titles

    calendarScheduling: " दिनदर्शिका शेड्युलिंग",
    maritialSatus: "वैवाहिक स्थिती",
    relation: "नाते",
    statusDetails: "स्थिती तपशील",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    Revert: "परत पाठवा",
    Complete: "पूर्ण",
    issuePhotopass: "फोटोपास जारी करा",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ApplicatCheck1: "जर अर्जदार वर असेल तर",
    ApplicatCheck2: "जर अर्जदार वधु असेल तर",

    transactions: " ट्रैन्ज़ैक्शन",
    transactionPath: "कायदेशीर प्रकरण/  ट्रैन्ज़ैक्शन ",

    //mr
    // instrustion
    onlyMHR:
      "महाराष्ट्रातील विवाहाचे रजिस्ट्रेशन केले जाते आणि वधू किंवा वर यापैकी एक जण पिंपरी चिंचवड महानगर पालिकेच्या हद्दी मधील रहिवासी असावा.",
    docNote:
      "आयडी पुरावा, रहिवासी पुरावा, वयाचा पुरावा वेगळा असावा, (लग्नाच्या वेळी स्थिती असल्यास मागील स्टेटस प्रूफमध्ये मूल्य असते विधवा/विधुर किंवा घटस्फोटीत आहे) आधारकार्ड पुरावा जोडल्यास व नागरिक भाड्याने राहत असलेस नोंदणीकृत करारनामा आवश्यक आहे.",

    //aprove
    GPhoto: "वरचा फोटो  ",
    Bphoto: "वधुचा फोटो  ",
    witnessphto1: "साक्षीदारचा १ फोटो  ",
    witnessphto2: "साक्षीदारचा २ फोटो  ",
    witnessphto3: "साक्षीदारचा ३ फोटो  ",
    Gthumb: "वरचा अंगठाचा ठसा  ",
    Bthumb: "वधुचा अंगठाचा ठसा  ",
    witnessthumb1: "साक्षीदारचा १ अंगठाचा ठसा  ",
    witnessthumb2: "साक्षीदारचा २ अंगठाचा ठसा  ",
    witnessthumb3: "साक्षीदारचा ३ अंगठाचा ठसा  ",

    //table
    Tnc: "नियम व अटी",
    newMRtable: "नवीन विवाह नोंदणी",
    boardtitle: "विवाह मंडळाची माहिती",
    zone: "झोन",
    ward: "वार्ड",
    Addrees: "अर्जदाराचा रहिवासाचा पत्ता :",

    CrrtAdree: "सध्याचा रहिवासाचा पत्ता :",
    parmtAdree: "कायमचा रहिवासाचा पत्ता :",
    personalDetails: "वैयक्तिक माहिती :",
    Adress: "पत्ता :",
    BriNBM: "  (  लग्नाआधीचे नाव)",
    AppliToGroom: "",
    AppliToBride: "",
    marrigeDetails: "विवाहाची माहिती :",
    marrigeDate: "विवाहाची दिनांक",

    //title
    ApplicatDetails: "अर्जदाराची माहिती",
    ApplicatName: "अर्जदाराच नाव",
    groomDetail: "वराची माहिती",
    groomParaentDetail: "वराच्या पालकांची माहिती",
    brideDetails: "वधुची माहिती",
    brideParaentDetail: "वधुच्या पालकांची माहिती",
    priestDetails: "पुजारी माहिती",
    witness: "साक्षीदार",
    witnessDetails: "साक्षीदार माहिती",
    documentsUpload: "दस्तऐवज अपलोड",
    boardDetail: "विवाह मंडळाची माहिती :",
    otherDetail: "इतर तपशील",

    // viceversa
    titleV: "Title  ",
    firstNameV: "First Name  ",
    middleNameV: "Middle Name  ",
    lastNameV: "Last Name  ",

    //groom
    title: "शीर्षक",
    firstName: "प्रथम नाव (इंग्लिश मध्ये) ",
    middleName: "मधले नाव (इंग्लिश मध्ये) ",
    lastName: "आडनाव (इंग्लिश मध्ये) ",
    firstNamemr: "प्रथम नाव (मराठी मध्ये) ",
    middleNamemr: "मधले नाव (मराठी मध्ये) ",
    lastNamemr: "आडनाव (मराठी मध्ये) ",
    BirthDate: "जन्म दिनांक  ",
    Gender: "लिंग",
    AadharNo: "आधार नंबर",
    Age: "वय (लग्नाच्या वेळीचे वय)",
    mobileNo: "दूरध्वनी क्रमांक",
    phoneNo: "फोन नंबर",
    email: "ई-मेल",

    flatBuildingNo: "फ्लॅट नंबर (इंग्लिश मध्ये) ",
    buildingName: "अपार्टमेंट नाव (इंग्लिश मध्ये) ",
    roadName: "गल्लीचे नाव (इंग्लिश मध्ये) ",
    Landmark: "जमीन चिन्ह (इंग्लिश मध्ये) ",
    villageName: "Village Name (In English) ",
    cityName: "शहराचे नाव (इंग्लिश मध्ये) ",

    flatBuildingNomr: "फ्लॅट नंबर (मराठी मध्ये) ",
    buildingNamemr: "अपार्टमेंट नाव (मराठी मध्ये) ",
    roadNamemr: "गल्लीचे नाव (मराठी मध्ये) ",
    Landmarkmr: "जमीन चिन्ह (मराठी मध्ये) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "शहराचे नाव (मराठी मध्ये) ",

    // flatBuildingNo: 'फ्लॅट नंबर',
    // buildingName: 'अपार्टमेंट नाव',
    // roadName: 'गल्लीचे नाव',
    // Landmark: 'जमीन चिन्ह',
    // villageName: 'गावाचे नाव ',
    // cityName: 'शहराचे नाव',
    state: "राज्य (इंग्लिश मध्ये) ",
    statemr: "राज्य (मराठी मध्ये)  ",

    pincode: "पिन कोड",
    Religion1: "जन्माने धर्म",
    Religion2: "दत्तक घेऊन धर्म",
    StatusOfMarrige: "लग्नाच्या वेळची स्थिती",
    AgeDocument: "वयाचे कागदपत्र",
    IdDocument: "ओळख कागदपत्र ",
    residentialDocument: "रहिवाशी कागदपत्र",
    StatusOfDocument: "कागदपत्र स्थिती ",

    //groomFather
    firstNameF: "वडिलांचं प्रथम नाव  ",
    middleNameF: "वडिलांचं मधले नाव  ",
    lastNameF: "वडिलांचं आडनाव  ",
    AgeF: "वडिलांच वय",
    mobileNoF: "वडिलांचं दूरध्वनी क्रमांक",
    AadharNoF: "वडिलांचं आधार नंबर",

    //groomMother
    firstNameM: "आईचे प्रथम नाव  ",
    middleNameM: "आईचे मधले नाव  ",
    lastNameM: "आईचे आडनाव  ",
    AgeM: "आईचे वय",
    mobileNoM: "आईचे दूरध्वनी क्रमांक",
    AadharNoM: "आईचे आधार नंबर",

    //prist
    placeofMarriage: "लग्नाचे ठिकाण (इंग्लिश मध्ये)",
    placeofMarriage1: "लग्नाचे ठिकाण (मराठी मध्ये) ",

    //witness
    address: "पत्ता",
    wRelation: "साक्षीदारशी नाते",
    wDocument: "साक्षीदाराचे कागदपत्र",
    witnessAdd: "साक्षीदार जोडा",

    //Document

    DBProof: "जन्म तारीख पुरावा",
    ResProof: "रहिवासाचा पुरावा",
    IdProof: "ओळखपत्र पुरावा",
    ResProofW1: "प्रथम साक्षीदार रहिवासाचा पुरावा",
    ResProofW2: "द्वितीय साक्षीदार रहिवासाचा पुरावा",
    ResProofW3: "तृतिय साक्षीदार रहिवासाचा पुरावा",
    marrigeRelatedDoc: "विवाह संबंधित दस्तऐवज",
    invetaionCard: "विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र ",
    marrigePhotoC: "विवाह छायाचित्र (जोडीचे) ",
    marDrf: "१०० रुपयांच्या स्टॅम्प पेपरवर अर्जाचा मसुदा तयार करा",
    DivorcePaper: "वैध घटस्फोट कागद (लागू असल्यास)",
    DeathC: "मृत्यू प्रमाणपत्र (लागू असल्यास)",
    certiByReligiousPlc: " मंदिर, मशीद इ. धार्मिक स्थळाद्वारे जारी केलेले प्रमाणपत्र",
    docFormat: " (फक्त jpg.jpeg.png.bmp.pdf फाइल अपलोड करण्याची परवानगी आहे. फोटो आकार कमाल 100 kb)",
    enterDoc: "दस्तऐवजाच नाव ",

    //board
    applicantName: "अर्जादारच नाव :",
    boardNameT: "विवाह मंडळचे नाव",
    boardName: "विवाह मंडळचे नाव (इंग्लिश मध्ये) ",
    boardNamemr: "विवाह मंडळचे नाव (मराठी मध्ये) ",

    remark: "शेरा",
    documentList: "दस्तऐवज यादी",
    ValidtyofMBR: "विवाह मंडळाची अंतिम वैधता",
    documentsUploadF: "दस्तऐवज अपलोड",
    TandC: "",
    //button
    back: "मागे",
    next: "पुढे",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    submit: "प्रस्तुत करणे",
    addFile: "फाइल जोडा",

    //table filed
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    hName: "वरचे नाव",
    wName: "वधूचे नाव",
    ApplicantName: "अर्जादारच नाव",

    //brudcrum
    newMarriageRegistration: "विवाह नोंदणी / नवीन विवाह नोंदणी ",
    BoardMarriageRegistration: "विवाह मंडळ नोंदणी / नवीन विवाह मंडळ नोंदणी ",

    //module: 'शहर नियोजन',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    // master: 'मास्टर्स',
    // transactions: 'व्यवहार',
    // report: 'अहवाल',
    // masterPath: 'शहर नियोजन/ मास्टर ',
    // transactionPath: 'शहर नियोजन/ व्यवहार ',
    // reportPath: 'शहर नियोजन/ अहवाल ',

    // //breadcrum
    // landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
    // tdrZoneGatAndVillageMappingPath:
    //   'शहर नियोजन/ मास्टर / टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntryPath:
    //   'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignationPath:
    //   'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',

    // //titles
    // landReservation: 'जमीन आरक्षण',
    // tdrZoneGatAndVillageMapping: 'टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',

    // //other labels
    // landReservationID: 'जमीन आरक्षण क्र',
    // reservationName: 'आरक्षणाचे नाव',
    // reservationNameEng: 'आरक्षणाचे नाव इंग्रजीत',
    // reservationNameMr: 'आरक्षणाचे नाव मराठीत',
    // surveyNumber: 'सर्वेक्षण क्र',
    // landReservationLegend: 'जमीन आरक्षण आख्यायिका',
    // reservationAreaInHector: 'हेक्टर मध्ये आरक्षण क्षेत्र',
    // landInPossession: 'ताब्यात जमीन',
    // remark: 'टिप्पणी',
    // villageName: 'गावाचे नाव',
    // gatName: 'गटाचे नाव',
    // zoneName: 'झोनचे नाव',
    // landReservationName: 'जमीन आरक्षण नाव',
    // citySurveyNo: 'शहर सर्वेक्षण क्र',
    // reservationNo: 'आरक्षण क्र',
    // landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
    // landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
    // ddtp: 'डी.डी.टी.पी',
    // deAndTp: 'उपअभियंता /नगर नियोजक',
    // atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',

    // attachFile: 'फाईल जोडा',
    // srNo: 'अनु क्र',
    // actions: 'क्रिया ',

    // //buttons
    // add: 'जोडा',
    // save: 'जतन करा',
    // update: 'अद्यायावत करा',
    // clear: 'रिक्त',
    // exit: 'बाहेर पडा',
    // back: 'मागे',
    // saveAndNext: 'जतन करा आणि पुढे',
    // finish: 'समाप्त',

    //ReIssuance of Marriage Certificate

    onlyRIMC: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    mRegNo: "विवाह रजि क्र",
    marriageDate: "लग्नाची तारीख",
    marriageYear: "लग्नाचे वर्ष",
    brideName: "वधूचे नाव",
    groomName: "वराचे नाव",
    regDate: "नोंदणी दिनांक",

    //Renewal of Marriage Board Registration
    onlyRMBR: "विवाह मंडळ नोंदणीचे नूतनीकरण",
    mbrName: "विवाह मंडळ नोंदणी नाव",
    mbrDate: "विवाह मंडळ नोंदणी तारीख",
    mbrYear: "विवाह मंडळ नोंदणी वर्ष",
    search: "शोधा",

    //Application Details

    onlyApplDetail: "अर्ज तपशील",
    applFName: "अर्जदाराचे पहिले नाव",
    applMName: "अर्जदाराचे मधले नाव",
    applLName: "अर्जदार आडनाव",
    groomFName: "वराचे पहिले नाव",
    groomMName: "वराचे मधले नाव",
    groomLName: "वराचे आडनाव",
    brideFName: "वधूचे पहिले नाव",
    brideMName: "वधू मधले नाव",
    brideLName: "वधू आडनाव",
    mDate: "लग्नाची तारीख",

    //ReIssuance of marriage Certificate
    newRMItable: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    applFullName: "अर्जदाराचे पूर्ण नाव",
    applicationNo: "अर्ज क्र",
    applicationDate: "अर्ज तारीख",

    module: "कायदेशीर प्रकरण व्यवस्थापन प्रणाली",
    formType: "masters",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",

    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    courtPath: "कायदेशीर प्रकरण/ मास्टर /न्यायालय",
    advocatePath: "कायदेशीर प्रकरण/ मास्टर /वकील",
    serviceHierachyPath: "कायदेशीर प्रकरण/ मास्टर / सेवा पदानुक्रम",
    caseTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा प्रकार",
    caseSubTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा उप-प्रकार",
    caseStagesPath: "कायदेशीर प्रकरण/ मास्टर / प्रकरण-टप्पे",
    employeeAndUserCreationPath: "कायदेशीर प्रकरण/ मास्टर / कर्मचारी आणि वापरकर्ता निर्मिती",
    counterSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplatesPath:
      "कायदेशीर प्रकरण/ मास्टर / संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRightsPath: "कायदेशीर प्रकरण/ मास्टर / वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPasswordPath:
      "कायदेशीर प्रकरण/ मास्टर / बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / दिनदर्शिका शेड्युलिंग",

    //titles
    court: "न्यायालय",
    advocate: "वकील",
    serviceHierachy: "सेवा पदानुक्रम",
    caseType: "प्रकरणाचा प्रकार",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    caseStages: "प्रकरण-टप्पे",
    employeeAndUserCreation: "कर्मचारी आणि वापरकर्ता निर्मिती",
    counterScheduling: " काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplates: " संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRights: " वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPassword: "बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarScheduling: " दिनदर्शिका शेड्युलिंग",

    //other labels
    complaintType: "विषय/तक्रारीचा प्रकार *",
    complaintSubType: "तक्रारीचा उप प्रकार *",
    status: "स्थिती *",
    mediaName: "मीडियाचे नाव *",
    mediaPrefix: "मीडिया उपसर्ग *",
    remark: "टिप्पणी",
    eventType: "कार्यक्रमाचा प्रकार *",
    eventDate: "कार्यक्रमाची तारीख *",
    alertDateTime: "सूचना तारीख आणि वेळ *",
    description: "वर्णन",
    courtName: "न्यायालयाचे नाव",
    address: "पत्ता",
    roadName: "रस्त्याचे नाव",
    landmark: "महत्त्वाची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक *",
    fname: "पहिले नाव *",
    mname: "मधले  नाव *",
    lname: "शेवटचे नाव *",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    hutPrefix: "झोपडी उपसर्ग",
    zoneKey: "झोन",
    hutNo: "झोपडी क्र",
    download: "डाउनलोड करा",
    downloadPhotopass: "फोटोपास डाउनलोड करा",
    print: "छापणे",

    slumKey: "झोपडपट्टी",
    areaOfHut: "चौरस फूट मध्ये झोपडीचे क्षेत्र(अंदाजे)",
    ownershipKey: "मालकी",

    constructionTypeKey: "बांधकाम प्रकार",
    usageTypeKey: "वापराचा प्रकार",
    usageSubTypeKey: "वापर उपप्रकार",
    length: "लांबी",
    breadth: "रुंदी",
    height: "उंची",
    partNoInList: "यादीतील भाग क्र",
    rehabilitation: "पुनर्वसन",
    eligibility: "पात्रता",
    waterConnection: "पाणी जोडणी",
    noOfFloors: "एकूण क्र. पैकी मजले (जी +)",
    maleCount: "पुरुष संख्या ",
    femaleCount: "महिलांची संख्या",
    totalFamilyMembers: "एकूण कुटुंब सदस्य",
    areaKey: "क्षेत्र",
    villageKey: "गावाचे नाव",
    cityKey: "शहराचे नाव",
    pincode: "पिन कोड",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    assemblyConstituency: "विधानसभा मतदारसंघाचे नाव",
    correction: "दुरुस्ती",
    remarks: "शेरा",

    applicationNo: "अर्ज क्रमांक",
    applicationDate: "अर्जाची तारीख",
    hutNo: "झोपडी क्रमांक",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    lastName: "शेवटचे नाव",
    photo: "चित्र",
    mobileNo: "मोबाईल क्रमांक",
    aadharNo: "आधार क्रमांक",
    emailId: "इमेल पत्ता",
    slumName: "झोपडपट्टीचे नाव",
    area: "क्षेत्र",
    village: "गाव",
    city: "शहर",
    pincode: "पिनकोड",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    title: "शीर्षक",
    noOfCopies: "प्रतींची संख्या",
    asOnDate: "तारखेप्रमाणे",
    feesApplicable: "शुल्क लागू",
    details: "तपशील",
    outstandingTaxesAmount: "थकबाकी कराची रक्कम",
    addApplicant: "अर्जदार जोडा",
    fullName: "पूर्ण नाव",

    save: "जतन करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    search: "शोधा",

    srNo: "अनुक्रमांक",
    action: "क्रिया",

          //issuance of Photopass

          insuranceOfPhotopass: "फोटोपासचा विमा",
          searchSlumDetails: "झोपडपट्टी तपशील शोधा",

          //aknowledgement

          pimpariChinchwadMaha: "पिंपरी चिंचवड महानगरपालिका",
          appAcknowldgement: "पोच पावती",
          ackDear: "प्रिय",
          ackpcmcthanku: "पिंपरी चिंचवड नागरिक सेवा वापरल्याबद्दल धन्यवाद !!",
      
          ackshortDesc:
            "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत फोटोपास जारी करण्यासाठी तुमचा अर्ज यशस्वीरीत्या सादर झाला आहे.",
          ackHutTransferShortDesc:
            "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत झोपडी हस्तांतरणासाठी तुमचा अर्ज यशस्वीरीत्या सादर झाला आहे.",
          ackApplicationSummery: "अर्जाचा तपशील",
          applicationNo: "अर्जाचा क्रमांक",
          dateofApplication: "अर्ज दिनांक",
          ackplzContactNearestOperator:
            "कोणत्याही प्रश्नासाठी कृपया तुमच्या जवळच्या ऑपरेटरशी संपर्क साधा खालील संपर्क तपशील:",
          ackpcmcAddress: "मुंबई पुणे महामार्ग पिंपरी पुणे ४११-०१८",
          ackPcmcphNo: "फोन क्रमांक:९१-०२०-२७४२-५५११/१२/१३/१४",
          ackstateCountry: "महाराष्ट्र, भारत",
          applicantAddress: "अर्जदाराचा पत्ता :",
          
          no1: "१)",
          chargeNm: "शुल्काचे नाव",
    loiNo: "हेतू पत्र क्र",
    rtiApplicationAmt: "तुमच्याकडे आरटीआय या सेवेसाठी नागरिक सेवा पोर्टलवर कृपया तुमची रक्कम रुपये",
    determineandPayAmt: "निश्चित करा आणि केलेल्या सेवेची रक्कम/शुल्क भरा.",
    contactNearestpcmcDivisionalOffice: "किंवा जवळील पिंपरी चिंचवड महानगरपलिका विभागीय कार्यालयाला भेट द्या.",
    departmentKey: "विभाग",
  }
}