export default {
  en: {
    type: "commonLabels",

    module: "Sports Portal",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",
    masterPath: "Sports Portal / Master",
    transactionPath: "Sports Portal / Transaction ",
    reportPath: "Sports Portal / Reports ",

    type: "master",
    // master: "Masters",
    masterPath: "Sports Portal/ Master",
    master: "Masters",

    //breadcrum

    facilityNamePath: "Sports Portal/ Master/ Facility Name Master",
    venuePath: "Sports Portal/ Master / Venue Master",
    bookingTimePath: "Sports Portal/ Master / Booking Time Master",
    facilityTypePath: "Sports Portal/ Master / Facility Type Master",

    //label title
    facilityNameMaster: "Facility Sub-Type Master",
    venueMaster: "Facility Venue Master",
    bookingTimeMaster: "Booking Time Slot Master",
    facilityTypeMaster: "Facility Type Master",

    //Facility Name Master
    facilityNameId: "Facility Name ID",
    facilityTypeId: "Facility Type ID",
    zone: "Zone",
    ward: "Ward",
    venueId: "Venue ID",
    department: "Department",
    subDepartment: "Sub Department",
    member: "Member",
    facilityType: "Facility Type",
    facilityTypeMr: "Facility Type (In Marathi)",
    schoolCollegeAddress: "School / College Address",
    facilityName: "Facility Sub-Type Name",
    gisCode: "GIS Code",
    remark: "Remark",
    venue: "Facility Venue",
    date: "Date",
    name: "Name",
    fromBookingTime: "From Booking Time",
    toBookingTime: "To Booking Time",
    capacity: "Capacity/TotalMember",

    //other labels

    //Remarks

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "transaction",

    transaction: "Transaction",

    transactionPath: "Sports Portal / Transactions ",

    //titles
    sportBooking: "Sport Booking",
    check: "Check Availability Status ",
    swimmingPool: "Swimming Pool",

    //breadcrum

    //titles
    bookingDetails: "Booking Details",
    personalGroupDetails: "Personal Group Details",
    personalDetails: "Personal Details",
    aadharAuthenticationDetails: "Aadhar Authentication Details",
    eCSDetails: "ECS Details",
    paymentDetails: "Payment Details",
    documentsUpload: "Documents Upload",

    //other labels
    documentUpload: "Document Upload",
    bookingDetails: "Booking Details",
    eCSDetails: "ECS Details",
    aadharAuthentication: "Aadhar Authentication",

    fromDate: "Date(From)",
    formDateTime: "Form Date Time",
    toDateTime: "To Date Time",
    toDate: "Date(To)",
    selectSlot: "Select Slot",
    ward: "Ward",
    subDepartment: "Sub Department",
    bookingRegistrationId: "Booking Registration Id",
    applicationDate: "Application Date",
    bookingType: "Booking Type",
    durationType: "Duration Type",
    applicantType: "Applicant Type",
    duration: "Duration",
    chargeType: "Charge Type",
    applicantTypeEn: "Applicant Type(EN)",
    applicantTypeMr: "Applicant Type (MR)",
    durationTypeEn: "Duration Type(EN)",
    durationTypeMr: "Duration Type (MR)",
    chargeTypeEn: "Charge Type(EN)",
    chargeTypeMr: "Charge Type (MR)",
    zone: "Zone",
    addMember: "Add Member",
    department: "Department",
    facilityType: "Facility Type",
    workAddress: "Work Address",

    facilityName: "Facility Sub-Type Name",
    venue: "Venue",
    totalGroupMember: "Total Group Member",
    groupDetails: "Group Details",
    title: "Title",
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    gender: "Gender",
    name: "Name",
    dateOfBirth: "Date Of Birth",
    age: "Age",
    mobileNo: "Mobile No",
    aadharNo: "Aadhar No",
    emailAddress: "Email Address",
    currentAddress: "Current Address",
    permanentAddress: "Permanent Address",
    cityName: "City Name",
    state: "State",
    Maharashtra: "Maharashtra",
    pinCode: "Pin Code",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountHolderName: "Bank Account Holder Name",
    bankAccountNo: "Bank Account No",
    ifscCode: "IFSC Code",
    bankAddress: "Bank Address",
    aadharCard: "Aadhar Card",
    photo: "Photo",
    panCard: "Pan Card",
    otherDocumentPhoto: "Other Document Photo",
    checkBox: "Permanent Address as the Correspondence Address",
    purposeOfBooking: "Purpose Of Booking",
    bookingPersonDetails: "Booking Person Details",
    slots: "Slots",
    timePeriod: "Time Period",
    sendOtp: "SEND OTP",
    attachFile: "Attach File",
    viewImage: "VIEW IMAGE",
    srNo: "Sr. No",
    actions: "Actions",
    Lattitude: "Lattitude",
    Longitute: "Longitude",
    Addfile: "Add File",
    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "report",

    reports: "Reports",

    reportsPath: "Sports Portal / Reports ",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    // state: "Please enter State (In English)",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    // stateMr: "Please enter State (In Marathi)",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    VtimePeriod: "Please select Time Period",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (in English)",
    placeMarriageMr: "Please enter Place of Marriage (in Marathi)",
    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",
    witnessAddressC: "Please enter an Address ",
    witnessRelation: "Please enter an Relation. ",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    paymentMode: "Payment Mode",
    paymentDetails: "Payment Details",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    //Modification in Marriage Certificate

    onlyMIMC: "Modification of Marriage Certificate",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab :",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark on application",
    APPROVE: "APPROVE",

    REASSIGN: "Revert Back",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    Vvenue: "Select Venue",
    VbookingType: "Select Booking Type",
    VapplicantType: "Select Applicant Type",
    VdurationType: "Select Duration Type",
    VfacilityType: "Select Facility Type",
    VfacilityName: "Select Facility Sub-Type Name",
    Vvenue: "Select Venue Name",
    VfromDate: "Select From Date",
    VtoDate: "Select To Date",
    VbookingType: "Select Booking Type",
    VpurposeOfBooking: "Select Purpose Of Booking",
    Vcaddres: "Please enter an current address",
    VfromBookingTime: "Select From Booking Time",
    VselectSlots: "Please Select Slot",
    VwAddress: "Please Enter Work Address",

    VtoBookingTime: "Select To Booking Time",
    VaadharCard: "Please Upload Aadhar Card",
    VpanCard: "Please Upload Pan Card",
    Vphoto: "Please Upload passport Size Photo ",
    VbankName: "Select Bank Name",
    VbranchName: "Please enter an Branch Name",
    VbankAccountHolderName: "Please enter an Bank Account Holder Name",
    VbankAccountNo: "Please enter an Bank Account No",
    VifscCode: "Please enter an IFSC Code",
    VbankAddress: "Please enter an Bank Address",
    generateLoi: "Generate LOI",
    pay: "Pay",
    receiptModeDetails: "Receipt Mode Details",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    receipt: "Receipts",
    usertask: "User task",
    serviceName: "Service Name ",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    demo: "",
    //mr
    MrMasters: "Marriage Registration / Masters",
    marriageRegistrationMaritalStatus: "Marriage Registration / Masters / Marital Status",

    pay: "PAY",
    marriageRegistrationrelation: "Marriage Registration / Masters / relation",
    receiptModeDetails: "Receipt Mode Details",
    maritialSatus: "Marital Status",
    relation: "Relation",

    AptBook: "Appointment Slot Booking",
    serviceChargeTypeName: "Service Charge Type Name",

    // field label
    srNo: "Sr. No",
    actions: "Actions",
    statusDetails: "Status Details",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",

    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",

    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    //marathi details
    gFNameMr: "",
    gMNameMr: "",
    gLNameMr: "",
    ApplicatCheck1: "If the Applicant is Groom",
    ApplicatCheck2: "If the Applicant is Bride",
    OwnerChkeck: "If the Applicant is Owner",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //mr
    Tnc: "accept term & Condition",
    // instrustion
    onlyMHR:
      " Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.",
    docNote:
      "Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.",
    //table
    newMRtable: "NEW MARRIAGE REGISTRATION ",
    boardtitle: "  Marriage Board Registration ",
    zone: "Zone",
    ward: "Ward",
    Addrees: "Applicant Address :",
    CrrtAdree: "Current Address :",
    parmtAdree: "Permanent Address :",
    personalDetails: "Personal Information :",
    Adress: "Address  :",
    BriNBM: "  (  Name before marriage)",
    AppliToGroom: "If the Applicant is Groom ",
    AppliToBride: "If the Applicant is Bride",
    marrigeDetails: "  Marriage Details :",
    marrigeDate: "Marriage Date",
    //aprove
    GPhoto: "Groom Photo  ",
    Bphoto: "Bride Photo  ",
    witnessphto1: "Witness 1 Photo  ",
    witnessphto2: "Witness 2 Photo  ",
    witnessphto3: "Witness 3 Photo  ",
    Gthumb: "Groom Thumb  ",
    Bthumb: "Bride Thumb  ",
    witnessthumb1: "Witness 1 Thumb  ",
    witnessthumb2: "Witness 2 Thumb  ",
    witnessthumb3: "Witness 3 Thumb  ",

    //title
    ApplicatDetails: "APPLICANT DETAILS",
    ApplicatName: "Applicant Name",
    groomDetail: "GROOM DETAILS",
    groomParaentDetail: "Groom Parents Details ",
    brideDetails: "BRIDE DETAILS",
    brideParaentDetail: "Bride Parents Details",
    priestDetails: "PRIEST DETAILS",
    witness: "Witness",
    witnessAdd: "Witness",
    witnessDetails: "WITNESS DETAILS",
    documentsUpload: "DOCUMENT UPLOAD",
    boardDetail: "Board Details :",
    otherDetail: "OTHER DETAILS",
    titleInmarathi: "Title (In Marathi)",
    titleInenglish: "Title (In english)",

    // viceversa
    titleV: "शीर्षक",
    firstNameV: "प्रथम नावं  ",
    middleNameV: "मधले नावं  ",
    lastNameV: "आडनाव  ",

    //Groom
    // title: 'Title  ',
    // firstName: 'First Name  ',
    // middleName: 'Middle Name  ',
    // lastName: 'Last Name  ',
    title: "Title ",
    title1: "Title ",
    firstName: "First Name (In English) ",
    middleName: "Middle Name (In English) ",
    lastName: "Last Name (In English) ",
    titlemr: "शीर्षक ",
    firstNamemr: "First Name (In Marathi) ",
    middleNamemr: "Middle Name (In Marathi) ",
    lastNamemr: "Last Name (In Marathi) ",

    BirthDate: "Birth Date   ",
    Gender: "Gender",
    AadharNo: "Aadhar No",
    Age: "Age (at the time of marriage)",
    mobileNo: "Mobile / Phone Number",
    phoneNo: "Phone Number",
    email: "Email",

    flatBuildingNo: "Flat/Building No (In English)  ",
    buildingName: "Apartment Name (In English) ",
    roadName: "Road Name (In English) ",
    Landmark: "Landmark (In English) ",
    villageName: "Village Name (In English) ",
    cityName: "City Name / Village Name (In English) ",

    flatBuildingNomr: "Flat/Building No (In Marathi) ",
    buildingNamemr: "Apartment Name (In Marathi) ",
    roadNamemr: "Road Name (In Marathi) ",
    Landmarkmr: "Landmark (In Marathi) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "City Name / Village Name (In Marathi) ",

    // State: "State (In English) ",
    // statemr: "State (In Marathi) ",
    pincode: "Pin Code",
    Religion1: "Religion by Birth",
    Religion2: " Religion by Adoption",
    StatusOfMarrige: " Status at time of marriage",
    AgeDocument: "Birth Proof Document",
    IdDocument: "Id Document",
    residentialDocument: "Residential Document",
    StatusOfDocument: "Status Of Document",

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: "Place of Marriage (in English)",
    placeofMarriage1: "Place of Marriage (in Marathi)",

    //witness
    address: "Address",
    wRelation: "Witness Relation",
    wDocument: "Witness Document",

    //Document

    DBProof: "Date of Birth Proof",
    ResProof: "Residence Proof",
    IdProof: "ID Proof",

    ResProofW1: "Residence Proof of first witness",
    ResProofW2: "Residence Proof of second witness",
    ResProofW3: "Residence Proof of third witness",

    marrigeRelatedDoc: "Marriage Related Document",

    invetaionCard: "Marriage Invitation card / affidavit ",
    marrigePhotoC: "Marriage Photograph (Couple) ",
    marDrf: "Draft an application on the 100 Rs Stamp paper",

    DivorcePaper: "Valid Divorce Paper (if applicable)",
    DeathC: "Death Certificate (if applicable)",
    certiByReligiousPlc: " Certificate issued by religious place i.e Temple, Mosque etc",
    docFormat: " (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)",
    enterDoc: "Document Name",
    TandC: "",
    //board
    applicantName: "Applicant Name :",
    boardNameT: "Marriage Board Name",
    boardName: "Marriage Board Name (In English)  ",
    boardNamemr: "Marriage Board Name (In Marathi)  ",
    remark: "Remarks",
    documentList: " Documents List",
    ValidtyofMBR: "  Validity Of MBR",
    documentsUploadF: "Documents Upload",

    //button
    back: "Back",
    next: "Next",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",
    submit: "Submit",
    apply: "Apply",
    addFile: "Upload File",

    //table filed
    srNo: "Sr. No",
    ApplicantName: "Applicant Name",
    hName: "Groom Name",
    wName: "Bride Name",
    actions: "Actions",

    //brudcrum
    newMarriageRegistration: "Marriage Registration / New Marriage Registration",
    BoardMarriageRegistration: "Marriage Registration / New Board Registration",

    //ReIssuance of Marriage Certificate

    onlyRIMC: "Re-Issuance of Marriage Certificate",
    mRegNo: "Marriage Reg No",
    marriageDate: "Marriage Date",
    marriageYear: "Marriage Year",
    brideName: "Bride Name",
    groomName: "Groom Name",
    regDate: "Registration Date",

    //Renewal of Marriage Board Registration
    onlyRMBR: "Renewal of Marriage Board Registration",
    mbrName: "Marriage Board Name",
    mbrDate: "Marriage Board Reg Date",
    mbrYear: "Marriage Board Reg Year",
    search: "Search",

    //Application Details

    onlyApplDetail: "Application Details",
    applFName: "Applicant First Name",
    applMName: "Applicant Middle Name",
    applLName: "Applicant Last Name",
    groomFName: "Groom First Name",
    groomMName: "Groom Middle Name",
    groomLName: "Groom Last Name",
    brideFName: "Bride First Name",
    brideMName: "Bride Middle Name",
    brideLName: "Bride Last Name",
    mDate: "Marriage Date",

    //ReIssuance of marriage Certificate
    newRMItable: "ReIssuance of Marriage Certificate",
    applFullName: "Applicant Full Name",
    applicationNo: "Application No",
    generateLoi: "Generate LOI",

    //Modification in Marriage Board Registration

    onlyMMBR: "Modification in Marriage Board Registration",
    applicationDate: "Application Date",
    registerationDate: "Registeration Date",
    registerationNo: "Marriage Board Reg Number",
    orgName: "Organisation Name",

    //Payment Collection
    bankName: "Bank Name",
    branchName: "Branch Name",
    ifsc: "IFSC Code",
    accountNumber: "Account Number ",
    pay: "Pay",
    exit: "Exit",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    // state: "Please enter State (In English)",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    // stateMr: "Please enter State (In Marathi)",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (in English)",
    placeMarriageMr: "Please enter Place of Marriage (in Marathi)",

    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",

    witnessAddressC: "Please enter an Address ",
    witnessRelation: "Please enter an Relation. ",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    //Modification in Marriage Certificate

    onlyMIMC: "Modification of Marriage Certificate",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab :",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark on application",
    APPROVE: "APPROVE",

    REASSIGN: "Revert Back",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    //validation file upload
    birthProfV: "Please Upload a Date of Birth Proof",
    ResideProofV: "Please Upload a Residence Proof",
    IdentyProofV: "Please Upload a ID Proof",

    invetaionCardV: "Please Upload a Marriage Invitation card / affidavit ",
    marrigePhotoCV: "Please Upload a Marriage Photograph (Couple) ",
    marDrfV: "Please Upload a Draft an application on the 100 Rs Stamp paper",
    boardheadphotoV: "Please Upload a Board Head Person Photo",
    boardorgphotocpyV: "Please Upload a Board / Organization PhotoCopy",
    panCardV: "Please Upload a Pan Card",
    adharcardV: "Please Upload a Aadhaar card",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    receipt: "Receipts",
    usertask: "User task",
    serviceName: "Service Name ",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    demo: "",
    //mr
    MrMasters: "Marriage Registration / Masters",
    marriageRegistrationMaritalStatus: "Marriage Registration / Masters / Marital Status",

    pay: "PAY",
    marriageRegistrationrelation: "Marriage Registration / Masters / relation",
    receiptModeDetails: "Receipt Mode Details",
    maritialSatus: "Marital Status",
    relation: "Relation",

    AptBook: "Appointment Slot Booking",
    serviceChargeTypeName: "Service Charge Type Name",

    // field label
    srNo: "Sr. No",
    actions: "Actions",
    statusDetails: "Status Details",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",

    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",

    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    //marathi details
    gFNameMr: "",
    gMNameMr: "",
    gLNameMr: "",
    ApplicatCheck1: "If the Applicant is Groom",
    ApplicatCheck2: "If the Applicant is Bride",
    OwnerChkeck: "If the Applicant is Owner",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //mr
    Tnc: "accept term & Condition",
    // instrustion
    onlyMHR:
      " Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.",
    docNote:
      "Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.",
    //table
    newMRtable: "NEW MARRIAGE REGISTRATION ",
    boardtitle: "  Marriage Board Registration ",
    zone: "Zone",
    ward: "Ward",
    Addrees: "Applicant Address :",
    CrrtAdree: "Current Address :",
    parmtAdree: "Permanent Address :",
    personalDetails: "Personal Information :",
    Adress: "Address  :",
    BriNBM: "  (  Name before marriage)",
    AppliToGroom: "If the Applicant is Groom ",
    AppliToBride: "If the Applicant is Bride",
    marrigeDetails: "  Marriage Details :",
    marrigeDate: "Marriage Date",
    //aprove
    GPhoto: "Groom Photo  ",
    Bphoto: "Bride Photo  ",
    witnessphto1: "Witness 1 Photo  ",
    witnessphto2: "Witness 2 Photo  ",
    witnessphto3: "Witness 3 Photo  ",
    Gthumb: "Groom Thumb  ",
    Bthumb: "Bride Thumb  ",
    witnessthumb1: "Witness 1 Thumb  ",
    witnessthumb2: "Witness 2 Thumb  ",
    witnessthumb3: "Witness 3 Thumb  ",

    //title
    ApplicatDetails: "APPLICANT DETAILS",
    ApplicatName: "Applicant Name",
    groomDetail: "GROOM DETAILS",
    groomParaentDetail: "Groom Parents Details ",
    brideDetails: "BRIDE DETAILS",
    brideParaentDetail: "Bride Parents Details",
    priestDetails: "PRIEST DETAILS",
    witness: "Witness",
    witnessAdd: "Witness",
    witnessDetails: "WITNESS DETAILS",
    documentsUpload: "DOCUMENT UPLOAD",
    boardDetail: "Board Details :",
    otherDetail: "OTHER DETAILS",
    titleInmarathi: "Title (In Marathi)",
    titleInenglish: "Title (In english)",

    // viceversa
    titleV: "शीर्षक",
    firstNameV: "प्रथम नावं  ",
    middleNameV: "मधले नावं  ",
    lastNameV: "आडनाव  ",

    //Groom
    // title: 'Title  ',
    // firstName: 'First Name  ',
    // middleName: 'Middle Name  ',
    // lastName: 'Last Name  ',
    title: "Title ",
    title1: "Title ",
    firstName: "First Name (In English) ",
    middleName: "Middle Name (In English) ",
    lastName: "Last Name (In English) ",
    titlemr: "शीर्षक ",
    firstNamemr: "First Name (In Marathi) ",
    middleNamemr: "Middle Name (In Marathi) ",
    lastNamemr: "Last Name (In Marathi) ",

    BirthDate: "Birth Date   ",
    Gender: "Gender",
    AadharNo: "Aadhar No",
    Age: "Age (at the time of marriage)",
    mobileNo: "Mobile / Phone Number",
    phoneNo: "Phone Number",
    email: "Email",

    flatBuildingNo: "Flat/Building No (In English)  ",
    buildingName: "Apartment Name (In English) ",
    roadName: "Road Name (In English) ",
    Landmark: "Landmark (In English) ",
    villageName: "Village Name (In English) ",
    cityName: "City Name / Village Name (In English) ",

    flatBuildingNomr: "Flat/Building No (In Marathi) ",
    buildingNamemr: "Apartment Name (In Marathi) ",
    roadNamemr: "Road Name (In Marathi) ",
    Landmarkmr: "Landmark (In Marathi) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "City Name / Village Name (In Marathi) ",

    // State: "State (In English) ",
    // statemr: "State (In Marathi) ",
    pincode: "Pin Code",
    Religion1: "Religion by Birth",
    Religion2: " Religion by Adoption",
    StatusOfMarrige: " Status at time of marriage",
    AgeDocument: "Birth Proof Document",
    IdDocument: "Id Document",
    residentialDocument: "Residential Document",
    StatusOfDocument: "Status Of Document",

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: "Place of Marriage (in English)",
    placeofMarriage1: "Place of Marriage (in Marathi)",

    //witness
    address: "Address",
    wRelation: "Witness Relation",
    wDocument: "Witness Document",

    //Document

    DBProof: "Date of Birth Proof",
    ResProof: "Residence Proof",
    IdProof: "ID Proof",

    ResProofW1: "Residence Proof of first witness",
    ResProofW2: "Residence Proof of second witness",
    ResProofW3: "Residence Proof of third witness",

    marrigeRelatedDoc: "Marriage Related Document",

    invetaionCard: "Marriage Invitation card / affidavit ",
    marrigePhotoC: "Marriage Photograph (Couple) ",
    marDrf: "Draft an application on the 100 Rs Stamp paper",

    DivorcePaper: "Valid Divorce Paper (if applicable)",
    DeathC: "Death Certificate (if applicable)",
    certiByReligiousPlc: " Certificate issued by religious place i.e Temple, Mosque etc",
    docFormat: " (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)",
    enterDoc: "Document Name",
    TandC: "",
    //board
    applicantName: "Applicant Name :",
    boardNameT: "Marriage Board Name",
    boardName: "Marriage Board Name (In English)  ",
    boardNamemr: "Marriage Board Name (In Marathi)  ",
    remark: "Remarks",
    documentList: " Documents List",
    ValidtyofMBR: "  Validity Of MBR",
    documentsUploadF: "Documents Upload",

    //button
    back: "Back",
    next: "Next",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",
    submit: "Submit",
    apply: "Apply",
    addFile: "Upload File",

    //table filed
    srNo: "Sr. No",
    ApplicantName: "Applicant Name",
    hName: "Groom Name",
    wName: "Bride Name",
    actions: "Actions",

    //brudcrum
    newMarriageRegistration: "Marriage Registration / New Marriage Registration",
    BoardMarriageRegistration: "Marriage Registration / New Board Registration",

    //ReIssuance of Marriage Certificate

    onlyRIMC: "Re-Issuance of Marriage Certificate",
    mRegNo: "Marriage Reg No",
    marriageDate: "Marriage Date",
    marriageYear: "Marriage Year",
    brideName: "Bride Name",
    groomName: "Groom Name",
    regDate: "Registration Date",

    //Renewal of Marriage Board Registration
    onlyRMBR: "Renewal of Marriage Board Registration",
    mbrName: "Marriage Board Name",
    mbrDate: "Marriage Board Reg Date",
    mbrYear: "Marriage Board Reg Year",
    search: "Search",

    //Application Details

    onlyApplDetail: "Application Details",
    applFName: "Applicant First Name",
    applMName: "Applicant Middle Name",
    applLName: "Applicant Last Name",
    groomFName: "Groom First Name",
    groomMName: "Groom Middle Name",
    groomLName: "Groom Last Name",
    brideFName: "Bride First Name",
    brideMName: "Bride Middle Name",
    brideLName: "Bride Last Name",
    mDate: "Marriage Date",

    //ReIssuance of marriage Certificate
    newRMItable: "ReIssuance of Marriage Certificate",
    applFullName: "Applicant Full Name",
    applicationNo: "Application No",
    generateLoi: "Generate LOI",

    //Modification in Marriage Board Registration

    onlyMMBR: "Modification in Marriage Board Registration",
    applicationDate: "Application Date",
    registerationDate: "Registeration Date",
    registerationNo: "Marriage Board Reg Number",
    orgName: "Organisation Name",

    //Payment Collection
    bankName: "Bank Name",
    branchName: "Branch Name",
    ifsc: "IFSC Code",
    accountNumber: "Account Number ",
    pay: "Pay",
    exit: "Exit",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    // state: "Please enter State (In English)",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    // stateMr: "Please enter State (In Marathi)",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (in English)",
    placeMarriageMr: "Please enter Place of Marriage (in Marathi)",

    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",

    witnessAddressC: "Please enter an Address ",
    witnessRelation: "Please enter an Relation. ",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    //Modification in Marriage Certificate

    onlyMIMC: "Modification of Marriage Certificate",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab :",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark on application",
    APPROVE: "APPROVE",

    REASSIGN: "Revert Back",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    //validation file upload
    birthProfV: "Please Upload a Date of Birth Proof",
    ResideProofV: "Please Upload a Residence Proof",
    IdentyProofV: "Please Upload a ID Proof",

    invetaionCardV: "Please Upload a Marriage Invitation card / affidavit ",
    marrigePhotoCV: "Please Upload a Marriage Photograph (Couple) ",
    marDrfV: "Please Upload a Draft an application on the 100 Rs Stamp paper",
    boardheadphotoV: "Please Upload a Board Head Person Photo",
    boardorgphotocpyV: "Please Upload a Board / Organization PhotoCopy",
    panCardV: "Please Upload a Pan Card",
    adharcardV: "Please Upload a Aadhaar card",
  },
  mr: {
    paymentDetails: "Payment Details",
    receiptModeDetails: "पैसे भरावयाची पद्धत",
    type: "commonLabels",
    pay: "पैसे भरा",
    module: "क्रीडा विभाग",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "क्रीडा विभाग/ मास्टर्स ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    type: "master",

    master: "मास्टर्स",
    // transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "क्रीडा विभाग/ मास्टर ",
    // transactionPath: "क्रीडा विभाग/ व्यवहार ",

    //breadcrum
    viewImage: "प्रतिमा पहा",
    facilityNamePath: "क्रीडा विभाग/ मास्टर्स / सुविधा उप-प्रकार मास्टर",
    venuePath: "क्रीडा विभाग/ मास्टर्स / ठिकाण मास्टर ",
    bookingTimePath: "क्रीडा विभाग/ मास्टर्स / बुकिंग वेळ मास्टर्स",
    facilityTypePath: "क्रीडा विभाग/ मास्टर्स / सुविधा प्रकार मास्टर",

    //titles
    facilityNameMaster: "सुविधा उप-प्रकार मास्टर",
    facilityTypeMaster: "सुविधा प्रकार मास्टर",
    venueMaster: "सुविधा ठिकाण मास्टर",
    bookingTimeMaster: "बुकिंग वेळ स्लॉट मास्टर",

    //labels
    facilityNameId: "सुविधा उपप्रकार आयडी",
    facilityTypeId: "सुविधा प्रकार आयडी",
    venueId: "ठिकाण आयडी",
    addMember: "सदस्य जोडा",
    // delete: "सदस्य जोडा",
    zone: "झोन",
    ward: "प्रभाग",
    subDepartment: "उप विभाग",
    department: "विभाग",
    member: "सदस्य",
    facilityType: "सुविधा प्रकार",
    facilityTypeMr: "सुविधा प्रकार (मराठी)",
    schoolCollegeAddress: "शाळा/कॉलेजचा पत्ता",
    workAddress: "कामाचा पत्ता",
    facilityName: "सुविधा उपप्रकार नाव",
    gisCode: "GIS कोड",
    remark: "शेरा",
    venue: "सुविधा ठिकाण",
    date: "तारीख",
    fromBookingTime: "(पासून) बुकिंगची वेळ",
    toBookingTime: "(ते) बुकिंगची वेळ",
    capacity: "क्षमता/एकूण सदस्य",
    Lattitude: "अक्षांश",
    Longitute: "रेखांश",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक ",
    fname: "पहिले नाव ",
    mname: "मधले  नाव ",
    lname: "शेवटचे नाव ",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",

    VbankName: "बँकेचे नाव निवडा",
    Vvenue: "ठिकाणाचे नाव निवडा",
    VbranchName: "शाखेचे नाव भरा",
    VbankAccountHolderName: "बँक खातेधारकाचे नाव भरा",
    VbankAccountNo: "खाता क्रमांक भरा",
    VifscCode: "बँक IFSC कोड भरा",
    VbankAddress: "बँकेचा पत्ता भरा",

    Vvenue: "सुविधा ठिकाण निवडा",

    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    photo: "पासपोर्टच्या आकाराचा फोटो",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",
    subType: "उप-प्रकार",
    slots: "स्लॉट",
    timePeriod: "कालावधी",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    sendOtp: "ओटीपी पाठवा",
    Addfile: "फाइल जोडा",
    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    type: "transaction",

    transaction: "व्यवहार",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    //breadcrum

    //titles
    sportBooking: "क्रीडा बुकिंग",
    check: "उपलब्धता स्थिती तपासा",
    swimmingPool: "जलतरण तलाव",

    //titles
    bookingDetails: "नोंदणी तपशील",
    personalGroupDetails: "वैयक्तिक गट तपशील",
    personalDetails: "वैयक्तिक माहिती",
    aadharAuthentication: "आधार प्रमाणीकरण",
    paymentDetails: "देयक तपशील",
    aadharAuthenticationDetails: "आधार प्रमाणीकरण तपशील",
    eCSDetails: "ECS तपशील",
    documentsUpload: "दस्तऐवज अपलोड करा",

    //other labels
    fromDate: "तारीख (पासून)",
    toDate: "तारीख (ते)",
    selectSlot: "स्लॉट निवडा",
    formDateTime: "(पासून) तारीख आणि वेळ",
    toDateTime: "(ते) तारीख आणि वेळ",
    bookingRegistrationId: "बुकिंग नोंदणी आयडी",
    documentUpload: "दस्तऐवज अपलोड",
    applicationDate: "अर्जाची तारीख",
    bookingType: "बुकिंग प्रकार",
    durationType: "कालावधीचा प्रकार",
    applicantType: "अर्जदाराचा प्रकार",
    duration: "कालावधी",
    chargeType: "शुल्काचा प्रकार",
    applicantTypeMr: "अर्जदाराचा प्रकार (मराठीमध्ये)",
    applicantTypeEn: "अर्जदाराचा प्रकार (इंग्लिशमध्ये)",
    durationTypeMr: "कालावधीचा प्रकार (मराठीमध्ये)",
    durationTypeEn: "कालावधीचा प्रकार (इंग्लिशमध्ये)",
    chargeTypeMr: "शुल्काचा प्रकार (मराठीमध्ये)",
    chargeTypeEn: "शुल्काचा प्रकार (इंग्लिशमध्ये)",
    VbookingType: "बुकिंग प्रकार निवडा",
    zone: "झोन",
    ward: "प्रभाग",
    subDepartment: "उप विभाग",
    department: "विभाग ",
    member: "सदस्य",
    facilityType: "सुविधा प्रकार",
    facilityName: "सुविधेचे उपप्रकार",
    venue: "सुविधा ठिकाण",
    totalGroupMember: "एकूण गट सदस्य",
    groupDetails: "गट तपशील",
    title: "शीर्षक",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    lastName: "आडनाव",
    gender: "लिंग",
    dateOfBirth: "जन्मतारीख",
    age: "वय",
    mobileNo: "मोबाईल क्र",
    aadharNo: "आधार क्र",
    emailAddress: "ईमेल आयडी",
    currentAddress: "सध्याचा पत्ता",
    permanentAddress: "कायमचा पत्ता",
    cityName: "शहराचे नाव",
    state: "राज्य",
    Maharashtra: "महाराष्ट्र",
    pinCode: "पिन कोड",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountHolderName: "बँक खातेधारकाचे नाव",
    bankAccountNo: "बँक खाते क्र",
    ifscCode: "IFSC कोड",
    bankAddress: "बँकेचा पत्ता",
    aadharCard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    otherDocumentPhoto: "इतर दस्तऐवज फोटो",
    checkBox: "सध्याचा रहिवाशी पत्ता कायमचा पत्ता",
    purposeOfBooking: "बुकिंगचा उद्देश",
    bookingPersonDetails: "बुकिंग व्यक्ती तपशील",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    onlyeng: "फक्त इंग्लिश मध्ये",
    onlymarathi: "फक्त मराठी मध्ये",
    APPROVE: "मंजूर करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    newLabel: "नवीन माहिती",
    onlyMIMC: "विवाह प्रमाणपत्रात बदल",
    // State: "स्टेट (इंग्लिश मध्ये) ",
    // statemr: "स्टेट (मराठी मध्ये) ",
    UploadFile: "फाइल अपलोड करा",
    electrbill: "वीज बिल",
    OtherDocument: "इतर दस्तऐवज",
    rationcard: "रेशान कार्ड",
    adharcard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    boardorgphotocpy: "संस्था किंवा मंडळची दस्तऐवज",
    boardheadphoto: "मंडळाच्या प्रमुख व्यक्तीच छायाचित्र",
    document: "दस्तऐवज",
    Owneraddress: " मंडळच्या प्रमुख व्यक्तीचा पत्ता  :",
    OwnerDetails: "मंडळच्या प्रमुख व्यक्तीची माहिती",
    titleInmarathi: "शीर्षक मराठी मध्ये",
    titleInenglish: "शीर्षक इंग्लिश मध्ये",
    OwnerChkeck: "जर अर्जादारच विवाह मंडळाचा प्रमुख असेल",
    apply: "जतन करा",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    EnterDocName: "कृपया दस्तऐवजाच नाव भरा ",
    witnessAddressC: "कृपया पत्ता भरा  ",
    witnessRelation: "कृपया साक्षीदारशी नाते भरा  ",

    birthProf: "कृपया जन्म तारीख पुरावा निवडा ",
    ResideProof: "कृपया रहिवासाचा पुरावा निवडा ",
    IdentyProof: "कृपया ओळखपत्र पुरावा निवडा ",
    // //Remarks
    selectReligionby: "कृपया जन्माने धर्म निवडा ",
    selectAdoptionby: "कृपया दत्तक घेऊन धर्म निवडा ",
    selectStatusAt: "कृपया लग्नाच्या वेळची स्थिती निवडा ",

    enterAge: "कृपया वय भरा ",
    selectGender: "कृपया लिंग निवडा ",
    selectZone: "कृपया झोन निवडा",
    selectWard: "कृपया वार्ड निवडा",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश मध्ये)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश मध्ये)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)",

    enterFNameMr: "कृपया पहिले नाव भरा (मराठी मध्ये) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी मध्ये)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी मध्ये)",

    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)",
    enterRoadName: "कृपया रस्त्याचे नाव भरा (इंग्लिश मध्ये)",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा (इंग्लिश मध्ये)",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश मध्ये)",
    // state: "कृपया  राज्य नाव भरा (इंग्लिश मध्ये)",

    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)",
    enterLandmarkMr: "कृपया  महत्त्वाची खूण भरा  (मराठी मध्ये)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)",
    // stateMr: "कृपया  राज्य नाव भरा  (मराठी मध्ये)",

    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",

    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    //mr
    selectWard: "कृपया प्रभाग निवडा ",
    selectZone: "कृपया झोन निवडा ",
    selectTitle: "कृपया शीर्षक निवडा ",
    placeMarriage: "कृपया  विवाहाचा ठिकाण भरा (इंग्लिश मध्ये)",
    placeMarriageMr: "कृपया  विवाहाचा ठिकाण भरा  (मराठी मध्ये)",
    VfacilityType: "कृपया सुविधाचा प्रकार निवडा",
    VdurationType: "कृपया कालावधीचा प्रकार निवडा",
    VapplicantType: "अर्जदाराचा प्रकार निवडा",
    VfromDate: " कृपया तारीख निवडा",
    VtoDate: " कृपया तारीख निवडा",
    VfacilityName: "सुविधेचे उपप्रकार निवडा",
    VpurposeOfBooking: "बुकिंगचा उद्देश निवडा",
    Vcaddres: "कृपया  सध्याचा पत्ता भरा   ",
    VfromBookingTime: "कृपया वेळ निवडा ",
    VselectSlots: "कृपया स्लॉट निवडा ",
    VtoBookingTime: "कृपया वेळ निवडा ",
    VaadharCard: "कृपया आधार कार्ड निवडा ",
    adharcardV: "कृपया आधार कार्ड अपलोड करा",
    panCardV: "कृपया पॅन कार्ड अपलोड करा",
    boardorgphotocpyV: "कृपया संस्था किंवा मंडळची दस्तऐवज अपलोड करा",
    boardheadphotoV: "कृपया मंडळाच्या प्रमुख व्यक्तीच छायाचित्र अपलोड करा",
    //validation file upload
    birthProfV: "कृपया जन्म तारीख पुरावा अपलोड करा ",
    ResideProofV: "कृपया रहिवासाचा पुरावा अपलोड करा ",
    IdentyProofV: "कृपया ओळखपत्र पुरावा अपलोड करा ",

    invetaionCardV: "कृपया विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र अपलोड करा",
    marrigePhotoCV: "कृपया विवाह छायाचित्र (जोडीचे) अपलोड करा",
    marDrfV: "कृपया १०० रुपयांच्या स्टॅम्प पेपरवर असलेला अर्जाचा मसुदा अपलोड करा",

    registerationNo: "मंडळाचा नोंदणी क्रमांक",
    onlyeng: "फक्त इंग्लिश मध्ये",
    onlymarathi: "फक्त मराठी मध्ये",
    APPROVE: "मंजूर करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    newLabel: "नवीन माहिती",
    onlyMIMC: "विवाह प्रमाणपत्रात बदल",
    // State: "स्टेट (इंग्लिश मध्ये) ",
    // statemr: "स्टेट (मराठी मध्ये) ",
    UploadFile: "फाइल अपलोड करा",
    electrbill: "वीज बिल",
    OtherDocument: "इतर दस्तऐवज",
    rationcard: "रेशान कार्ड",
    adharcard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    boardorgphotocpy: "संस्था किंवा मंडळची दस्तऐवज",
    boardheadphoto: "मंडळाच्या प्रमुख व्यक्तीच छायाचित्र",
    document: "दस्तऐवज",
    Owneraddress: " मंडळच्या प्रमुख व्यक्तीचा पत्ता  :",
    OwnerDetails: "मंडळच्या प्रमुख व्यक्तीची माहिती",
    titleInmarathi: "शीर्षक (मराठी मध्ये)",
    titleInenglish: "शीर्षक (इंग्लिश मध्ये)",
    OwnerChkeck: "जर अर्जादारच विवाह मंडळाचा प्रमुख असेल",
    apply: "जतन करा",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    EnterDocName: "कृपया दस्तऐवजाच नाव भरा ",
    witnessAddressC: "कृपया पत्ता भरा  ",
    witnessRelation: "कृपया साक्षीदारशी नाते भरा  ",

    birthProf: "कृपया जन्म तारीख पुरावा निवडा ",
    ResideProof: "कृपया रहिवासाचा पुरावा निवडा ",
    IdentyProof: "कृपया ओळखपत्र पुरावा निवडा ",
    // //Remarks
    selectReligionby: "कृपया जन्माने धर्म निवडा ",
    selectAdoptionby: "कृपया दत्तक घेऊन धर्म निवडा ",
    selectStatusAt: "कृपया लग्नाच्या वेळची स्थिती निवडा ",

    enterAge: "कृपया वय भरा ",
    selectGender: "कृपया लिंग निवडा ",
    selectZone: "कृपया झोन निवडा",
    selectWard: "कृपया वार्ड निवडा",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश मध्ये)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश मध्ये)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)",

    enterFNameMr: "कृपया पहिले नाव भरा (मराठी मध्ये) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी मध्ये)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी मध्ये)",

    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)",
    enterRoadName: "कृपया रस्त्याचे नाव भरा (इंग्लिश मध्ये)",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा (इंग्लिश मध्ये)",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश मध्ये)",
    // state: "कृपया  राज्य नाव भरा (इंग्लिश मध्ये)",

    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)",
    enterLandmarkMr: "कृपया  महत्त्वाची खूण भरा  (मराठी मध्ये)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)",
    // stateMr: "कृपया  राज्य नाव भरा  (मराठी मध्ये)",

    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",

    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    //mr
    selectWard: "कृपया प्रभाग निवडा ",
    selectZone: "कृपया झोन निवडा ",
    selectTitle: "कृपया शीर्षक निवडा ",
    placeMarriage: "कृपया  विवाहाचा ठिकाण भरा (इंग्लिश मध्ये)",
    placeMarriageMr: "कृपया  विवाहाचा ठिकाण भरा  (मराठी मध्ये)",

    pay: "पैसे भरा",
    titlemr: "शीर्षक ",
    title1: "Title ",
    newMRtable: "नवीन विवाह नोंदणी",
    module: "विवाह नोंदणी",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    masters: "मास्टर्स",
    transactions: "ट्रैन्ज़ैक्शन",
    reports: "अहवाल",
    receipt: "पावती",
    usertask: "User task",
    serviceChargeTypeName: "सेवा शुल्काचा प्रकार",

    chargeName: "शुल्काचा प्रकार",
    masters: "मास्टर्स",
    masterPath: "तक्रार निरीक्षण / मास्टर्स",

    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    //mr
    MrMasters: "विवाह नोंदणी/ मास्टर ",
    marriageRegistrationMaritalStatus: "विवाह नोंदणी/ मास्टर / वैवाहिक स्थिती",

    marriageRegistrationrelation: "विवाह नोंदणी/ मास्टर / नाते",

    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",

    documentUpload: "दस्तऐवज अपलोड",
    addFile: "फाइल जोडा",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    verify: "सत्यापित",
    reject: "नाकारा",
    noFileFound: "कोणतीही फाइल आढळली नाही",
    verified: "तपासून झाले",

    upload: "अपलोड करा",
    next: "पुढे",
    preview: "पूर्वावलोकन",

    attachFile: "फाईल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    serviceName: "सेवेचे नाव ",
    //titles

    calendarScheduling: " दिनदर्शिका शेड्युलिंग",
    maritialSatus: "वैवाहिक स्थिती",
    relation: "नाते",
    //field label
    srNo: "अनु क्रमांक",
    actions: "क्रिया ",
    statusDetails: "स्थिती तपशील",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ApplicatCheck1: "जर अर्जदार वर असेल तर",
    ApplicatCheck2: "जर अर्जदार वधु असेल तर",

    transactions: " ट्रैन्ज़ैक्शन",
    transactionPath: "कायदेशीर प्रकरण/  ट्रैन्ज़ैक्शन ",

    //mr
    // instrustion
    onlyMHR:
      "महाराष्ट्रातील विवाहाचे रजिस्ट्रेशन केले जाते आणि वधू किंवा वर यापैकी एक जण पिंपरी चिंचवड महानगर पालिकेच्या हद्दी मधील रहिवासी असावा.",
    docNote:
      "आयडी पुरावा, रहिवासी पुरावा, वयाचा पुरावा वेगळा असावा, (लग्नाच्या वेळी स्थिती असल्यास मागील स्टेटस प्रूफमध्ये मूल्य असते विधवा/विधुर किंवा घटस्फोटीत आहे) आधारकार्ड पुरावा जोडल्यास व नागरिक भाड्याने राहत असलेस नोंदणीकृत करारनामा आवश्यक आहे.",

    //aprove
    GPhoto: "वरचा फोटो  ",
    Bphoto: "वधुचा फोटो  ",
    witnessphto1: "साक्षीदारचा १ फोटो  ",
    witnessphto2: "साक्षीदारचा २ फोटो  ",
    witnessphto3: "साक्षीदारचा ३ फोटो  ",
    Gthumb: "वरचा अंगठाचा ठसा  ",
    Bthumb: "वधुचा अंगठाचा ठसा  ",
    witnessthumb1: "साक्षीदारचा १ अंगठाचा ठसा  ",
    witnessthumb2: "साक्षीदारचा २ अंगठाचा ठसा  ",
    witnessthumb3: "साक्षीदारचा ३ अंगठाचा ठसा  ",

    //table
    Tnc: "नियम व अटी",
    newMRtable: "नवीन विवाह नोंदणी",
    boardtitle: "विवाह मंडळाची माहिती",
    zone: "झोन",
    ward: "वार्ड",
    Addrees: "अर्जदाराचा रहिवासाचा पत्ता :",

    CrrtAdree: "सध्याचा रहिवासाचा पत्ता :",
    parmtAdree: "कायमचा रहिवासाचा पत्ता :",
    personalDetails: "वैयक्तिक माहिती :",
    Adress: "पत्ता :",
    BriNBM: "  (  लग्नाआधीचे नाव)",
    AppliToGroom: "",
    AppliToBride: "",
    marrigeDetails: "विवाहाची माहिती :",
    marrigeDate: "विवाहाची दिनांक",

    //title
    ApplicatDetails: "अर्जदाराची माहिती",
    ApplicatName: "अर्जदाराच नाव",
    groomDetail: "वराची माहिती",
    groomParaentDetail: "वराच्या पालकांची माहिती",
    brideDetails: "वधुची माहिती",
    brideParaentDetail: "वधुच्या पालकांची माहिती",
    priestDetails: "पुजारी माहिती",
    witness: "साक्षीदार",
    witnessDetails: "साक्षीदार माहिती",
    documentsUpload: "दस्तऐवज अपलोड",
    boardDetail: "विवाह मंडळाची माहिती :",
    otherDetail: "इतर तपशील",

    // viceversa
    titleV: "Title  ",
    firstNameV: "First Name  ",
    middleNameV: "Middle Name  ",
    lastNameV: "Last Name  ",

    //groom
    title: "शीर्षक",
    firstName: "प्रथम नाव (इंग्लिश मध्ये) ",
    middleName: "मधले नाव (इंग्लिश मध्ये) ",
    lastName: "आडनाव (इंग्लिश मध्ये) ",
    firstNamemr: "प्रथम नाव (मराठी मध्ये) ",
    middleNamemr: "मधले नाव (मराठी मध्ये) ",
    lastNamemr: "आडनाव (मराठी मध्ये) ",
    BirthDate: "जन्म दिनांक  ",
    Gender: "लिंग",
    AadharNo: "आधार नंबर",
    Age: "वय (लग्नाच्या वेळीचे वय)",
    mobileNo: "दूरध्वनी क्रमांक",
    phoneNo: "फोन नंबर",
    email: "ई-मेल",

    flatBuildingNo: "फ्लॅट नंबर (इंग्लिश मध्ये) ",
    buildingName: "अपार्टमेंट नाव (इंग्लिश मध्ये) ",
    roadName: "गल्लीचे नाव (इंग्लिश मध्ये) ",
    Landmark: "जमीन चिन्ह (इंग्लिश मध्ये) ",
    villageName: "Village Name (In English) ",
    cityName: "शहराचे नाव (इंग्लिश मध्ये) ",

    flatBuildingNomr: "फ्लॅट नंबर (मराठी मध्ये) ",
    buildingNamemr: "अपार्टमेंट नाव (मराठी मध्ये) ",
    roadNamemr: "गल्लीचे नाव (मराठी मध्ये) ",
    Landmarkmr: "जमीन चिन्ह (मराठी मध्ये) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "शहराचे नाव (मराठी मध्ये) ",

    // flatBuildingNo: 'फ्लॅट नंबर',
    // buildingName: 'अपार्टमेंट नाव',
    // roadName: 'गल्लीचे नाव',
    // Landmark: 'जमीन चिन्ह',
    // villageName: 'गावाचे नाव ',
    // cityName: 'शहराचे नाव',
    // state: "राज्य (इंग्लिश मध्ये) ",
    // statemr: "राज्य (मराठी मध्ये)  ",

    pincode: "पिन कोड",
    Religion1: "जन्माने धर्म",
    Religion2: "दत्तक घेऊन धर्म",
    StatusOfMarrige: "लग्नाच्या वेळची स्थिती",
    AgeDocument: "वयाचे कागदपत्र",
    IdDocument: "ओळख कागदपत्र ",
    residentialDocument: "रहिवाशी कागदपत्र",
    StatusOfDocument: "कागदपत्र स्थिती ",

    //groomFather
    firstNameF: "वडिलांचं प्रथम नाव  ",
    middleNameF: "वडिलांचं मधले नाव  ",
    lastNameF: "वडिलांचं आडनाव  ",
    AgeF: "वडिलांच वय",
    mobileNoF: "वडिलांचं दूरध्वनी क्रमांक",
    AadharNoF: "वडिलांचं आधार नंबर",

    //groomMother
    firstNameM: "आईचे प्रथम नाव  ",
    middleNameM: "आईचे मधले नाव  ",
    lastNameM: "आईचे आडनाव  ",
    AgeM: "आईचे वय",
    mobileNoM: "आईचे दूरध्वनी क्रमांक",
    AadharNoM: "आईचे आधार नंबर",

    //prist
    placeofMarriage: "लग्नाचे ठिकाण (इंग्लिश मध्ये)",
    placeofMarriage1: "लग्नाचे ठिकाण (मराठी मध्ये) ",

    //witness
    address: "पत्ता",
    wRelation: "साक्षीदारशी नाते",
    wDocument: "साक्षीदाराचे कागदपत्र",
    witnessAdd: "साक्षीदार जोडा",

    //Document

    DBProof: "जन्म तारीख पुरावा",
    ResProof: "रहिवासाचा पुरावा",
    IdProof: "ओळखपत्र पुरावा",
    ResProofW1: "प्रथम साक्षीदार रहिवासाचा पुरावा",
    ResProofW2: "द्वितीय साक्षीदार रहिवासाचा पुरावा",
    ResProofW3: "तृतिय साक्षीदार रहिवासाचा पुरावा",
    marrigeRelatedDoc: "विवाह संबंधित दस्तऐवज",

    invetaionCard: "विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र ",
    marrigePhotoC: "विवाह छायाचित्र (जोडीचे) ",
    marDrf: "१०० रुपयांच्या स्टॅम्प पेपरवर अर्जाचा मसुदा तयार करा",

    DivorcePaper: "वैध घटस्फोट कागद (लागू असल्यास)",
    DeathC: "मृत्यू प्रमाणपत्र (लागू असल्यास)",
    certiByReligiousPlc: " मंदिर, मशीद इ. धार्मिक स्थळाद्वारे जारी केलेले प्रमाणपत्र",
    docFormat: " (फक्त jpg.jpeg.png.bmp.pdf फाइल अपलोड करण्याची परवानगी आहे. फोटो आकार कमाल 100 kb)",
    enterDoc: "दस्तऐवजाच नाव ",

    //board
    applicantName: "अर्जादारच नाव :",
    boardNameT: "विवाह मंडळचे नाव",
    boardName: "विवाह मंडळचे नाव (इंग्लिश मध्ये) ",
    boardNamemr: "विवाह मंडळचे नाव (मराठी मध्ये) ",

    remark: "शेरा",
    documentList: "दस्तऐवज यादी",
    ValidtyofMBR: "विवाह मंडळाची अंतिम वैधता",
    documentsUploadF: "दस्तऐवज अपलोड",
    TandC: "",
    //button
    back: "मागे",
    next: "पुढे",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    submit: "प्रस्तुत करणे",
    addFile: "फाइल जोडा",

    //table filed
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    hName: "वरचे नाव",
    wName: "वधूचे नाव",
    ApplicantName: "अर्जादारच नाव",

    //brudcrum
    newMarriageRegistration: "विवाह नोंदणी / नवीन विवाह नोंदणी ",
    BoardMarriageRegistration: "विवाह मंडळ नोंदणी / नवीन विवाह मंडळ नोंदणी ",

    //module: 'शहर नियोजन',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    // master: 'मास्टर्स',
    // transactions: 'व्यवहार',
    // report: 'अहवाल',
    // masterPath: 'शहर नियोजन/ मास्टर ',
    // transactionPath: 'शहर नियोजन/ व्यवहार ',
    // reportPath: 'शहर नियोजन/ अहवाल ',

    // //breadcrum
    // landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
    // tdrZoneGatAndVillageMappingPath:
    //   'शहर नियोजन/ मास्टर / टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntryPath:
    //   'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignationPath:
    //   'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',

    // //titles
    // landReservation: 'जमीन आरक्षण',
    // tdrZoneGatAndVillageMapping: 'टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',

    // //other labels
    // landReservationID: 'जमीन आरक्षण क्र',
    // reservationName: 'आरक्षणाचे नाव',
    // reservationNameEng: 'आरक्षणाचे नाव इंग्रजीत',
    // reservationNameMr: 'आरक्षणाचे नाव मराठीत',
    // surveyNumber: 'सर्वेक्षण क्र',
    // landReservationLegend: 'जमीन आरक्षण आख्यायिका',
    // reservationAreaInHector: 'हेक्टर मध्ये आरक्षण क्षेत्र',
    // landInPossession: 'ताब्यात जमीन',
    // remark: 'टिप्पणी',
    // villageName: 'गावाचे नाव',
    // gatName: 'गटाचे नाव',
    // zoneName: 'झोनचे नाव',
    // landReservationName: 'जमीन आरक्षण नाव',
    // citySurveyNo: 'शहर सर्वेक्षण क्र',
    // reservationNo: 'आरक्षण क्र',
    // landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
    // landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
    // ddtp: 'डी.डी.टी.पी',
    // deAndTp: 'उपअभियंता /नगर नियोजक',
    // atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',

    // attachFile: 'फाईल जोडा',
    // srNo: 'अनु क्र',
    // actions: 'क्रिया ',

    // //buttons
    // add: 'जोडा',
    // save: 'जतन करा',
    // update: 'अद्यायावत करा',
    // clear: 'रिक्त',
    // exit: 'बाहेर पडा',
    // back: 'मागे',
    // saveAndNext: 'जतन करा आणि पुढे',
    // finish: 'समाप्त',

    //ReIssuance of Marriage Certificate

    onlyRIMC: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    mRegNo: "विवाह रजि क्र",
    marriageDate: "लग्नाची तारीख",
    marriageYear: "लग्नाचे वर्ष",
    brideName: "वधूचे नाव",
    groomName: "वराचे नाव",
    regDate: "नोंदणी दिनांक",

    //Renewal of Marriage Board Registration
    onlyRMBR: "विवाह मंडळ नोंदणीचे नूतनीकरण",
    mbrName: "विवाह मंडळ नोंदणी नाव",
    mbrDate: "विवाह मंडळ नोंदणी तारीख",
    mbrYear: "विवाह मंडळ नोंदणी वर्ष",
    search: "शोधा",

    //Application Details

    onlyApplDetail: "अर्ज तपशील",
    applFName: "अर्जदाराचे पहिले नाव",
    applMName: "अर्जदाराचे मधले नाव",
    applLName: "अर्जदार आडनाव",
    groomFName: "वराचे पहिले नाव",
    groomMName: "वराचे मधले नाव",
    groomLName: "वराचे आडनाव",
    brideFName: "वधूचे पहिले नाव",
    brideMName: "वधू मधले नाव",
    brideLName: "वधू आडनाव",
    mDate: "लग्नाची तारीख",

    //ReIssuance of marriage Certificate
    newRMItable: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    applFullName: "अर्जदाराचे पूर्ण नाव",
    applicationNo: "अर्ज क्र",
    applicationDate: "अर्ज तारीख",
  },
};
