export default {
  en: {
    petLicense: "Pet License",
    petAnimal: "Pet Animal",
    area: "Area",
    zone: "Zone",
    ward: "Ward",
    flatOrHouseNo: "Flat/House No.",
    buildingName: "Building Name",
    detailAddress: "Detail Address",
    ownerName: "Owner Name",
    mobileNo: "Mobile no.",
    emailId: "Email ID",
    petName: "Pet Name",
    petBirthdate: "Pet Birthdate",
    animalBreed: "Animal Breed",
    animalColor: "Animal Color",
    animalAge: "Animal Age (in YY:MM)",
    animalWeight: "Animal Weight (in kg)",
    animalGender: "Animal gender",
    antiRabiesVaccinationStatus: "Anti-Rabies Vaccination Status",
    vaccinationDate: "Vaccination Date",
    veterinaryDoctorsName: `Veterinary Doctor's Name`,
    documents: "Documents",
    vaccinationPDF: "Vaccination PDF",
    animalPhoto: "Animal Photo",
    remark: "Remark",
    status: "Status",
    petAnimalEn: "Pet Animal name in English",
    petAnimalMr: "Pet Animal name in Marathi",
    petBreed: "Pet Breed",
    breedNameEn: "Breed name in English",
    breedNameMr: "Breed name in Marathi",
    ownerPhotoID: "Owner ID Proof",
    makePayment: "Make Payment",
    generateLicense: "Generate License",
    viewLicense: "View License",
    licenseFor: "License For",
    pcmc: "Pimpri-Chinchwad Municipal Corporation",
    fiscalYear: "F.Y.",
    officeCopy: "OFFICE COPY",
    customerCopy: "CUSTOMER COPY",
    receiptNo: "Receipt No.",
    date: "Date",
    relatedTo: "Related To",
    cfcRefNo: "CFC Ref. No",
    cfcCounterNo: "CFC Counter No.",
    receivedFrom: "Received From",
    serviceName: "Service Name",
    narration: "Narration",
    address: "Address",
    paymentMode: "Payment Mode",
    rupees: "Rupees",
    chequeNo: "Cheque No.",
    chequeDate: "Cheque Date",
    bankName: "Bank Name",
    referenceNo: "Reference No.",
    applicationDate: "Application Date",
    details: "Details",
    payableAmount: "Payable Amount",
    receivedAmount: "Received Amount",
    rebateAmount: "Rebate/Concession Amount",
    advanceAmount: "Advance Amount",
    actualPayableAmount: "Actual Payable Amount",
    totalAmount: "Total Amount",
    amountInWords: "Amount in Words",
    receiverSignature: `Receiver's Signature`,
    tip: "Tip",
    printBy: "Printed By",
    printDateAndTime: "Print Date and Time",
    casePaperNo: "Case Paper No.",
    licenseNo: "License No.",
    ownerAddress: "Owner Address",
    symptoms: "Symptoms",
    aknowledgementSlipNo: "Acknowledgement Slip No. (numeric)",
    diagnosisDetail: "Diagnosis Details",
    medicineDetails: "Medicine Details",
    treatment: "Treatment",
    payment: "Payment",
    payerName: "Payer Name",
    payerAddress: "Payer Address",
    receiptDate: "Receipt Date",
    transactionDate: "Transaction Date",
    treatmentCategory: "Treatment Category",
    casePaperDate: "Case Paper Date",
    accountGlCode: "GL Account Code",
    opd: "OPD",
    lattitude: "Lattitude",
    longitude: "Longitude",
    city: "City",
    state: "State",
    pincode: "Pincode",
    amount: "Amount",
    paymentType: "Payment Type",
    cfcCode: "CFC Code",
    ddNo: "Demand Draft's No.",
    ddDate: "Demand Draft's Date",
    branchName: "Branch Name",
    ifscCode: "IFSC Code",
    accountNo: "Account No.",
    caseEntry: "Case Entry",
    oldLicense: "Old License",
    fromDate: "From Date",
    toDate: "To Date",
    officeType: "Office Type",
    opdPrefix: "OPD Prefix",
    opdNo: "OPD No",
    opdName: "OPD Name",
    opdOpeningTime: "OPD Opening Time",
    opdClosingTime: "OPD Closing Time",
    opdWorkingDays: "OPD Working Days",
    labFacility: "Lab Facility",
    xRayFacility: "X-Ray Facility",
    opdAddress: "OPD Address",
    flatOrBuildingNo: "Flat/Building No.",
    roadName: "Road Name",
    landmark: "Landmark",
    ipdPrefix: "IPD Prefix",
    ipdNo: "IPD No",
    ipdName: "IPD Name",
    ipdOpeningTime: "IPD Opening Time",
    ipdClosingTime: "IPD Closing Time",
    ipdWorkingDays: "IPD Working Days",
    ipdAddress: "IPD Address",
    totalApplications: "Total Applications",
    paidApplications: "Paid Applications",
    notPaidApplications: "Not Paid Applications",
    approved: "Approved",
    reassigned: "Reassigned",
    pending: "Pending",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory or Optional",
    upload: "Upload",
    mandatory: "Mandatory",
    optional: "Optional",
    uploadWarning: "Please upload file (PDF/JPG/JPEG/PNG) with size less than 2MB !",
    medicine: "Medicine",
    days: "Days",
    dosage: "Dosage",
    addMedicine: "Add Medicine",
    prescription: "Prescription",
    casePaperReceipt: "Case Paper Receipt",
    smallPetIncinerator: "Small Pet Incinerator",
    applicationNo: "Application No.",
    teamName: "Team Name",

    search: "Search",
    preview: "Preview",
    addFile: "Add File",
    srNo: "Sr. No",
    actions: "Actions",
    approve: "Approve",
    reassign: "Reassign",
    agreeAndNext: "Agree & Next",
    // ipd feild
    // ipd: "Ipd",
    // opdNo: "Opd Number",
    // casePaperNo: "Case Paper Number",
    // casePaperDate: "Case Paper Date",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    print: "Print",
  },
  mr: {
    petLicense: "पाळीव प्राणी परवाना",
    petAnimal: "पाळीव प्राणी",
    area: "क्षेत्र",
    zone: "विभाग",
    ward: "प्रभाग",
    flatOrHouseNo: "फ्लॅट/घर क्र.",
    buildingName: "इमारतीचे नाव",
    detailAddress: "पूर्ण पत्ता",
    ownerName: "मालकाचे नाव",
    mobileNo: "मोबाईल नं",
    emailId: "इमेल पत्ता",
    petName: "पाळीव प्राण्याचे नाव",
    petBirthdate: "पाळीव प्राण्याची जन्मतारीख",
    animalBreed: "प्राण्याची जाती",
    animalColor: "प्राण्याचा रंग",
    animalAge: "प्राण्याचं वय (YY:MM मध्ये)",
    animalWeight: "प्राण्याचं वजन (किलोग्राम मध्ये)",
    animalGender: "प्राण्याचं लिंग",
    antiRabiesVaccinationStatus: "रेबीजविरोधी लसीकरण स्थिती",
    vaccinationDate: "लसीकरणची तारीख",
    veterinaryDoctorsName: "पशुवैद्यकीय डॉक्टरांचे नाव",
    documents: "कागदपत्रे",
    vaccinationPDF: "लसीकरणाची PDF",
    animalPhoto: "प्राण्याचा फोटो",
    remark: "टिप्पणी",
    status: "अर्ज स्थिती",
    petAnimalEn: "पाळीव प्राण्याचे इंग्रजीत नाव",
    petAnimalMr: "पाळीव प्राण्याचे मराठीत नाव",
    petBreed: "पाळीव प्राण्याची जाती",
    breedNameEn: "जातीचं नाव इंग्रजीत",
    breedNameMr: "जातीचं नाव मराठीत",
    ownerPhotoID: "मालकाचा ओळख पुरावा",
    makePayment: "पैसे भरा",
    generateLicense: "परवाना निर्मिती",
    viewLicense: "परवाना पहा",
    licenseFor: "कुठल्या पाळीव प्राण्यासाठी",
    pcmc: "पिंपरी चिंचवड महानगरपालिका",
    fiscalYear: "सन",
    officeCopy: "कार्यालयाची प्रत",
    customerCopy: "ग्राहकाची प्रत",
    receiptNo: "पावती क्र.",
    date: "तारीख",
    relatedTo: "विभागाकडून",
    cfcRefNo: "सीएफसी संदर्भ क्रं",
    cfcCounterNo: "सीएफसी काउंटर क्रं",
    receivedFrom: "कोणाकडून",
    serviceName: "सेवेचे नाव",
    narration: "विवरण",
    address: "पत्ता",
    paymentMode: "देय प्रकार",
    rupees: "रुपये",
    chequeNo: "धनादेश क्रं.",
    chequeDate: "धनादेश क्रं",
    bankName: "बँकेचे नाव",
    referenceNo: "संदर्भ क्रं.",
    applicationDate: "अर्जाची तारीख",
    details: "तपशील",
    payableAmount: "देय रक्कम",
    receivedAmount: "स्वीकारलेली रक्कम",
    rebateAmount: "सूट/सवलत रक्कम",
    advanceAmount: "आगाऊ रक्कम",
    actualPayableAmount: "एकूण देय रक्कम",
    totalAmount: "एकूण रक्कम",
    amountInWords: "एकूण रक्कम शब्दांमध्ये",
    receiverSignature: "स्वीकारनाऱ्याची स्वाक्षरी",
    tip: "टीप",
    printBy: "छापनार्याचे नाव",
    printDateAndTime: "छापतांना तारीख आणि वेळ",
    casePaperNo: "केसपेपर क्र.",
    licenseNo: "परवाना क्र.",
    ownerAddress: "मालकाचा पत्ता",
    symptoms: "लक्षणं",
    aknowledgementSlipNo: "पोच पावती क्र. (क्रमांक)",
    diagnosisDetail: "निदान तपशील",
    medicineDetails: "औषध तपशील",
    treatment: "उपचार",
    payment: "पैसे भरणे",
    payerName: "देयकाचे नाव",
    payerAddress: "देयकाचा पत्ता",
    receiptDate: "पावतीची तारीख",
    transactionDate: "ट्रांसकशनची तारीख",
    treatmentCategory: "उपचार श्रेणी",
    casePaperDate: "केस पेपरची तारीख",
    accountGlCode: "जीएल खात्याचा कोड",
    opd: "ओपीडी",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    city: "शहर",
    state: "राज्य",
    pincode: "पिनकोड",
    amount: "रक्कम",
    paymentType: "पैसे भरण्याची पध्दत",
    cfcCode: "सीएफसी कोड",
    ddNo: "डिमांड ड्राफ्ट क्र",
    ddDate: "डिमांड ड्राफ्टची तारीख",
    branchName: "शाखेचे नाव",
    ifscCode: "आयएफएससी कोड",
    accountNo: "खाते क्रमांक",
    caseEntry: "केस एंट्री",
    oldLicense: "जुनं परवाना",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    officeType: "कार्यालयाचा प्रकार",
    opdPrefix: "ओपीडी उपसर्ग",
    opdNo: "ओपीडीचा क्रमांक",
    opdName: "ओपीडीचे नाव",
    opdOpeningTime: "ओपीडी उघडण्याची वेळ",
    opdClosingTime: "ओपीडी बंद होण्याची वेळ",
    opdWorkingDays: "ओपीडीचे कामाचे दिवस",
    labFacility: "प्रयोगशाळा सुविधा",
    xRayFacility: "क्ष-किरण सुविधा",
    opdAddress: "ओपीडीचा पत्ता",
    flatOrBuildingNo: "फ्लॅट/इमारत क्र.",
    roadName: "रस्त्याचं नाव",
    landmark: "महत्त्वाची खूण",
    ipdPrefix: "आयपीडी उपसर्ग",
    ipdNo: "आयपीडीचा क्रमांक",
    ipdName: "आयपीडीचे नाव",
    ipdOpeningTime: "आयपीडी उघडण्याची वेळ",
    ipdClosingTime: "आयपीडी बंद होण्याची वेळ",
    ipdWorkingDays: "आयपीडीचे कामाचे दिवस",
    totalApplications: "एकूण अर्जदार",
    paidApplications: "पैसे भरलेले अर्जदार",
    notPaidApplications: "पैसे न भरलेले अर्जदार",
    approved: "एकूण मंजूर परवाना",
    reassigned: "एकूण रद्द परवाना",
    pending: "प्रलंबित अर्ज",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    uploadWarning: "कृपया 2MB पेक्षा कमी आकाराची फाइल (PDF/JPG/JPEG/PNG) अपलोड करा !",
    medicine: "औषध",
    days: "दिवस",
    dosage: "डोस",
    addMedicine: "औषध जोडा",
    prescription: "पावती",
    casePaperReceipt: "केस पेपर पावती",
    smallPetIncinerator: "लहान पाळीव प्राण्याचा अंतिम संस्कार",
    applicationNo: "अर्ज क्रमांक",
    teamName: "संघाचे नाव",

    search: "शोधा",
    preview: "पूर्वावलोकन",
    addFile: "फाइल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    approve: "मंजूर",
    reassign: "पुन्हा नियुक्त करा",
    agreeAndNext: "सहमत आणि पुढे",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    print: "छापणे",
  },
};
