export default { 
    en: 
    { 
        pcmcName: "Pimpri Chinchwad Municipal Corporation", 
        pcmcNameNew: "Pimpri Chinchwad Citizen Service Portal", 
        welcomeTo: "WELCOME TO", 
        citizen: "CITIZEN", 
        department: "DEPARTMENT", 
        cfcUser: "CFC USER", 
        citizenCred: "Citizen Email Id/Phone number",
        departmentCred: "Department User Email Id/Phone number", 
        cfcCred: "CFC User Email Id/Phone number", 
        password: "Password", 
        verifyMe: "Verify Me", 
        forgotPassword: "Forgot Password?", 
        or: "Or", 
        dontHaveAnAccount: "Don't have an account?", 
        signUpHere: "Sign Up Here", 
        login: "Login", 
        footer: "© 2023, developed by Nascent Infotechnologies Pvt. Ltd. & ATOS", 
        googleMarthiTrans: "Download Google Marathi Translator",
     }, 
     mr: 
     { 
        pcmcName: "पिंपरी-चिंचवड महानगरपालिका", 
        pcmcNameNew: "पिंपरी चिंचवड सिटीझन सर्व्हिस पोर्टल", 
        welcomeTo: "आपले स्वागत आहे", 
        citizen: "नागरिक", 
        department: "विभाग", 
        cfcUser: "सीएफसी वापरकर्ता", 
        citizenCred: "नागरिक ईमेल आयडी/फोन नंबर", 
        departmentCred: "विभाग वापरकर्ता ईमेल आयडी/फोन नंबर", 
        cfcCred: "सीएफसी वापरकर्ता ईमेल आयडी/फोन नंबर", 
        password: "पासवर्ड", 
        verifyMe: "माझी पडताळणी करा", 
        forgotPassword: "पासवर्ड विसरलात?", 
        or: "किंवा", 
        dontHaveAnAccount: "खाते नाही?", 
        signUpHere: "येथे साइन अप करा", 
        login: "लॉगिन करा", 
        footer: "© 2023, नासेंट इन्फोटेक. प्रा. लि. आणि अँटोस द्वारा विकसित.", 
        googleMarthiTrans: "गुगल मराठी अनुवादक डाउनलोड करा", 
    }, 
};
